/* @date 2025-04-10T02:14:49.717307620Z */

/**********************************************************************
 * @file Button_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
 **********************************************************************/

#ifndef CSE_BUTTON_ITF_H
#define CSE_BUTTON_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Button_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* Trigger functions */
	/* @generated_from _2022x_1ad00ce_1659683574035_551596_3462 */
	/* @generated_from _2022x_1ad00ce_1659688230703_340985_4140 */  
	void (*Trigger_control_On)(void);
	/* @generated_from _2022x_1ad00ce_1659683574035_551596_3462 */
	/* @generated_from _2022x_1ad00ce_1659688235695_364403_4143 */  
	void (*Trigger_control_Off)(void);
	/* Read functions */
	/* @generated_from _2022x_1_1ad00ce_1677833598836_377885_3507 */
	/* @generated_from _2022x_2_16600ad_1710514982431_30757_4430 */  
	void (*Read_button_button)(Boolean* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Button *parent;
}Cse_Button_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from _2022x_1ad00ce_1659686618091_973487_3644 */ 
void Button_Button_init(Cse_Button_Struct* self);
void Button_Button(Cse_Button_Struct* instance);
void Button_Button_end(Cse_Button_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from _2022x_1ad00ce_1659686618091_973487_3644 */ 
#define Button(...) Button_Button(__VA_ARGS__)
/* @generated_from _2022x_1ad00ce_1659686618091_973487_3644 */ 
#define Button_init(...) Button_Button_init(__VA_ARGS__)
/* @generated_from _2022x_1ad00ce_1659686618091_973487_3644 */ 
#define Button_end(...) Button_Button_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */

/* Trigger functions declaration */
/* @generated_from _2022x_1ad00ce_1659683574035_551596_3462 */
/* @generated_from _2022x_1ad00ce_1659688230703_340985_4140 */  
void Cse_Trigger_control_On(Cse_Button_Struct* instance);
/* @generated_from _2022x_1ad00ce_1659683574035_551596_3462 */
/* @generated_from _2022x_1ad00ce_1659688235695_364403_4143 */  
void Cse_Trigger_control_Off(Cse_Button_Struct* instance);

/* Read functions declaration */
/* @generated_from _2022x_1_1ad00ce_1677833598836_377885_3507 */
/* @generated_from _2022x_2_16600ad_1710514982431_30757_4430 */
void Cse_Read_button_button(Cse_Button_Struct* instance, Boolean* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Trigger_control_On(inst) inst->Trigger_control_On()
#define Cse_Trigger_control_Off(inst) inst->Trigger_control_Off()
#define Cse_Read_button_button(inst, data) inst->Read_button_button(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_BUTTON_ITF_H */

/* end of file */
