/* @date 2025-04-10T02:14:49.692758914Z */

/**********************************************************************
 * @file Button_Button.h
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659686618091_973487_3644
 **********************************************************************/

#ifndef BUTTON_BUTTON_H
#define BUTTON_BUTTON_H

#include "Button_itf.h" /* Datatypes defined at interfaces */
#include "Button_internal_types.h" /* Datatypes for internal data */

#include "Button_Button_Send_Off.h"
#include "Button_Button_Send_On.h"

/* BEG_USER_CODE(types) do not remove */

#ifndef WALLCLOCK_T
#define WALLCLOCK_T WALLCLOCK_T
typedef double  WALLCLOCK_T;  /* time type (can be any scalar) */
#endif
#ifndef USERDATA_T
#define USERDATA_T  USERDATA_T
typedef void *  USERDATA_T;   /* replace this pointer by an anonymous struct if needed. */
#endif

/* END_USER_CODE(types) do not remove */

typedef enum {
    BUTTON_STATE_T_INITIAL_0,
    BUTTON_STATE_T_off,
    BUTTON_STATE_T_on,
    BUTTON_STATE_T_VOID
} BUTTON_STATE_T;

typedef enum {
    BUTTON_EVENT_T_NO_EVENT
} BUTTON_EVENT_T;

typedef struct Button_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Button_struct*);

    /* user data */
    USERDATA_T              USERDATA;

    /* data */
    Boolean                 button_button;

    /* sub behaviors */
    Button_Send_Off_struct  on_Effect_Button_Send_Off;
    Button_Send_On_struct   on_Entry_Button_Send_On;

    /* pointer to classifier */
    struct Button* classifier;

    /* internal */
    BUTTON_STATE_T          CURRENT_STATE_0;
    WALLCLOCK_T             WALL_CLOCK;
    BUTTON_EVENT_T          EVENT;
    Boolean                 FIRST;
    Boolean                 DONE_ACTIVITY;
} Button_struct;

void Button_struct_ctor(struct Button_struct * const self, struct Button* classifier);
void _basic_Button_init(Button_struct *instance);
void _basic_Button(Button_struct *instance);
void _basic_Button_end(Button_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*BUTTON_BUTTON_H*/
/* end of file */
