/* @date 2025-04-10T02:14:49.724801637Z */

/**********************************************************************
 * @file Button.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
 **********************************************************************/

#ifndef BUTTON_H
#define BUTTON_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Button_itf.h"
#include "Button_internal_types.h"
#include "Button_Button.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from _2022x_1ad00ce_1659678969433_444652_3277 */	 
typedef struct Button{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Button*);

	/**
	 * @brief Public attribute for composition relation to Boolean:pinData
	 * @generated_from _2022x_1_1ad00ce_1678450549864_650375_4760
	 */
	Boolean pinData;
		
	/**
	 * Data for Behavior Button
	 * @generated_from _2022x_1ad00ce_1659686618091_973487_3644
	 */
	Button_struct Button;

	/**********************************************************************
	 * Communication Interface section
	 **********************************************************************/
	/**
	 * Communication interface
	 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
	 */
	Cse_Button_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Button;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
 */
void Button_ctor(Button* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef BUTTON_H

/* end of file */