/* @date 2025-04-10T02:14:49.738162557Z */

/**********************************************************************
 * @file Counter_type.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from _2022x_1_1ad00ce_1679314077359_990669_5639
 **********************************************************************/

#ifndef COUNTER_TYPE_H
#define COUNTER_TYPE_H

#include <stddef.h>
/* stdbool.h define standard bool (true/false) starting from C99 standard */ 
#include <stdbool.h>

/**********************************************************************
 * Data Type Boolean definition
 **********************************************************************/
#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool Boolean;
#endif /* Boolean */

/**********************************************************************
 * Data Type Integer definition
 **********************************************************************/
#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int Integer;
#endif /* Integer */

#endif /* COUNTER_TYPE_H */

/* end of file */
