/* @date 2025-04-10T02:14:49.737203370Z */

/**********************************************************************
 * @file Counter_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1_1ad00ce_1679314077359_990669_5639
 **********************************************************************/

#include "Counter.h"
#include "Counter_itf.h"
#include "Tal.h" // tal_getTime

/* end of file */
