/* @date 2025-02-27T05:05:36.385227132Z */

/**********************************************************************
 * @file Cse_Button_hook_cfg.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
 **********************************************************************/

#ifndef CSE_BUTTON_HOOK_CFG_H
#define CSE_BUTTON_HOOK_CFG_H

/**********************************************************************
 * Macros declaration definition
 **********************************************************************/
/* 
 * Define symbol ENABLE_HOOKS to enable the mechanism of hooks 
 * Enabled by default
 */
#define ENABLE_HOOKS
#ifdef ENABLE_HOOKS

#define Cse_ReadHook_Button_button_button
#define Cse_TriggerHook_Button_control_On
#define Cse_TriggerHook_Button_control_Off

#endif /* ENABLE_HOOKS */

#endif /* CSE_<?COMPONENT_NAME_DEFINE?>_HOOK_CFG_H */

/* end of file */
