/* @date 2025-04-10T02:14:49.396598370Z */

/**********************************************************************
 * @file Cse_Flashlight_hook.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 * 
 * @generated_from _2022x_1ad00ce_1659678666246_667973_3242
 **********************************************************************/


#ifndef CSE_FLASHLIGHT_HOOK_H
#define CSE_FLASHLIGHT_HOOK_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Cse_Flashlight_hook_cfg.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/**********************************************************************
 * Functions declaration
 **********************************************************************/
#if defined(Cse_ReadHook_Flashlight_timer_ipControl_On)
extern void Cse_ReadHook_Flashlight_timer_ipControl_On_Start(SignalEvent_On_type* pData);
extern void Cse_ReadHook_Flashlight_timer_ipControl_On_Return(SignalEvent_On_type* pData);
#else
#define Cse_ReadHook_Flashlight_timer_ipControl_On_Start(value)  ((void) (0))
#define Cse_ReadHook_Flashlight_timer_ipControl_On_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Flashlight_timer_ipControl_On */

#if defined(Cse_ReadHook_Flashlight_timer_ipControl_Off)
extern void Cse_ReadHook_Flashlight_timer_ipControl_Off_Start(SignalEvent_Off_type* pData);
extern void Cse_ReadHook_Flashlight_timer_ipControl_Off_Return(SignalEvent_Off_type* pData);
#else
#define Cse_ReadHook_Flashlight_timer_ipControl_Off_Start(value)  ((void) (0))
#define Cse_ReadHook_Flashlight_timer_ipControl_Off_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Flashlight_timer_ipControl_Off */

#if defined(Cse_ReadHook_Flashlight_light_ipTimer_Tick)
extern void Cse_ReadHook_Flashlight_light_ipTimer_Tick_Start(SignalEvent_Tick_type* pData);
extern void Cse_ReadHook_Flashlight_light_ipTimer_Tick_Return(SignalEvent_Tick_type* pData);
#else
#define Cse_ReadHook_Flashlight_light_ipTimer_Tick_Start(value)  ((void) (0))
#define Cse_ReadHook_Flashlight_light_ipTimer_Tick_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Flashlight_light_ipTimer_Tick */

#if defined(Cse_ReadHook_Flashlight_tempoManager_control_On)
extern void Cse_ReadHook_Flashlight_tempoManager_control_On_Start(SignalEvent_On_type* pData);
extern void Cse_ReadHook_Flashlight_tempoManager_control_On_Return(SignalEvent_On_type* pData);
#else
#define Cse_ReadHook_Flashlight_tempoManager_control_On_Start(value)  ((void) (0))
#define Cse_ReadHook_Flashlight_tempoManager_control_On_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Flashlight_tempoManager_control_On */

#if defined(Cse_ReadHook_Flashlight_tempoManager_control_Off)
extern void Cse_ReadHook_Flashlight_tempoManager_control_Off_Start(SignalEvent_Off_type* pData);
extern void Cse_ReadHook_Flashlight_tempoManager_control_Off_Return(SignalEvent_Off_type* pData);
#else
#define Cse_ReadHook_Flashlight_tempoManager_control_Off_Start(value)  ((void) (0))
#define Cse_ReadHook_Flashlight_tempoManager_control_Off_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Flashlight_tempoManager_control_Off */

#if defined(Cse_ReadHook_Flashlight_onCount_ipLight_light)
extern void Cse_ReadHook_Flashlight_onCount_ipLight_light_Start(Boolean* pData);
extern void Cse_ReadHook_Flashlight_onCount_ipLight_light_Return(Boolean* pData);
#else
#define Cse_ReadHook_Flashlight_onCount_ipLight_light_Start(value)  ((void) (0))
#define Cse_ReadHook_Flashlight_onCount_ipLight_light_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Flashlight_onCount_ipLight_light */

#if defined(Cse_ReadHook_Flashlight_timer_ipControl2_switchOff)
extern void Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Start(Boolean* pData);
extern void Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Return(Boolean* pData);
#else
#define Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Start(value)  ((void) (0))
#define Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Flashlight_timer_ipControl2_switchOff */

#if defined(Cse_ReadHook_Flashlight_button_button_button)
extern void Cse_ReadHook_Flashlight_button_button_button_Start(Boolean* pData);
extern void Cse_ReadHook_Flashlight_button_button_button_Return(Boolean* pData);
#else
#define Cse_ReadHook_Flashlight_button_button_button_Start(value)  ((void) (0))
#define Cse_ReadHook_Flashlight_button_button_button_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Flashlight_button_button_button */

#if defined(Cse_ReadHook_Flashlight_tempoManager_ipTempo_button)
extern void Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Start(Integer* pData);
extern void Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Return(Integer* pData);
#else
#define Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Start(value)  ((void) (0))
#define Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Flashlight_tempoManager_ipTempo_button */


#if defined(Cse_WriteHook_Flashlight_light_opLight_light)
extern void Cse_WriteHook_Flashlight_light_opLight_light_Start(Boolean* pData);
extern void Cse_WriteHook_Flashlight_light_opLight_light_Return(Boolean* pData);
#else
#define Cse_WriteHook_Flashlight_light_opLight_light_Start(value)  ((void) (0))
#define Cse_WriteHook_Flashlight_light_opLight_light_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_Flashlight_light_opLight_light */

#if defined(Cse_WriteHook_Flashlight_onCount_opCounts_data)
extern void Cse_WriteHook_Flashlight_onCount_opCounts_data_Start(Integer* pData);
extern void Cse_WriteHook_Flashlight_onCount_opCounts_data_Return(Integer* pData);
#else
#define Cse_WriteHook_Flashlight_onCount_opCounts_data_Start(value)  ((void) (0))
#define Cse_WriteHook_Flashlight_onCount_opCounts_data_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_Flashlight_onCount_opCounts_data */

#if defined(Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff)
extern void Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Start(Boolean* pData);
extern void Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Return(Boolean* pData);
#else
#define Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Start(value)  ((void) (0))
#define Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff */

#if defined(Cse_TriggerHook_Flashlight_timer_opLight_Tick)
extern void Cse_TriggerHook_Flashlight_timer_opLight_Tick_Start(SignalEvent_Tick_type* pData);
extern void Cse_TriggerHook_Flashlight_timer_opLight_Tick_Return(SignalEvent_Tick_type* pData);
#else
#define Cse_TriggerHook_Flashlight_timer_opLight_Tick_Start(value)  ((void) (0))
#define Cse_TriggerHook_Flashlight_timer_opLight_Tick_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Flashlight_timer_opLight_Tick */

#if defined(Cse_TriggerHook_Flashlight_button_control_On)
extern void Cse_TriggerHook_Flashlight_button_control_On_Start(SignalEvent_On_type* pData);
extern void Cse_TriggerHook_Flashlight_button_control_On_Return(SignalEvent_On_type* pData);
#else
#define Cse_TriggerHook_Flashlight_button_control_On_Start(value)  ((void) (0))
#define Cse_TriggerHook_Flashlight_button_control_On_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Flashlight_button_control_On */

#if defined(Cse_TriggerHook_Flashlight_button_control_Off)
extern void Cse_TriggerHook_Flashlight_button_control_Off_Start(SignalEvent_Off_type* pData);
extern void Cse_TriggerHook_Flashlight_button_control_Off_Return(SignalEvent_Off_type* pData);
#else
#define Cse_TriggerHook_Flashlight_button_control_Off_Start(value)  ((void) (0))
#define Cse_TriggerHook_Flashlight_button_control_Off_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Flashlight_button_control_Off */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CSE_<?COMPONENT_NAME_DEFINE?>_HOOK_H */

/* end of file */
