/* @date 2025-02-27T05:05:36.383921193Z */

/**********************************************************************
 * @file Cse_Button_hook.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 * 
 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
 **********************************************************************/


#ifndef CSE_BUTTON_HOOK_H
#define CSE_BUTTON_HOOK_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Cse_Button_hook_cfg.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/**********************************************************************
 * Functions declaration
 **********************************************************************/
#if defined(Cse_ReadHook_Button_button_button)
extern void Cse_ReadHook_Button_button_button_Start(Boolean* pData);
extern void Cse_ReadHook_Button_button_button_Return(Boolean* pData);
#else
#define Cse_ReadHook_Button_button_button_Start(value)  ((void) (0))
#define Cse_ReadHook_Button_button_button_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Button_button_button */


#if defined(Cse_TriggerHook_Button_control_On)
extern void Cse_TriggerHook_Button_control_On_Start(SignalEvent_On_type* pData);
extern void Cse_TriggerHook_Button_control_On_Return(SignalEvent_On_type* pData);
#else
#define Cse_TriggerHook_Button_control_On_Start(value)  ((void) (0))
#define Cse_TriggerHook_Button_control_On_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Button_control_On */

#if defined(Cse_TriggerHook_Button_control_Off)
extern void Cse_TriggerHook_Button_control_Off_Start(SignalEvent_Off_type* pData);
extern void Cse_TriggerHook_Button_control_Off_Return(SignalEvent_Off_type* pData);
#else
#define Cse_TriggerHook_Button_control_Off_Start(value)  ((void) (0))
#define Cse_TriggerHook_Button_control_Off_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Button_control_Off */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CSE_<?COMPONENT_NAME_DEFINE?>_HOOK_H */

/* end of file */
