/* @date 2025-04-10T02:14:49.397104470Z */

/**********************************************************************
 * @file Cse_Flashlight_hook_usr.c
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678666246_667973_3242
 **********************************************************************/

/*
 * define symbol USER_HOOKS to enable this file content on compiler 
 * command or uncomment following line
 */
/* #define USER_HOOKS */
#ifdef USER_HOOKS

#include "Cse_cfg.h"

#ifdef __cplusplus
// Code is compiled as C code even if the file is a cpp file
extern "C" {
#endif /* __cplusplus */

/* BEG_USER_CODE(HEADER) do not remove */
/* Add your includes here */
/* END_USER_CODE(HEADER) do not remove */

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl_On_Start
 * Start Hook to be overwritten to read On value on ipControl port
 * @generated_from _2022x_1ad00ce_1659683568410_618746_3444
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
*/
void Cse_ReadHook_Flashlight_timer_ipControl_On_Start(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683568410_618746_3444__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683568410_618746_3444__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl_On_Return
 * Return Hook to be overwritten to read On value on ipControl port
 * @generated_from _2022x_1ad00ce_1659683568410_618746_3444
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
*/
void Cse_ReadHook_Flashlight_timer_ipControl_On_Return(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683568410_618746_3444__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683568410_618746_3444__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl_Off_Start
 * Start Hook to be overwritten to read Off value on ipControl port
 * @generated_from _2022x_1ad00ce_1659683568410_618746_3444
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
*/
void Cse_ReadHook_Flashlight_timer_ipControl_Off_Start(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683568410_618746_3444__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683568410_618746_3444__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl_Off_Return
 * Return Hook to be overwritten to read Off value on ipControl port
 * @generated_from _2022x_1ad00ce_1659683568410_618746_3444
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
*/
void Cse_ReadHook_Flashlight_timer_ipControl_Off_Return(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683568410_618746_3444__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683568410_618746_3444__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_light_ipTimer_Tick_Start
 * Start Hook to be overwritten to read Tick value on ipTimer port
 * @generated_from _2022x_1ad00ce_1659683538905_142987_3408
 * @generated_from _2022x_1ad00ce_1659688287223_365621_4218
*/
void Cse_ReadHook_Flashlight_light_ipTimer_Tick_Start(SignalEvent_Tick_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683538905_142987_3408__2022x_1ad00ce_1659688287223_365621_4218) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683538905_142987_3408__2022x_1ad00ce_1659688287223_365621_4218) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_light_ipTimer_Tick_Return
 * Return Hook to be overwritten to read Tick value on ipTimer port
 * @generated_from _2022x_1ad00ce_1659683538905_142987_3408
 * @generated_from _2022x_1ad00ce_1659688287223_365621_4218
*/
void Cse_ReadHook_Flashlight_light_ipTimer_Tick_Return(SignalEvent_Tick_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683538905_142987_3408__2022x_1ad00ce_1659688287223_365621_4218) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683538905_142987_3408__2022x_1ad00ce_1659688287223_365621_4218) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_control_On_Start
 * Start Hook to be overwritten to read On value on control port
 * @generated_from _2022x_2_16600ad_1710517570715_697449_5230
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
*/
void Cse_ReadHook_Flashlight_tempoManager_control_On_Start(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710517570715_697449_5230__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710517570715_697449_5230__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_control_On_Return
 * Return Hook to be overwritten to read On value on control port
 * @generated_from _2022x_2_16600ad_1710517570715_697449_5230
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
*/
void Cse_ReadHook_Flashlight_tempoManager_control_On_Return(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710517570715_697449_5230__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710517570715_697449_5230__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_control_Off_Start
 * Start Hook to be overwritten to read Off value on control port
 * @generated_from _2022x_2_16600ad_1710517570715_697449_5230
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
*/
void Cse_ReadHook_Flashlight_tempoManager_control_Off_Start(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710517570715_697449_5230__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710517570715_697449_5230__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_control_Off_Return
 * Return Hook to be overwritten to read Off value on control port
 * @generated_from _2022x_2_16600ad_1710517570715_697449_5230
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
*/
void Cse_ReadHook_Flashlight_tempoManager_control_Off_Return(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710517570715_697449_5230__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710517570715_697449_5230__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_onCount_ipLight_light_Start
 * Start Hook to be overwritten to read light value on ipLight port
 * @generated_from _2022x_1_1ad00ce_1679314077363_282445_5642
 * @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781
*/
void Cse_ReadHook_Flashlight_onCount_ipLight_light_Start(Boolean* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1679314077363_282445_5642__2022x_1_1ad00ce_1679479084488_911966_6781) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1679314077363_282445_5642__2022x_1_1ad00ce_1679479084488_911966_6781) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_onCount_ipLight_light_Return
 * Return Hook to be overwritten to read light value on ipLight port
 * @generated_from _2022x_1_1ad00ce_1679314077363_282445_5642
 * @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781
*/
void Cse_ReadHook_Flashlight_onCount_ipLight_light_Return(Boolean* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1679314077363_282445_5642__2022x_1_1ad00ce_1679479084488_911966_6781) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1679314077363_282445_5642__2022x_1_1ad00ce_1679479084488_911966_6781) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Start
 * Start Hook to be overwritten to read switchOff value on ipControl2 port
 * @generated_from _2022x_2_16600ad_1710516938469_985483_4880
 * @generated_from _2022x_2_16600ad_1710521616807_180606_4578
*/
void Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Start(Boolean* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710516938469_985483_4880__2022x_2_16600ad_1710521616807_180606_4578) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710516938469_985483_4880__2022x_2_16600ad_1710521616807_180606_4578) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Return
 * Return Hook to be overwritten to read switchOff value on ipControl2 port
 * @generated_from _2022x_2_16600ad_1710516938469_985483_4880
 * @generated_from _2022x_2_16600ad_1710521616807_180606_4578
*/
void Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Return(Boolean* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710516938469_985483_4880__2022x_2_16600ad_1710521616807_180606_4578) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710516938469_985483_4880__2022x_2_16600ad_1710521616807_180606_4578) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_button_button_button_Start
 * Start Hook to be overwritten to read button value on button port
 * @generated_from _2022x_1_1ad00ce_1677833598836_377885_3507
 * @generated_from _2022x_2_16600ad_1710514982431_30757_4430
*/
void Cse_ReadHook_Flashlight_button_button_button_Start(Boolean* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1677833598836_377885_3507__2022x_2_16600ad_1710514982431_30757_4430) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1677833598836_377885_3507__2022x_2_16600ad_1710514982431_30757_4430) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_button_button_button_Return
 * Return Hook to be overwritten to read button value on button port
 * @generated_from _2022x_1_1ad00ce_1677833598836_377885_3507
 * @generated_from _2022x_2_16600ad_1710514982431_30757_4430
*/
void Cse_ReadHook_Flashlight_button_button_button_Return(Boolean* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1677833598836_377885_3507__2022x_2_16600ad_1710514982431_30757_4430) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1677833598836_377885_3507__2022x_2_16600ad_1710514982431_30757_4430) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Start
 * Start Hook to be overwritten to read button value on ipTempo port
 * @generated_from _2022x_2_16600ad_1710516249654_577579_4733
 * @generated_from _2022x_2_16600ad_1710516859703_529569_4765
*/
void Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Start(Integer* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710516249654_577579_4733__2022x_2_16600ad_1710516859703_529569_4765) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710516249654_577579_4733__2022x_2_16600ad_1710516859703_529569_4765) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Return
 * Return Hook to be overwritten to read button value on ipTempo port
 * @generated_from _2022x_2_16600ad_1710516249654_577579_4733
 * @generated_from _2022x_2_16600ad_1710516859703_529569_4765
*/
void Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Return(Integer* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710516249654_577579_4733__2022x_2_16600ad_1710516859703_529569_4765) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710516249654_577579_4733__2022x_2_16600ad_1710516859703_529569_4765) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_light_opLight_light_Start
 * Start hook to be overwritten to send light value on opLight port
 * @generated_from _2022x_1_1ad00ce_1677833604509_32091_3522
 * @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781
 */
void Cse_WriteHook_Flashlight_light_opLight_light_Start(Boolean* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1677833604509_32091_3522__2022x_1_1ad00ce_1679479084488_911966_6781) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1677833604509_32091_3522__2022x_1_1ad00ce_1679479084488_911966_6781) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_light_opLight_light_Return
 * Return hook to be overwritten to send light value on opLight port
 * @generated_from _2022x_1_1ad00ce_1677833604509_32091_3522
 * @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781
 */
void Cse_WriteHook_Flashlight_light_opLight_light_Return(Boolean* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1677833604509_32091_3522__2022x_1_1ad00ce_1679479084488_911966_6781) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1677833604509_32091_3522__2022x_1_1ad00ce_1679479084488_911966_6781) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_onCount_opCounts_data_Start
 * Start hook to be overwritten to send data value on opCounts port
 * @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025
 * @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025
 */
void Cse_WriteHook_Flashlight_onCount_opCounts_data_Start(Integer* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1679392992085_960294_6025__2022x_1_1ad00ce_1679392992085_960294_6025) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1679392992085_960294_6025__2022x_1_1ad00ce_1679392992085_960294_6025) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_onCount_opCounts_data_Return
 * Return hook to be overwritten to send data value on opCounts port
 * @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025
 * @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025
 */
void Cse_WriteHook_Flashlight_onCount_opCounts_data_Return(Integer* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1679392992085_960294_6025__2022x_1_1ad00ce_1679392992085_960294_6025) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1679392992085_960294_6025__2022x_1_1ad00ce_1679392992085_960294_6025) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Start
 * Start hook to be overwritten to send switchOff value on opControl port
 * @generated_from _2022x_2_16600ad_1710516884293_38745_4831
 * @generated_from _2022x_2_16600ad_1710521616807_180606_4578
 */
void Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Start(Boolean* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710516884293_38745_4831__2022x_2_16600ad_1710521616807_180606_4578) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710516884293_38745_4831__2022x_2_16600ad_1710521616807_180606_4578) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Return
 * Return hook to be overwritten to send switchOff value on opControl port
 * @generated_from _2022x_2_16600ad_1710516884293_38745_4831
 * @generated_from _2022x_2_16600ad_1710521616807_180606_4578
 */
void Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Return(Boolean* pData){
	/* BEG_USER_CODE(_2022x_2_16600ad_1710516884293_38745_4831__2022x_2_16600ad_1710521616807_180606_4578) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_2_16600ad_1710516884293_38745_4831__2022x_2_16600ad_1710521616807_180606_4578) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_timer_opLight_Tick_Start
 * Start hook to be overwritten to Trigger Tick on opLight port
 * @generated_from _2022x_1ad00ce_1659683566715_850672_3426
 * @generated_from _2022x_1ad00ce_1659688287223_365621_4218
 */
void Cse_TriggerHook_Flashlight_timer_opLight_Tick_Start(SignalEvent_Tick_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683566715_850672_3426__2022x_1ad00ce_1659688287223_365621_4218) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683566715_850672_3426__2022x_1ad00ce_1659688287223_365621_4218) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_timer_opLight_Tick_Return
 * Return hook to be overwritten to Trigger Tick on opLight port
 * @generated_from _2022x_1ad00ce_1659683566715_850672_3426
 * @generated_from _2022x_1ad00ce_1659688287223_365621_4218
 */
void Cse_TriggerHook_Flashlight_timer_opLight_Tick_Return(SignalEvent_Tick_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683566715_850672_3426__2022x_1ad00ce_1659688287223_365621_4218) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683566715_850672_3426__2022x_1ad00ce_1659688287223_365621_4218) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_button_control_On_Start
 * Start hook to be overwritten to Trigger On on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
 */
void Cse_TriggerHook_Flashlight_button_control_On_Start(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_button_control_On_Return
 * Return hook to be overwritten to Trigger On on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
 */
void Cse_TriggerHook_Flashlight_button_control_On_Return(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_button_control_Off_Start
 * Start hook to be overwritten to Trigger Off on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
 */
void Cse_TriggerHook_Flashlight_button_control_Off_Start(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_button_control_Off_Return
 * Return hook to be overwritten to Trigger Off on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
 */
void Cse_TriggerHook_Flashlight_button_control_Off_Return(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
}


#ifdef __cplusplus
}
#endif /* __cplusplus */

/* BEG_USER_CODE(FOOTER) do not remove */
/* Add your includes here */
/* END_USER_CODE(FOOTER) do not remove */

#endif /* USER_HOOKS */
/* end of file */
