/* @date 2025-04-10T02:14:49.671090665Z */

/**********************************************************************
 * @file Light_Light_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659688246184_266641_4147
 **********************************************************************/

#ifdef STATEMACHINE

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define opLight_light   instance->opLight_light
#define opLight         opLight_light
#define poutData        instance->classifier->poutData

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Function Off_Do
 * Implements "Do" of State: Off
 * Do calls OpaqueBehavior: null
 *
 * @generated_from _2022x_1ad00ce_1659688246252_961360_4176
 * @generated_from _2022x_1_1ad00ce_1677836151283_489740_4246
 **********************************************************************/
static void Off_Do(Light_struct *instance) {
    /* BEG_USER_CODE(Do_2022x_1ad00ce_1659688246252_961360_4176) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    poutData=false;

    /* END_USER_CODE(Do_2022x_1ad00ce_1659688246252_961360_4176) do not remove */
}

/**********************************************************************
 * Function On_Do
 * Implements "Do" of State: On
 * Do calls OpaqueBehavior: null
 *
 * @generated_from _2022x_1ad00ce_1659688271019_988850_4197
 * @generated_from _2022x_1_1ad00ce_1677835558156_715319_4116
 **********************************************************************/
static void On_Do(Light_struct *instance) {
    /* BEG_USER_CODE(Do_2022x_1ad00ce_1659688271019_988850_4197) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    poutData=true;

    /* END_USER_CODE(Do_2022x_1ad00ce_1659688271019_988850_4197) do not remove */
}

static void StateMachine_init(Light_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(init_state_machine) do not remove */
}

static void StateMachine_end(Light_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(end_state_machine) do not remove */
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

#endif /* STATEMACHINE */
/* end of file */
