/* @date 2025-04-10T02:14:49.753836730Z */

/**********************************************************************
 * @file Tempo_TempoManager_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_2_16600ad_1710518012706_366349_5363
 **********************************************************************/

#ifdef STATEMACHINE

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define ipTempo_button      instance->ipTempo_button
#define ipTempo             ipTempo_button
#define opControl_switchOff instance->opControl_switchOff
#define opControl           opControl_switchOff
#define tempo               instance->classifier->tempo

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Function Init_Entry
 * Implements "Entry" of State: Init
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from _2022x_2_16600ad_1710518012870_434506_5392
 * @generated_from _2022x_2_16600ad_1710845254675_524621_5231
 **********************************************************************/
static void Init_Entry(TempoManager_struct *instance) {
    /* BEG_USER_CODE(Entry_2022x_2_16600ad_1710518012870_434506_5392) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    extern bool myTimerRunning;
    extern timerId myTimerId;

    opControl = false;
    if(myTimerRunning == true){
        myTimerRunning = false;
        tal_CancelTimer(myTimerId);
    }

    /* END_USER_CODE(Entry_2022x_2_16600ad_1710518012870_434506_5392) do not remove */
}

/**********************************************************************
 * Function Tempo_Entry
 * Implements "Entry" of State: Tempo
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from _2022x_2_16600ad_1710518048256_352437_5436
 * @generated_from _2022x_2_16600ad_1710519120889_739755_5964
 **********************************************************************/
static void Tempo_Entry(TempoManager_struct *instance) {
    /* BEG_USER_CODE(Entry_2022x_2_16600ad_1710518048256_352437_5436) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    extern void *myFct(void* arg);

    opControl = false;
    if(ipTempo > 0){
        tal_CreateThread(myFct, instance);
    }

    /* END_USER_CODE(Entry_2022x_2_16600ad_1710518048256_352437_5436) do not remove */
}

static void StateMachine_init(TempoManager_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(init_state_machine) do not remove */
}

static void StateMachine_end(TempoManager_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(end_state_machine) do not remove */
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

#endif /* STATEMACHINE */
/* end of file */
