/* @date 2025-04-10T02:14:49.751995521Z */

/**********************************************************************
 * @file Tempo_TempoManager.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_2_16600ad_1710518012706_366349_5363
 **********************************************************************/

/* Application code for statemachine "TempoManager" */

#include "Tempo_TempoManager.h"
#include "Tempo.h"

#define STATEMACHINE        TempoManager_struct

/**********************************************************************
 * Function TempoManager_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from _2022x_2_16600ad_1710518012706_366349_5363
 **********************************************************************/
static void TempoManager_struct_dtor(struct TempoManager_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function TempoManager_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from _2022x_2_16600ad_1710518012706_366349_5363
 **********************************************************************/
void TempoManager_struct_ctor(struct TempoManager_struct * const self, struct Tempo* classifier) {
    /* Init pointer to destructor */
    self->dtor = TempoManager_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * separate code of user-modifiable functions to prevent accidental
 * changes to code above.
 **********************************************************************/
#include "Tempo_TempoManager_usr.c"

/**********************************************************************
 * Function _basic_TempoManager_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_2_16600ad_1710518012706_366349_5363
 **********************************************************************/
void _basic_TempoManager_init(TempoManager_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T)0;
    instance->CURRENT_STATE_0 = TEMPOMANAGER_STATE_T_VOID;

    StateMachine_init(instance);
}

/**********************************************************************
 * Function _basic_TempoManager
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_2_16600ad_1710518012706_366349_5363
 **********************************************************************/
void _basic_TempoManager(TempoManager_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> Init */
        /* @generated_from _2022x_2_16600ad_1710518012871_326899_5393 */
        Init_Entry(instance); /* Entry of TEMPOMANAGER_STATE_T_Init */
        instance->CURRENT_STATE_0 = TEMPOMANAGER_STATE_T_Init;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State Init */
        /* @generated_from _2022x_2_16600ad_1710518012870_434506_5392 */
        case TEMPOMANAGER_STATE_T_Init: {
            if( instance->EVENT == TEMPOMANAGER_EVENT_T_On ) {
                /* Transition Init -> Tempo */
                /* @generated_from _2022x_2_16600ad_1710518060310_774822_5473 */
                Tempo_Entry(instance); /* Entry of TEMPOMANAGER_STATE_T_Tempo */
                instance->CURRENT_STATE_0 = TEMPOMANAGER_STATE_T_Tempo;
                instance->EVENT = TEMPOMANAGER_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of TEMPOMANAGER_STATE_T_Init */
        }
        /* State Tempo */
        /* @generated_from _2022x_2_16600ad_1710518048256_352437_5436 */
        case TEMPOMANAGER_STATE_T_Tempo: {
            if( instance->EVENT == TEMPOMANAGER_EVENT_T_Off ) {
                /* Transition Tempo -> Init */
                /* @generated_from _2022x_2_16600ad_1710518094182_703954_5504 */
                Init_Entry(instance); /* Entry of TEMPOMANAGER_STATE_T_Init */
                instance->CURRENT_STATE_0 = TEMPOMANAGER_STATE_T_Init;
                instance->EVENT = TEMPOMANAGER_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of TEMPOMANAGER_STATE_T_Tempo */
        }
        default: break;
    } /* end of switch */
}

/**********************************************************************
 * Function _basic_TempoManager_end
 * Implements statemachine exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_2_16600ad_1710518012706_366349_5363
 **********************************************************************/
void _basic_TempoManager_end(TempoManager_struct *instance) {
    StateMachine_end(instance);
}

/* end of file */
