/* @date 2025-04-10T02:14:49.763828402Z */

/**********************************************************************
 * @file Tempo.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from _2022x_2_16600ad_1710516215858_329482_4706
 **********************************************************************/

#ifndef TEMPO_H
#define TEMPO_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include <Tal.h>
#include "Tempo_itf.h"
#include "Tempo_internal_types.h"
#include "Tempo_TempoManager.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from _2022x_2_16600ad_1710516215858_329482_4706 */	 
typedef struct Tempo{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Tempo*);

	/**
	 * @brief Public attribute for composition relation to Real:tempo
	 * @generated_from _2022x_2_16600ad_1710518732173_969238_5793
	 */
	Real tempo;
		
	/**
	 * Data for Behavior TempoManager
	 * @generated_from _2022x_2_16600ad_1710518012706_366349_5363
	 */
	TempoManager_struct TempoManager;

	/**********************************************************************
	 * Communication Interface section
	 **********************************************************************/
	/**
	 * Communication interface
	 * @generated_from _2022x_2_16600ad_1710516215858_329482_4706
	 */
	Cse_Tempo_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Tempo;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_2_16600ad_1710516215858_329482_4706
 */
void Tempo_ctor(Tempo* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef TEMPO_H

/* end of file */