/* @date 2025-04-10T02:14:49.755715326Z */

/**********************************************************************
 * @file Tempo_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from _2022x_2_16600ad_1710516215858_329482_4706
 **********************************************************************/

#ifndef CSE_TEMPO_ITF_H
#define CSE_TEMPO_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Tempo_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* @generated_from _2022x_2_16600ad_1710516884293_38745_4831 */
	/* @generated_from _2022x_2_16600ad_1710521616807_180606_4578 */	
	void (*Write_opControl_switchOff)(Boolean* msg);
	/* Trigger functions */
	/* Read functions */
	/* @generated_from _2022x_2_16600ad_1710516249654_577579_4733 */
	/* @generated_from _2022x_2_16600ad_1710516859703_529569_4765 */  
	void (*Read_ipTempo_button)(Integer* msg);
	/* @generated_from _2022x_2_16600ad_1710517570715_697449_5230 */
	/* @generated_from _2022x_1ad00ce_1659688230703_340985_4140 */  
	void (*Read_control_On)(SignalEvent_On_type* msg);
	/* @generated_from _2022x_2_16600ad_1710517570715_697449_5230 */
	/* @generated_from _2022x_1ad00ce_1659688235695_364403_4143 */  
	void (*Read_control_Off)(SignalEvent_Off_type* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Tempo *parent;
}Cse_Tempo_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from _2022x_2_16600ad_1710518012706_366349_5363 */ 
void Tempo_TempoManager_init(Cse_Tempo_Struct* self);
void Tempo_TempoManager(Cse_Tempo_Struct* instance);
void Tempo_TempoManager_end(Cse_Tempo_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from _2022x_2_16600ad_1710518012706_366349_5363 */ 
#define TempoManager(...) Tempo_TempoManager(__VA_ARGS__)
/* @generated_from _2022x_2_16600ad_1710518012706_366349_5363 */ 
#define TempoManager_init(...) Tempo_TempoManager_init(__VA_ARGS__)
/* @generated_from _2022x_2_16600ad_1710518012706_366349_5363 */ 
#define TempoManager_end(...) Tempo_TempoManager_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */
/* @generated_from _2022x_2_16600ad_1710516884293_38745_4831 */
/* @generated_from _2022x_2_16600ad_1710521616807_180606_4578 */	
void Cse_Write_opControl_switchOff(Cse_Tempo_Struct* instance, Boolean* msg);

/* Trigger functions declaration */

/* Read functions declaration */
/* @generated_from _2022x_2_16600ad_1710516249654_577579_4733 */
/* @generated_from _2022x_2_16600ad_1710516859703_529569_4765 */
void Cse_Read_ipTempo_button(Cse_Tempo_Struct* instance, Integer* msg);
/* @generated_from _2022x_2_16600ad_1710517570715_697449_5230 */
/* @generated_from _2022x_1ad00ce_1659688230703_340985_4140 */
void Cse_Read_control_On(Cse_Tempo_Struct* instance, SignalEvent_On_type* msg);
/* @generated_from _2022x_2_16600ad_1710517570715_697449_5230 */
/* @generated_from _2022x_1ad00ce_1659688235695_364403_4143 */
void Cse_Read_control_Off(Cse_Tempo_Struct* instance, SignalEvent_Off_type* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Read_ipTempo_button(inst, data) inst->Read_ipTempo_button(data)
#define Cse_Write_opControl_switchOff(inst, data) inst->Write_opControl_switchOff(data)
#define Cse_Read_control_On(inst, data) inst->Read_control_On(data)
#define Cse_Read_control_Off(inst, data) inst->Read_control_Off(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_TEMPO_ITF_H */

/* end of file */
