/* @date 2025-04-10T02:14:49.633126534Z */

/**********************************************************************
 * @file Timer_type.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from _2022x_1ad00ce_1659678985350_593051_3321
 **********************************************************************/

#ifndef TIMER_TYPE_H
#define TIMER_TYPE_H

#include <stddef.h>
/* stdbool.h define standard bool (true/false) starting from C99 standard */ 
#include <stdbool.h>

/**********************************************************************
 * Data Type trigger_type definition
 **********************************************************************/
#ifndef trigger_type_DEFINITION
#define trigger_type_DEFINITION
typedef bool trigger_type;
#endif /* trigger_type */

/**********************************************************************
 * Data Type SignalEvent_Tick_type definition
 **********************************************************************/
#ifndef SignalEvent_Tick_type_DEFINITION
#define SignalEvent_Tick_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_Tick_type;
#endif /* SignalEvent_Tick_type */

/**********************************************************************
 * Data Type SignalEvent_On_type definition
 **********************************************************************/
#ifndef SignalEvent_On_type_DEFINITION
#define SignalEvent_On_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_On_type;
#endif /* SignalEvent_On_type */

/**********************************************************************
 * Data Type SignalEvent_Off_type definition
 **********************************************************************/
#ifndef SignalEvent_Off_type_DEFINITION
#define SignalEvent_Off_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_Off_type;
#endif /* SignalEvent_Off_type */

/**********************************************************************
 * Data Type Boolean definition
 **********************************************************************/
#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool Boolean;
#endif /* Boolean */

#endif /* TIMER_TYPE_H */

/* end of file */
