/* @date 2025-04-10T02:14:49.566537943Z */

/**********************************************************************
 * @file Timer_Timer.h
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659687960195_296841_3882
 **********************************************************************/

#ifndef TIMER_TIMER_H
#define TIMER_TIMER_H

#include "Timer_itf.h" /* Datatypes defined at interfaces */
#include "Timer_internal_types.h" /* Datatypes for internal data */

#include "Timer_Timer_Send_Tick.h"

/* BEG_USER_CODE(types) do not remove */

#ifndef WALLCLOCK_T
#define WALLCLOCK_T WALLCLOCK_T
typedef double  WALLCLOCK_T;  /* time type (can be any scalar) */
#endif
#ifndef USERDATA_T
#define USERDATA_T  USERDATA_T
typedef void *  USERDATA_T;   /* replace this pointer by an anonymous struct if needed. */
#endif

/* END_USER_CODE(types) do not remove */

typedef enum {
    TIMER_STATE_T_INITIAL_0,
    TIMER_STATE_T_off,
    TIMER_STATE_T_Ticking,
    TIMER_STATE_T_VOID
} TIMER_STATE_T;

typedef enum {
    TIMER_EVENT_T_Off,
    TIMER_EVENT_T_On,
    TIMER_EVENT_T_NO_EVENT
} TIMER_EVENT_T;

typedef struct Timer_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Timer_struct*);

    /* user data */
    USERDATA_T              USERDATA;

    /* data */
    Boolean                 ipControl2_switchOff;



    /* sub behaviors */
    Timer_Send_Tick_struct  Ticking_Entry_Timer_Send_Tick;

    /* pointer to classifier */
    struct Timer* classifier;

    /* internal */
    TIMER_STATE_T           CURRENT_STATE_0;
    WALLCLOCK_T             WALL_CLOCK;
    WALLCLOCK_T             ENTER_CLOCK_0;
    TIMER_EVENT_T           EVENT;
    Boolean                 FIRST;
    Boolean                 DONE_ACTIVITY;
} Timer_struct;

void Timer_struct_ctor(struct Timer_struct * const self, struct Timer* classifier);
void _basic_Timer_init(Timer_struct *instance);
void _basic_Timer(Timer_struct *instance);
void _basic_Timer_end(Timer_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*TIMER_TIMER_H*/
/* end of file */
