/* @date 2025-04-10T02:14:49.599008862Z */

/**********************************************************************
 * @file Timer_Timer_Send_Tick.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659689071378_428346_4514
 **********************************************************************/

/* Application code for activity "Send Tick" */

#include "Timer_Timer_Send_Tick.h"

#include "Timer.h"
#include <string.h>
/**********************************************************************
 * handy helpers
 **********************************************************************/
#define ipControl2_switchOff        instance->ipControl2_switchOff
#define ipControl2                  ipControl2_switchOff
#define switchOff                   instance->classifier->switchOff

/**********************************************************************
 * default event handlers
 **********************************************************************/
// cppcheck-suppress constParameterCallback
static TIMER_SEND_TICK_EVENT_T default_peekEvent(Timer_Send_Tick_struct *instance) {
    return instance->EVENT;
}
static TIMER_SEND_TICK_EVENT_T default_nextEvent(Timer_Send_Tick_struct *instance) {
    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    return TIMER_SEND_TICK_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent(Timer_Send_Tick_struct *instance, TIMER_SEND_TICK_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == TIMER_SEND_TICK_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************
 * helpers
 **********************************************************************/
static inline Boolean isRunning(const Timer_Send_Tick_struct* const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************
 * Function Timer_Send_Tick_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from _2022x_1ad00ce_1659689071378_428346_4514
 **********************************************************************/
static void Timer_Send_Tick_struct_dtor(struct Timer_Send_Tick_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function Timer_Send_Tick_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from _2022x_1ad00ce_1659689071378_428346_4514
 **********************************************************************/
void Timer_Send_Tick_struct_ctor(struct Timer_Send_Tick_struct * const self, struct Timer* classifier) {
    /* Init pointer to destructor */
    self->dtor = Timer_Send_Tick_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * Function _basic_Timer_Send_Tick_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659689071378_428346_4514
 **********************************************************************/
void _basic_Timer_Send_Tick_init(Timer_Send_Tick_struct *instance) {
    if(instance->peekEVENT == NULL) {instance->peekEVENT = default_peekEvent;}
    if(instance->nextEVENT == NULL) {instance->nextEVENT = default_nextEvent;}
    if(instance->sendEVENT == NULL) {instance->sendEVENT = default_sendEvent;}
    instance->EVENT = TIMER_SEND_TICK_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));

    instance->WALL_CLOCK        = (WALLCLOCK_T)0;


    // TODO how to assign events functions
    // instance->node_2_Model_Functions_Send_Tick.peekEVENT = instance->peekEVENT;
    // instance->node_2_Model_Functions_Send_Tick.nextEVENT = instance->nextEVENT;
    // instance->node_2_Model_Functions_Send_Tick.sendEVENT = instance->sendEVENT;
    instance->node_2_Model_Functions_Send_Tick.classifier = instance->classifier;
    _basic_Model_Functions_Send_Tick_init(&(instance->node_2_Model_Functions_Send_Tick));
}

/**********************************************************************
 * Function _basic_Timer_Send_Tick
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659689071378_428346_4514
 **********************************************************************/
Boolean _basic_Timer_Send_Tick(Timer_Send_Tick_struct *instance) {
    /* initialization */
    if(isRunning(instance) == FALSE) {
        instance->flow[0] = 1u; /* SET_FLOW->CallBehaviorAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node CallBehaviorAction */
    /* @generated_from _2022x_1ad00ce_1659689071373_957232_4509 */
    if(1u == (instance->flow[0] & 1u)) { /* TST_FLOW<-InitialNode */
        Boolean success;
        success = _basic_Model_Functions_Send_Tick(&(instance->node_2_Model_Functions_Send_Tick));
        if(success != FALSE) {
            instance->flow[0] ^= 1u; /* CLR_FLOW<-InitialNode */
            instance->flow[0] |= 2u; /* SET_FLOW->ActivityFinalNode */
        }
    }
    /* node ActivityFinalNode */
    /* @generated_from _2022x_1ad00ce_1659689071370_920292_4508 */
    if(2u == (instance->flow[0] & 2u)) { /* TST_FLOW<-CallBehaviorAction */
        (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));
    }

    return (FALSE == isRunning(instance)) ? TRUE : FALSE;
}

/**********************************************************************
 * Function _basic_Timer_Send_Tick_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659689071378_428346_4514
 **********************************************************************/
void _basic_Timer_Send_Tick_end(Timer_Send_Tick_struct *instance) {
    _basic_Model_Functions_Send_Tick_end(&(instance->node_2_Model_Functions_Send_Tick));
}

/* end of file */
