/* @date 2025-03-04T06:13:23.910414796Z */

/**********************************************************************
 * @file Button_Button.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659686618091_973487_3644
 **********************************************************************/

/* Application code for statemachine "Button" */

#include "Button_Button.h"
#include "Button.h"

#define STATEMACHINE        Button_struct

/**********************************************************************
 * Function Button_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from _2022x_1ad00ce_1659686618091_973487_3644
 **********************************************************************/
static void Button_struct_dtor(struct Button_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function Button_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from _2022x_1ad00ce_1659686618091_973487_3644
 **********************************************************************/
void Button_struct_ctor(struct Button_struct * const self, struct Button* classifier) {
    /* Init pointer to destructor */
    self->dtor = Button_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * separate code of user-modifiable functions to prevent accidental
 * changes to code above.
 **********************************************************************/
#include "Button_Button_usr.c"

/**********************************************************************
 * Function _basic_Button_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659686618091_973487_3644
 **********************************************************************/
void _basic_Button_init(Button_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T)0;
    instance->CURRENT_STATE_0 = BUTTON_STATE_T_VOID;

    instance->on_Effect_Button_Send_Off.classifier = instance->classifier;
    _basic_Button_Send_Off_init(&(instance->on_Effect_Button_Send_Off));

    instance->on_Entry_Button_Send_On.classifier = instance->classifier;
    _basic_Button_Send_On_init(&(instance->on_Entry_Button_Send_On));

    StateMachine_init(instance);
}

/**********************************************************************
 * Function _basic_Button
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659686618091_973487_3644
 **********************************************************************/
void _basic_Button(Button_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> off */
        /* @generated_from _2022x_1ad00ce_1659686618195_31981_3674 */
        instance->CURRENT_STATE_0 = BUTTON_STATE_T_off;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State off */
        /* @generated_from _2022x_1ad00ce_1659686618193_304174_3673 */
        case BUTTON_STATE_T_off: {
            if( pinData!=false ) {
                /* Transition off -> on */
                /* @generated_from _2022x_1ad00ce_1659687553562_420977_3696 */
                on_Entry(instance); /* Entry Send On */
                instance->CURRENT_STATE_0 = BUTTON_STATE_T_on;
                instance->EVENT = BUTTON_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of BUTTON_STATE_T_off */
        }
        /* State on */
        /* @generated_from _2022x_1ad00ce_1659687553559_425198_3695 */
        case BUTTON_STATE_T_on: {
            if( pinData==false ) {
                /* Transition on -> off */
                /* @generated_from _2022x_1ad00ce_1659687813473_879953_3794 */
                on_Effect(instance); /* Effect Send Off */
                instance->CURRENT_STATE_0 = BUTTON_STATE_T_off;
                instance->EVENT = BUTTON_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of BUTTON_STATE_T_on */
        }
        default: break;
    } /* end of switch */
}

/**********************************************************************
 * Function _basic_Button_end
 * Implements statemachine exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659686618091_973487_3644
 **********************************************************************/
void _basic_Button_end(Button_struct *instance) {
    StateMachine_end(instance);
}

/* end of file */
