/* @date 2025-03-04T06:13:23.918095025Z */

/**********************************************************************
 * @file Button_Button_Send_On.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659691200449_687228_4664
 **********************************************************************/

/* Application code for activity "Send On" */

#include "Button_Button_Send_On.h"

#include "Button.h"
#include <string.h>
/**********************************************************************
 * handy helpers
 **********************************************************************/
#define button_button           instance->button_button
#define button                  button_button
#define pinData                 instance->classifier->pinData

/**********************************************************************
 * default event handlers
 **********************************************************************/
// cppcheck-suppress constParameterCallback
static BUTTON_SEND_ON_EVENT_T default_peekEvent(Button_Send_On_struct *instance) {
    return instance->EVENT;
}
static BUTTON_SEND_ON_EVENT_T default_nextEvent(Button_Send_On_struct *instance) {
    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    return BUTTON_SEND_ON_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent(Button_Send_On_struct *instance, BUTTON_SEND_ON_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == BUTTON_SEND_ON_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************
 * helpers
 **********************************************************************/
static inline Boolean isRunning(const Button_Send_On_struct* const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************
 * Function Button_Send_On_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from _2022x_1ad00ce_1659691200449_687228_4664
 **********************************************************************/
static void Button_Send_On_struct_dtor(struct Button_Send_On_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function Button_Send_On_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from _2022x_1ad00ce_1659691200449_687228_4664
 **********************************************************************/
void Button_Send_On_struct_ctor(struct Button_Send_On_struct * const self, struct Button* classifier) {
    /* Init pointer to destructor */
    self->dtor = Button_Send_On_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * Function _basic_Button_Send_On_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659691200449_687228_4664
 **********************************************************************/
void _basic_Button_Send_On_init(Button_Send_On_struct *instance) {
    if(instance->peekEVENT == NULL) {instance->peekEVENT = default_peekEvent;}
    if(instance->nextEVENT == NULL) {instance->nextEVENT = default_nextEvent;}
    if(instance->sendEVENT == NULL) {instance->sendEVENT = default_sendEvent;}
    instance->EVENT = BUTTON_SEND_ON_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));

    instance->WALL_CLOCK        = (WALLCLOCK_T)0;


    // TODO how to assign events functions
    // instance->node_2_Model_Functions_Send_On.peekEVENT = instance->peekEVENT;
    // instance->node_2_Model_Functions_Send_On.nextEVENT = instance->nextEVENT;
    // instance->node_2_Model_Functions_Send_On.sendEVENT = instance->sendEVENT;
    instance->node_2_Model_Functions_Send_On.classifier = instance->classifier;
    _basic_Model_Functions_Send_On_init(&(instance->node_2_Model_Functions_Send_On));
}

/**********************************************************************
 * Function _basic_Button_Send_On
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659691200449_687228_4664
 **********************************************************************/
Boolean _basic_Button_Send_On(Button_Send_On_struct *instance) {
    /* initialization */
    if(isRunning(instance) == FALSE) {
        instance->flow[0] = 1u; /* SET_FLOW->CallBehaviorAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node CallBehaviorAction */
    /* @generated_from _2022x_1ad00ce_1659691200447_542493_4659 */
    if(1u == (instance->flow[0] & 1u)) { /* TST_FLOW<-InitialNode */
        Boolean success;
        success = _basic_Model_Functions_Send_On(&(instance->node_2_Model_Functions_Send_On));
        if(success != FALSE) {
            instance->flow[0] ^= 1u; /* CLR_FLOW<-InitialNode */
            instance->flow[0] |= 2u; /* SET_FLOW->ActivityFinalNode */
        }
    }
    /* node ActivityFinalNode */
    /* @generated_from _2022x_1ad00ce_1659691200447_459289_4658 */
    if(2u == (instance->flow[0] & 2u)) { /* TST_FLOW<-CallBehaviorAction */
        (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));
    }

    return (FALSE == isRunning(instance)) ? TRUE : FALSE;
}

/**********************************************************************
 * Function _basic_Button_Send_On_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659691200449_687228_4664
 **********************************************************************/
void _basic_Button_Send_On_end(Button_Send_On_struct *instance) {
    _basic_Model_Functions_Send_On_end(&(instance->node_2_Model_Functions_Send_On));
}

/* end of file */
