/* @date 2025-03-04T06:13:23.936335115Z */

/**********************************************************************
 * @file Button.c
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
 **********************************************************************/

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include <stddef.h> // NULL
#include "Button.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */


/* Function pointer to destructor function generated automatically */
static void Button_dtor(struct Button* self){
	/* Call hierarchical destructors */
	self->Button.dtor(&self->Button);

	/* Clean pointer to destructor */
	self->dtor = NULL;
}

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
 */
void Button_ctor(Button* self){
	/* Init pointer to destructor */
	self->dtor = Button_dtor;

	/* Default values */

	/* Configure Communication Interface */
	self->cse_itf.parent = self;

	/* Call hierarchical constructors */
	Button_struct_ctor(&self->Button, self);
}
/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */