/* @date 2025-03-04T06:13:23.913854317Z */

/**********************************************************************
 * @file Button_Button_Send_Off.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659691265299_712196_4743
 **********************************************************************/

#ifndef BUTTON_BUTTON_SEND_OFF_H
#define BUTTON_BUTTON_SEND_OFF_H

#include "Button_type.h" /* Datatypes for internal data */
#include "Button_internal_types.h" /* Datatypes for internal data */

#include "Model_Functions_Send_Off.h"

#include <stdint.h>
typedef enum {
    BUTTON_SEND_OFF_EVENT_T_NO_EVENT
} BUTTON_SEND_OFF_EVENT_T;

#ifndef ESP_TYPES
#define ESP_TYPES
/* BEG_USER_CODE(local-types) do not remove */

typedef double  WALLCLOCK_T;  /* time type (can be any scalar) */
typedef void *  USERDATA_T;   /* replace this pointer by an anonymous struct if needed. */

/* END_USER_CODE(local-types) do not remove */
#endif

typedef struct Button_Send_Off_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Button_Send_Off_struct*);

    /* user data */
    USERDATA_T                      USERDATA;

    /* data */
    Boolean                         button_button;

    /* called behaviors */
    Model_Functions_Send_Off_struct node_2_Model_Functions_Send_Off;

    /* events */
    BUTTON_SEND_OFF_EVENT_T         EVENT;
    BUTTON_SEND_OFF_EVENT_T         (*peekEVENT)(struct Button_Send_Off_struct *instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    BUTTON_SEND_OFF_EVENT_T         (*nextEVENT)(struct Button_Send_Off_struct *instance); /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean                         (*sendEVENT)(struct Button_Send_Off_struct *instance, BUTTON_SEND_OFF_EVENT_T event); \
        /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct Button* classifier;

    /* internal */
    uint32_t                        flow[1];
    WALLCLOCK_T                     WALL_CLOCK;
} Button_Send_Off_struct;

void Button_Send_Off_struct_ctor(struct Button_Send_Off_struct * const self, struct Button* classifier);
void _basic_Button_Send_Off_init(Button_Send_Off_struct *instance);
Boolean _basic_Button_Send_Off(Button_Send_Off_struct *instance);
void _basic_Button_Send_Off_end(Button_Send_Off_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*BUTTON_BUTTON_SEND_OFF_H*/
/* end of file */
