/* @date 2025-03-04T06:13:23.944444857Z */

/**********************************************************************
 * @file Counter_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from _2022x_1_1ad00ce_1679314077359_990669_5639
 **********************************************************************/

#ifndef CSE_COUNTER_ITF_H
#define CSE_COUNTER_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Counter_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025 */
	/* @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025 */	
	void (*Write_opCounts_data)(Integer* msg);
	/* Trigger functions */
	/* Read functions */
	/* @generated_from _2022x_1_1ad00ce_1679314077363_282445_5642 */
	/* @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781 */  
	void (*Read_ipLight_light)(Boolean* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Counter *parent;
}Cse_Counter_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from _2022x_1_1ad00ce_1679395074392_356802_6200 */ 
void Counter_OB_cnt_init(Cse_Counter_Struct* self);
void Counter_OB_cnt(Cse_Counter_Struct* instance);
void Counter_OB_cnt_end(Cse_Counter_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from _2022x_1_1ad00ce_1679395074392_356802_6200 */ 
#define OB_cnt(...) Counter_OB_cnt(__VA_ARGS__)
/* @generated_from _2022x_1_1ad00ce_1679395074392_356802_6200 */ 
#define OB_cnt_init(...) Counter_OB_cnt_init(__VA_ARGS__)
/* @generated_from _2022x_1_1ad00ce_1679395074392_356802_6200 */ 
#define OB_cnt_end(...) Counter_OB_cnt_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */
/* @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025 */
/* @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025 */	
void Cse_Write_opCounts_data(Cse_Counter_Struct* instance, Integer* msg);

/* Trigger functions declaration */

/* Read functions declaration */
/* @generated_from _2022x_1_1ad00ce_1679314077363_282445_5642 */
/* @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781 */
void Cse_Read_ipLight_light(Cse_Counter_Struct* instance, Boolean* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Read_ipLight_light(inst, data) inst->Read_ipLight_light(data)
#define Cse_Write_opCounts_data(inst, data) inst->Write_opCounts_data(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_COUNTER_ITF_H */

/* end of file */
