/* @date 2025-02-27T05:05:36.383305131Z */

/**********************************************************************
 * @file Cse_Button.c
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
 **********************************************************************/

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Tal.h" // tal_allocate
#include "Cse_cfg.h"
#include "Cse_Button_hook.h"
#define CSE_C /* Macro to include only some specific parts of include files */
#include "Button.h"

#include <string.h> // memset

#include "Button_itf.h"

#ifdef CSE_DEBUG
#include <stdio.h>
#define debug_cse(...) printf(__VA_ARGS__); fflush(stdout)
#else
#define debug_cse(...)
#endif

/**
 * Unique instance of the main entity
 */
Button* pButton;

/**
 * Required additional objects to instanciate
 */

task_descriptor task_descriptors[NUMBER_OF_TASKS];


/**********************************************************************
 * Function to Trigger On on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
 **********************************************************************/
static void Cse_Trigger_Button_control_On(void){

	Cse_TriggerHook_Button_control_On_Start(&pButton->to_UNCONNECTED_control_On);
	debug_cse("DEBUG: Cse_Trigger_Button_control_On\n");
	pButton->to_UNCONNECTED_control_On.trigger = 1;
	Cse_TriggerHook_Button_control_On_Return(&pButton->to_UNCONNECTED_control_On);
}

/**********************************************************************
 * Function to Trigger Off on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
 **********************************************************************/
static void Cse_Trigger_Button_control_Off(void){

	Cse_TriggerHook_Button_control_Off_Start(&pButton->to_UNCONNECTED_control_Off);
	debug_cse("DEBUG: Cse_Trigger_Button_control_Off\n");
	pButton->to_UNCONNECTED_control_Off.trigger = 1;
	Cse_TriggerHook_Button_control_Off_Return(&pButton->to_UNCONNECTED_control_Off);
}



/**********************************************************************
 * Function to read button value on button port
 * @generated_from _2022x_1_1ad00ce_1677833598836_377885_3507
 * @generated_from _2022x_2_16600ad_1710514982431_30757_4430
 **********************************************************************/
static void Cse_Read_Button_button_button(Boolean* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Button_button_button_Start(&pButton->from_UNCONNECTED_button_button);
	debug_cse("DEBUG: RTE_Read_Button_button_button\n");
	Cse_ReadHook_Button_button_button_Return(&pButton->from_UNCONNECTED_button_button);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pButton->from_UNCONNECTED_button_button)[byteIdx];
	}
}



/**********************************************************************
 * Map the communication APIs to component instances
 * First function to call before Cse_task_descriptors_init & Cse_components_init
 **********************************************************************/
void Cse_component_instances_init(void){
	pButton = tal_allocate(sizeof(Button));

	/* Erase memory section for Behaviors proper implementation */
	memset(pButton, 0, sizeof(Button));

	Button_ctor(pButton);
	
	/* BEG: Button Communication Interface Configuration */
	/* Write functions */
	/* Trigger functions */
	pButton->cse_itf.Trigger_control_On = &Cse_Trigger_Button_control_On;
	pButton->cse_itf.Trigger_control_Off = &Cse_Trigger_Button_control_Off;
	/* Read functions */
	pButton->cse_itf.Read_button_button = &Cse_Read_Button_button_button;
	/* Server call functions */
	/* END: Button Cmmunication Interface Configuration */

}

/**********************************************************************
 * Function configuring each task.
 * Function to call just after Cse_component_instances_init
 **********************************************************************/
void Cse_task_descriptors_init(void){


}

/**********************************************************************
 * Function calling all the init functions as configured in the model.
 * To be called after Cse_task_descriptors_init & Cse_component_instances_init
 **********************************************************************/
void Cse_components_init(void) {
	Button_Button_init(&pButton->cse_itf);
}

/* end of file */
