/* @date 2025-02-27T05:05:36.384639209Z */

/**********************************************************************
 * @file Cse_Button_hook_usr.c
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678969433_444652_3277
 **********************************************************************/

/*
 * define symbol USER_HOOKS to enable this file content on compiler 
 * command or uncomment following line
 */
/* #define USER_HOOKS */
#ifdef USER_HOOKS

#include "Cse_cfg.h"

#ifdef __cplusplus
// Code is compiled as C code even if the file is a cpp file
extern "C" {
#endif /* __cplusplus */

/* BEG_USER_CODE(HEADER) do not remove */
/* Add your includes here */
/* END_USER_CODE(HEADER) do not remove */

/**
 * Function Cse_ReadHook_Button_button_button_Start
 * Start Hook to be overwritten to read button value on button port
 * @generated_from _2022x_1_1ad00ce_1677833598836_377885_3507
 * @generated_from _2022x_2_16600ad_1710514982431_30757_4430
*/
void Cse_ReadHook_Button_button_button_Start(Boolean* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1677833598836_377885_3507__2022x_2_16600ad_1710514982431_30757_4430) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1677833598836_377885_3507__2022x_2_16600ad_1710514982431_30757_4430) do not remove */
}

/**
 * Function Cse_ReadHook_Button_button_button_Return
 * Return Hook to be overwritten to read button value on button port
 * @generated_from _2022x_1_1ad00ce_1677833598836_377885_3507
 * @generated_from _2022x_2_16600ad_1710514982431_30757_4430
*/
void Cse_ReadHook_Button_button_button_Return(Boolean* pData){
	/* BEG_USER_CODE(_2022x_1_1ad00ce_1677833598836_377885_3507__2022x_2_16600ad_1710514982431_30757_4430) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1_1ad00ce_1677833598836_377885_3507__2022x_2_16600ad_1710514982431_30757_4430) do not remove */
}

/**
 * Function Cse_TriggerHook_Button_control_On_Start
 * Start hook to be overwritten to Trigger On on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
 */
void Cse_TriggerHook_Button_control_On_Start(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
}

/**
 * Function Cse_TriggerHook_Button_control_On_Return
 * Return hook to be overwritten to Trigger On on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
 */
void Cse_TriggerHook_Button_control_On_Return(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688230703_340985_4140) do not remove */
}

/**
 * Function Cse_TriggerHook_Button_control_Off_Start
 * Start hook to be overwritten to Trigger Off on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
 */
void Cse_TriggerHook_Button_control_Off_Start(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
}

/**
 * Function Cse_TriggerHook_Button_control_Off_Return
 * Return hook to be overwritten to Trigger Off on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
 */
void Cse_TriggerHook_Button_control_Off_Return(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(_2022x_1ad00ce_1659683574035_551596_3462__2022x_1ad00ce_1659688235695_364403_4143) do not remove */
}


#ifdef __cplusplus
}
#endif /* __cplusplus */

/* BEG_USER_CODE(FOOTER) do not remove */
/* Add your includes here */
/* END_USER_CODE(FOOTER) do not remove */

#endif /* USER_HOOKS */
/* end of file */
