/* @date 2025-03-04T06:13:23.646672887Z */

/**********************************************************************
 * @file Cse_Flashlight.c
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678666246_667973_3242
 **********************************************************************/

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Tal.h" // tal_allocate
#include "Cse_cfg.h"
#include "Cse_Flashlight_hook.h"
#define CSE_C /* Macro to include only some specific parts of include files */
#include "Flashlight.h"

#include <string.h> // memset

#include "Timer_itf.h"
#include "Light_itf.h"
#include "Button_itf.h"
#include "Counter_itf.h"
#include "Tempo_itf.h"

#ifdef CSE_DEBUG
#include <stdio.h>
#define debug_cse(...) printf(__VA_ARGS__); fflush(stdout)
#else
#define debug_cse(...)
#endif

/**
 * Unique instance of the main entity
 */
Flashlight* pFlashlight;

/**
 * Required additional objects to instanciate
 */

task_descriptor task_descriptors[NUMBER_OF_TASKS];

static function_ptr task0_functions[4];
static Cse_instance_ptr task0_rteInstances[4];

static function_ptr task1_functions[1];
static Cse_instance_ptr task1_rteInstances[1];


/**********************************************************************
 * Function to Trigger Tick on opLight port
 * @generated_from _2022x_1ad00ce_1659683566715_850672_3426
 * @generated_from _2022x_1ad00ce_1659688287223_365621_4218
 **********************************************************************/
static void Cse_Trigger_Flashlight_timer_opLight_Tick(void){

	Cse_TriggerHook_Flashlight_timer_opLight_Tick_Start(&pFlashlight->to_light_ipTimer_Tick);
	debug_cse("DEBUG: Cse_Trigger_Flashlight_timer_opLight_Tick\n");
	pFlashlight->to_light_ipTimer_Tick.trigger = 1;
	Cse_TriggerHook_Flashlight_timer_opLight_Tick_Return(&pFlashlight->to_light_ipTimer_Tick);
}

/**********************************************************************
 * Function to Trigger On on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
 **********************************************************************/
static void Cse_Trigger_Flashlight_button_control_On(void){

	Cse_TriggerHook_Flashlight_button_control_On_Start(&pFlashlight->to_timer_ipControl_On);
	debug_cse("DEBUG: Cse_Trigger_Flashlight_button_control_On\n");
	pFlashlight->to_timer_ipControl_On.trigger = 1;
	pFlashlight->to_tempoManager_control_On.trigger = 1;
	Cse_TriggerHook_Flashlight_button_control_On_Return(&pFlashlight->to_timer_ipControl_On);
}

/**********************************************************************
 * Function to Trigger Off on control port
 * @generated_from _2022x_1ad00ce_1659683574035_551596_3462
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
 **********************************************************************/
static void Cse_Trigger_Flashlight_button_control_Off(void){

	Cse_TriggerHook_Flashlight_button_control_Off_Start(&pFlashlight->to_timer_ipControl_Off);
	debug_cse("DEBUG: Cse_Trigger_Flashlight_button_control_Off\n");
	pFlashlight->to_timer_ipControl_Off.trigger = 1;
	pFlashlight->to_tempoManager_control_Off.trigger = 1;
	Cse_TriggerHook_Flashlight_button_control_Off_Return(&pFlashlight->to_timer_ipControl_Off);
}


/**********************************************************************
 * Function to send light value on opLight port
 * @generated_from _2022x_1_1ad00ce_1677833604509_32091_3522
 * @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781
 **********************************************************************/
static void Cse_Write_Flashlight_light_opLight_light(Boolean* data){
	// Copy byte by byte
	unsigned int byteIdx;

	Cse_WriteHook_Flashlight_light_opLight_light_Start(&pFlashlight->from_light_opLight_light);
	debug_cse("DEBUG: Cse_Write_Flashlight_light_opLight_light\n");

	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) &pFlashlight->from_light_opLight_light)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Flashlight_light_opLight_light_Return(&pFlashlight->from_light_opLight_light);
	
}

/**********************************************************************
 * Function to send data value on opCounts port
 * @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025
 * @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025
 **********************************************************************/
static void Cse_Write_Flashlight_onCount_opCounts_data(Integer* data){
	// Copy byte by byte
	unsigned int byteIdx;

	Cse_WriteHook_Flashlight_onCount_opCounts_data_Start(&pFlashlight->from_onCount_opCounts_data);
	debug_cse("DEBUG: Cse_Write_Flashlight_onCount_opCounts_data\n");

	for(byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pFlashlight->from_onCount_opCounts_data)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Flashlight_onCount_opCounts_data_Return(&pFlashlight->from_onCount_opCounts_data);
	
}

/**********************************************************************
 * Function to send switchOff value on opControl port
 * @generated_from _2022x_2_16600ad_1710516884293_38745_4831
 * @generated_from _2022x_2_16600ad_1710521616807_180606_4578
 **********************************************************************/
static void Cse_Write_Flashlight_tempoManager_opControl_switchOff(Boolean* data){
	// Copy byte by byte
	unsigned int byteIdx;

	Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Start(&pFlashlight->from_tempoManager_opControl_switchOff);
	debug_cse("DEBUG: Cse_Write_Flashlight_tempoManager_opControl_switchOff\n");

	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) &pFlashlight->from_tempoManager_opControl_switchOff)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Return(&pFlashlight->from_tempoManager_opControl_switchOff);
	
}


/**********************************************************************
 * Function to read On value on ipControl port
 * @generated_from _2022x_1ad00ce_1659683568410_618746_3444
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
 **********************************************************************/
static void Cse_Read_Flashlight_timer_ipControl_On(SignalEvent_On_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_timer_ipControl_On_Start(&pFlashlight->to_timer_ipControl_On);
	debug_cse("DEBUG: RTE_Read_Flashlight_timer_ipControl_On\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_On_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_timer_ipControl_On)[byteIdx];
	}
	pFlashlight->to_timer_ipControl_On.trigger = 0;
	Cse_ReadHook_Flashlight_timer_ipControl_On_Return(&pFlashlight->to_timer_ipControl_On);
}

/**********************************************************************
 * Function to read Off value on ipControl port
 * @generated_from _2022x_1ad00ce_1659683568410_618746_3444
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
 **********************************************************************/
static void Cse_Read_Flashlight_timer_ipControl_Off(SignalEvent_Off_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_timer_ipControl_Off_Start(&pFlashlight->to_timer_ipControl_Off);
	debug_cse("DEBUG: RTE_Read_Flashlight_timer_ipControl_Off\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Off_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_timer_ipControl_Off)[byteIdx];
	}
	pFlashlight->to_timer_ipControl_Off.trigger = 0;
	Cse_ReadHook_Flashlight_timer_ipControl_Off_Return(&pFlashlight->to_timer_ipControl_Off);
}

/**********************************************************************
 * Function to read Tick value on ipTimer port
 * @generated_from _2022x_1ad00ce_1659683538905_142987_3408
 * @generated_from _2022x_1ad00ce_1659688287223_365621_4218
 **********************************************************************/
static void Cse_Read_Flashlight_light_ipTimer_Tick(SignalEvent_Tick_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_light_ipTimer_Tick_Start(&pFlashlight->to_light_ipTimer_Tick);
	debug_cse("DEBUG: RTE_Read_Flashlight_light_ipTimer_Tick\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Tick_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_light_ipTimer_Tick)[byteIdx];
	}
	pFlashlight->to_light_ipTimer_Tick.trigger = 0;
	Cse_ReadHook_Flashlight_light_ipTimer_Tick_Return(&pFlashlight->to_light_ipTimer_Tick);
}

/**********************************************************************
 * Function to read On value on control port
 * @generated_from _2022x_2_16600ad_1710517570715_697449_5230
 * @generated_from _2022x_1ad00ce_1659688230703_340985_4140
 **********************************************************************/
static void Cse_Read_Flashlight_tempoManager_control_On(SignalEvent_On_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_tempoManager_control_On_Start(&pFlashlight->to_tempoManager_control_On);
	debug_cse("DEBUG: RTE_Read_Flashlight_tempoManager_control_On\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_On_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_tempoManager_control_On)[byteIdx];
	}
	pFlashlight->to_tempoManager_control_On.trigger = 0;
	Cse_ReadHook_Flashlight_tempoManager_control_On_Return(&pFlashlight->to_tempoManager_control_On);
}

/**********************************************************************
 * Function to read Off value on control port
 * @generated_from _2022x_2_16600ad_1710517570715_697449_5230
 * @generated_from _2022x_1ad00ce_1659688235695_364403_4143
 **********************************************************************/
static void Cse_Read_Flashlight_tempoManager_control_Off(SignalEvent_Off_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_tempoManager_control_Off_Start(&pFlashlight->to_tempoManager_control_Off);
	debug_cse("DEBUG: RTE_Read_Flashlight_tempoManager_control_Off\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Off_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_tempoManager_control_Off)[byteIdx];
	}
	pFlashlight->to_tempoManager_control_Off.trigger = 0;
	Cse_ReadHook_Flashlight_tempoManager_control_Off_Return(&pFlashlight->to_tempoManager_control_Off);
}

/**********************************************************************
 * Function to read light value on ipLight port
 * @generated_from _2022x_1_1ad00ce_1679314077363_282445_5642
 * @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781
 **********************************************************************/
static void Cse_Read_Flashlight_onCount_ipLight_light(Boolean* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_onCount_ipLight_light_Start(&pFlashlight->from_light_opLight_light);
	debug_cse("DEBUG: RTE_Read_Flashlight_onCount_ipLight_light\n");
	Cse_ReadHook_Flashlight_onCount_ipLight_light_Return(&pFlashlight->from_light_opLight_light);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->from_light_opLight_light)[byteIdx];
	}
}

/**********************************************************************
 * Function to read switchOff value on ipControl2 port
 * @generated_from _2022x_2_16600ad_1710516938469_985483_4880
 * @generated_from _2022x_2_16600ad_1710521616807_180606_4578
 **********************************************************************/
static void Cse_Read_Flashlight_timer_ipControl2_switchOff(Boolean* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Start(&pFlashlight->from_tempoManager_opControl_switchOff);
	debug_cse("DEBUG: RTE_Read_Flashlight_timer_ipControl2_switchOff\n");
	Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Return(&pFlashlight->from_tempoManager_opControl_switchOff);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->from_tempoManager_opControl_switchOff)[byteIdx];
	}
}

/**********************************************************************
 * Function to read button value on button port
 * @generated_from _2022x_1_1ad00ce_1677833598836_377885_3507
 * @generated_from _2022x_2_16600ad_1710514982431_30757_4430
 **********************************************************************/
static void Cse_Read_Flashlight_button_button_button(Boolean* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_button_button_button_Start(&pFlashlight->from_UNCONNECTED_button_button);
	debug_cse("DEBUG: RTE_Read_Flashlight_button_button_button\n");
	Cse_ReadHook_Flashlight_button_button_button_Return(&pFlashlight->from_UNCONNECTED_button_button);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->from_UNCONNECTED_button_button)[byteIdx];
	}
}

/**********************************************************************
 * Function to read button value on ipTempo port
 * @generated_from _2022x_2_16600ad_1710516249654_577579_4733
 * @generated_from _2022x_2_16600ad_1710516859703_529569_4765
 **********************************************************************/
static void Cse_Read_Flashlight_tempoManager_ipTempo_button(Integer* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Start(&pFlashlight->from_UNCONNECTED_ipTempo_button);
	debug_cse("DEBUG: RTE_Read_Flashlight_tempoManager_ipTempo_button\n");
	Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Return(&pFlashlight->from_UNCONNECTED_ipTempo_button);
	for(byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->from_UNCONNECTED_ipTempo_button)[byteIdx];
	}
}



/**********************************************************************
 * Map the communication APIs to component instances
 * First function to call before Cse_task_descriptors_init & Cse_components_init
 **********************************************************************/
void Cse_component_instances_init(void){
	pFlashlight = tal_allocate(sizeof(Flashlight));

	/* Erase memory section for Behaviors proper implementation */
	memset(pFlashlight, 0, sizeof(Flashlight));

	Flashlight_ctor(pFlashlight);
	
	/* BEG: Timer Communication Interface Configuration */
	/* Write functions */
	/* Trigger functions */
	pFlashlight->timer.cse_itf.Trigger_opLight_Tick = &Cse_Trigger_Flashlight_timer_opLight_Tick;
	/* Read functions */
	pFlashlight->timer.cse_itf.Read_ipControl_On = &Cse_Read_Flashlight_timer_ipControl_On;
	pFlashlight->timer.cse_itf.Read_ipControl_Off = &Cse_Read_Flashlight_timer_ipControl_Off;
	pFlashlight->timer.cse_itf.Read_ipControl2_switchOff = &Cse_Read_Flashlight_timer_ipControl2_switchOff;
	/* Server call functions */
	/* END: Timer Cmmunication Interface Configuration */

	/* BEG: Light Communication Interface Configuration */
	/* Write functions */
	pFlashlight->light.cse_itf.Write_opLight_light = &Cse_Write_Flashlight_light_opLight_light;
	/* Trigger functions */
	/* Read functions */
	pFlashlight->light.cse_itf.Read_ipTimer_Tick = &Cse_Read_Flashlight_light_ipTimer_Tick;
	/* Server call functions */
	/* END: Light Cmmunication Interface Configuration */

	/* BEG: Button Communication Interface Configuration */
	/* Write functions */
	/* Trigger functions */
	pFlashlight->button.cse_itf.Trigger_control_On = &Cse_Trigger_Flashlight_button_control_On;
	pFlashlight->button.cse_itf.Trigger_control_Off = &Cse_Trigger_Flashlight_button_control_Off;
	/* Read functions */
	pFlashlight->button.cse_itf.Read_button_button = &Cse_Read_Flashlight_button_button_button;
	/* Server call functions */
	/* END: Button Cmmunication Interface Configuration */

	/* BEG: Counter Communication Interface Configuration */
	/* Write functions */
	pFlashlight->onCount.cse_itf.Write_opCounts_data = &Cse_Write_Flashlight_onCount_opCounts_data;
	/* Trigger functions */
	/* Read functions */
	pFlashlight->onCount.cse_itf.Read_ipLight_light = &Cse_Read_Flashlight_onCount_ipLight_light;
	/* Server call functions */
	/* END: Counter Cmmunication Interface Configuration */

	/* BEG: Tempo Communication Interface Configuration */
	/* Write functions */
	pFlashlight->tempoManager.cse_itf.Write_opControl_switchOff = &Cse_Write_Flashlight_tempoManager_opControl_switchOff;
	/* Trigger functions */
	/* Read functions */
	pFlashlight->tempoManager.cse_itf.Read_ipTempo_button = &Cse_Read_Flashlight_tempoManager_ipTempo_button;
	pFlashlight->tempoManager.cse_itf.Read_control_On = &Cse_Read_Flashlight_tempoManager_control_On;
	pFlashlight->tempoManager.cse_itf.Read_control_Off = &Cse_Read_Flashlight_tempoManager_control_Off;
	/* Server call functions */
	/* END: Tempo Cmmunication Interface Configuration */

}

/**********************************************************************
 * Function configuring each task.
 * Function to call just after Cse_component_instances_init
 **********************************************************************/
void Cse_task_descriptors_init(void){
  /* Runnable to task mapping */
  task0_functions[0] = (function_ptr)Timer_Timer;
  task0_rteInstances[0] = &pFlashlight->timer.cse_itf;
  /* Runnable to task mapping */
  task0_functions[1] = (function_ptr)Light_Light;
  task0_rteInstances[1] = &pFlashlight->light.cse_itf;
  /* Runnable to task mapping */
  task0_functions[2] = (function_ptr)Button_Button;
  task0_rteInstances[2] = &pFlashlight->button.cse_itf;
  /* Runnable to task mapping */
  task0_functions[3] = (function_ptr)Counter_OB_cnt;
  task0_rteInstances[3] = &pFlashlight->onCount.cse_itf;
  /* Runnable to task mapping */
  task1_functions[0] = (function_ptr)Tempo_TempoManager;
  task1_rteInstances[0] = &pFlashlight->tempoManager.cse_itf;

  /* Periodic task task0 configuration */
  task_descriptors[0].type = PERIODIC;
  task_descriptors[0].period = 50;
  task_descriptors[0].functions = task0_functions;
  task_descriptors[0].cse_instances = task0_rteInstances;
  task_descriptors[0].nfunctions = 4;

  /* Periodic task task1 configuration */
  task_descriptors[1].type = PERIODIC;
  task_descriptors[1].period = 100;
  task_descriptors[1].functions = task1_functions;
  task_descriptors[1].cse_instances = task1_rteInstances;
  task_descriptors[1].nfunctions = 1;


}

/**********************************************************************
 * Function calling all the init functions as configured in the model.
 * To be called after Cse_task_descriptors_init & Cse_component_instances_init
 **********************************************************************/
void Cse_components_init(void) {
	Timer_Timer_init(&pFlashlight->timer.cse_itf);
	Light_Light_init(&pFlashlight->light.cse_itf);
	Button_Button_init(&pFlashlight->button.cse_itf);
	Counter_OB_cnt_init(&pFlashlight->onCount.cse_itf);
	Tempo_TempoManager_init(&pFlashlight->tempoManager.cse_itf);
}

/* end of file */
