/* @date 2025-03-04T06:13:23.787715856Z */

/************************************************
 * @file Flashlight_internal_types.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678666246_667973_3242
 ***********************************************/

#ifndef FLASHLIGHT_INTERNAL_TYPES_H
#define FLASHLIGHT_INTERNAL_TYPES_H

#include <stdbool.h>


/**********************************************************************
 * Data Types used in statemachines and activities definition
 **********************************************************************/

#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool    Boolean;
#endif

#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int     Integer;
#endif

#ifndef Real_DEFINITION
#define Real_DEFINITION
typedef double   Real;
#endif

#ifndef String_DEFINITION
#define String_DEFINITION
typedef char *  String;
#endif

#ifndef TRUE
#define TRUE    true
#endif

#ifndef FALSE
#define FALSE   false
#endif

#endif //#ifndef FLASHLIGHT_INTERNAL_TYPES_H

/* end of file */