/* @date 2025-03-04T06:13:23.782383139Z */

/**********************************************************************
 * @file Flashlight.c
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678666246_667973_3242
 **********************************************************************/

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include <stddef.h> // NULL
#include "Flashlight.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */


/* Function pointer to destructor function generated automatically */
static void Flashlight_dtor(struct Flashlight* self){
	/* Call hierarchical destructors */
	self->timer.dtor(&self->timer);
	self->light.dtor(&self->light);
	self->button.dtor(&self->button);
	self->onCount.dtor(&self->onCount);
	self->tempoManager.dtor(&self->tempoManager);

	/* Clean pointer to destructor */
	self->dtor = NULL;
}

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_1ad00ce_1659678666246_667973_3242
 */
void Flashlight_ctor(Flashlight* self){
	/* Init pointer to destructor */
	self->dtor = Flashlight_dtor;

	/* Default values */

	/* Call hierarchical constructors */
	Timer_ctor(&self->timer);
	Light_ctor(&self->light);
	Button_ctor(&self->button);
	Counter_ctor(&self->onCount);
	Tempo_ctor(&self->tempoManager);
}
/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */