/* @date 2025-03-04T06:13:23.757703693Z */

/**********************************************************************
 * @file Flashlight.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678666246_667973_3242
 **********************************************************************/

#ifndef FLASHLIGHT_H
#define FLASHLIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Flashlight_internal_types.h"
#include "Light.h"
#include "Button.h"
#include "Timer.h"
#include "Tempo.h"
#include "Counter.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from _2022x_1ad00ce_1659678666246_667973_3242 */	 
typedef struct Flashlight{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Flashlight*);

	/**
	 * @brief Public attribute for composition relation to Timer:timer
	 * @generated_from _2022x_1ad00ce_1659678985369_326992_3323
	 */
	struct Timer timer;
		
	/**
	 * @brief Public attribute for composition relation to Light:light
	 * @generated_from _2022x_1ad00ce_1659679002911_573881_3367
	 */
	struct Light light;
		
	/**
	 * @brief Public attribute for composition relation to Button:button
	 * @generated_from _2022x_1ad00ce_1659678969454_111100_3279
	 */
	struct Button button;
		
	/**
	 * @brief Public attribute for composition relation to Counter:onCount
	 * @generated_from _2022x_1_1ad00ce_1679314085594_615266_5739
	 */
	struct Counter onCount;
		
	/**
	 * @brief Public attribute for composition relation to Tempo:tempoManager
	 * @generated_from _2022x_2_16600ad_1710867778948_375532_5980
	 */
	struct Tempo tempoManager;
		
	/**********************************************************************
	 * Communication & Scheduling Environment - Shared variables declaration
	 **********************************************************************/
	/* @generated_from _2022x_1ad00ce_1659683568410_618746_3444 */
	/* @generated_from _2022x_1ad00ce_1659688230703_340985_4140 */
	/* @generated_from _2022x_1_1ad00ce_1677477360183_160247_3627 */
	SignalEvent_On_type to_timer_ipControl_On;
	 
	/* @generated_from _2022x_1ad00ce_1659683568410_618746_3444 */
	/* @generated_from _2022x_1ad00ce_1659688235695_364403_4143 */
	/* @generated_from _2022x_1_1ad00ce_1677477360183_160247_3627 */
	SignalEvent_Off_type to_timer_ipControl_Off;
	 
	/* @generated_from _2022x_1_1ad00ce_1677833604509_32091_3522 */
	/* @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781 */
	/* @generated_from _2022x_1_1ad00ce_1679480606974_479394_7367 */
	/* @generated_from _2022x_1_1ad00ce_1679489083332_365172_4499 */
	Boolean from_light_opLight_light;
	 
	/* @generated_from _2022x_1ad00ce_1659683538905_142987_3408 */
	/* @generated_from _2022x_1ad00ce_1659688287223_365621_4218 */
	/* @generated_from _2022x_1ad00ce_1659686574407_717334_3637 */
	SignalEvent_Tick_type to_light_ipTimer_Tick;
	 
	/* @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025 */
	/* @generated_from _2022x_1_1ad00ce_1679392992085_960294_6025 */
	/* @generated_from _2022x_1_1ad00ce_1679394150722_604259_6077 */
	Integer from_onCount_opCounts_data;
	 
	/* @generated_from _2022x_2_16600ad_1710516884293_38745_4831 */
	/* @generated_from _2022x_2_16600ad_1710521616807_180606_4578 */
	/* @generated_from _2022x_2_16600ad_1710867891716_627817_6170 */
	Boolean from_tempoManager_opControl_switchOff;
	 
	/* @generated_from _2022x_2_16600ad_1710517570715_697449_5230 */
	/* @generated_from _2022x_1ad00ce_1659688230703_340985_4140 */
	/* @generated_from _2022x_2_16600ad_1710867896687_368060_6186 */
	SignalEvent_On_type to_tempoManager_control_On;
	 
	/* @generated_from _2022x_2_16600ad_1710517570715_697449_5230 */
	/* @generated_from _2022x_1ad00ce_1659688235695_364403_4143 */
	/* @generated_from _2022x_2_16600ad_1710867896687_368060_6186 */
	SignalEvent_Off_type to_tempoManager_control_Off;
	 
	/* @generated_from _2022x_1_1ad00ce_1677833598836_377885_3507 */
	/* @generated_from _2022x_2_16600ad_1710514982431_30757_4430 */
	/* @generated_from _2022x_2_16600ad_1710867896687_368060_6186 */
	Boolean from_UNCONNECTED_button_button;
	 
	/* @generated_from _2022x_2_16600ad_1710516249654_577579_4733 */
	/* @generated_from _2022x_2_16600ad_1710516859703_529569_4765 */
	/* @generated_from _2022x_2_16600ad_1710867896687_368060_6186 */
	Integer from_UNCONNECTED_ipTempo_button;
	 
	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Flashlight;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_1ad00ce_1659678666246_667973_3242
 */
void Flashlight_ctor(Flashlight* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef FLASHLIGHT_H

/* end of file */