/* @date 2025-03-04T06:13:23.886999513Z */

/**********************************************************************
 * @file Light_Light.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659688246184_266641_4147
 **********************************************************************/

/* Application code for statemachine "Light" */

#include "Light_Light.h"
#include "Light.h"

#define STATEMACHINE        Light_struct

/**********************************************************************
 * Function Light_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from _2022x_1ad00ce_1659688246184_266641_4147
 **********************************************************************/
static void Light_struct_dtor(struct Light_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function Light_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from _2022x_1ad00ce_1659688246184_266641_4147
 **********************************************************************/
void Light_struct_ctor(struct Light_struct * const self, struct Light* classifier) {
    /* Init pointer to destructor */
    self->dtor = Light_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * separate code of user-modifiable functions to prevent accidental
 * changes to code above.
 **********************************************************************/
#include "Light_Light_usr.c"

/**********************************************************************
 * Function _basic_Light_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659688246184_266641_4147
 **********************************************************************/
void _basic_Light_init(Light_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T)0;
    instance->CURRENT_STATE_0 = LIGHT_STATE_T_VOID;

    StateMachine_init(instance);
}

/**********************************************************************
 * Function _basic_Light
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659688246184_266641_4147
 **********************************************************************/
void _basic_Light(Light_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> Off */
        /* @generated_from _2022x_1ad00ce_1659688246252_237256_4177 */
        instance->CURRENT_STATE_0 = LIGHT_STATE_T_Off;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State Off */
        /* @generated_from _2022x_1ad00ce_1659688246252_961360_4176 */
        case LIGHT_STATE_T_Off: {
            instance->DONE_ACTIVITY = TRUE;
            Off_Do(instance); /* Do of LIGHT_STATE_T_Off */
            if( instance->EVENT == LIGHT_EVENT_T_Tick ) {
                /* Transition Off -> On */
                /* @generated_from _2022x_1ad00ce_1659688271021_87915_4198 */
                instance->CURRENT_STATE_0 = LIGHT_STATE_T_On;
                instance->EVENT = LIGHT_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of LIGHT_STATE_T_Off */
        }
        /* State On */
        /* @generated_from _2022x_1ad00ce_1659688271019_988850_4197 */
        case LIGHT_STATE_T_On: {
            instance->DONE_ACTIVITY = TRUE;
            On_Do(instance); /* Do of LIGHT_STATE_T_On */
            if( instance->EVENT == LIGHT_EVENT_T_Tick ) {
                /* Transition On -> Off */
                /* @generated_from _2022x_1ad00ce_1659688277716_714502_4215 */
                instance->CURRENT_STATE_0 = LIGHT_STATE_T_Off;
                instance->EVENT = LIGHT_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of LIGHT_STATE_T_On */
        }
        default: break;
    } /* end of switch */
}

/**********************************************************************
 * Function _basic_Light_end
 * Implements statemachine exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659688246184_266641_4147
 **********************************************************************/
void _basic_Light_end(Light_struct *instance) {
    StateMachine_end(instance);
}

/* end of file */
