/* @date 2025-03-04T06:13:23.885568217Z */

/**********************************************************************
 * @file Light_Light.h
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659688246184_266641_4147
 **********************************************************************/

#ifndef LIGHT_LIGHT_H
#define LIGHT_LIGHT_H

#include "Light_itf.h" /* Datatypes defined at interfaces */
#include "Light_internal_types.h" /* Datatypes for internal data */


/* BEG_USER_CODE(types) do not remove */

#ifndef WALLCLOCK_T
#define WALLCLOCK_T WALLCLOCK_T
typedef double  WALLCLOCK_T;  /* time type (can be any scalar) */
#endif
#ifndef USERDATA_T
#define USERDATA_T  USERDATA_T
typedef void *  USERDATA_T;   /* replace this pointer by an anonymous struct if needed. */
#endif

/* END_USER_CODE(types) do not remove */

typedef enum {
    LIGHT_STATE_T_INITIAL_0,
    LIGHT_STATE_T_Off,
    LIGHT_STATE_T_On,
    LIGHT_STATE_T_VOID
} LIGHT_STATE_T;

typedef enum {
    LIGHT_EVENT_T_Tick,
    LIGHT_EVENT_T_NO_EVENT
} LIGHT_EVENT_T;

typedef struct Light_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Light_struct*);

    /* user data */
    USERDATA_T  USERDATA;

    /* data */
    Boolean     opLight_light;


    /* sub behaviors */

    /* pointer to classifier */
    struct Light* classifier;

    /* internal */
    LIGHT_STATE_T   CURRENT_STATE_0;
    WALLCLOCK_T WALL_CLOCK;
    LIGHT_EVENT_T   EVENT;
    Boolean     FIRST;
    Boolean     DONE_ACTIVITY;
} Light_struct;

void Light_struct_ctor(struct Light_struct * const self, struct Light* classifier);
void _basic_Light_init(Light_struct *instance);
void _basic_Light(Light_struct *instance);
void _basic_Light_end(Light_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*LIGHT_LIGHT_H*/
/* end of file */
