/* @date 2025-03-04T06:13:23.893070745Z */

/**********************************************************************
 * @file Light_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659679002893_124708_3365
 **********************************************************************/

#include "Light.h"
#include "Light_itf.h"
#include "Light_Light.h"
#include "Tal.h" // tal_getTime

/**********************************************************************
 * Init function invoked for component initialization purpose.
 **********************************************************************/
void Light_init(Cse_Light_Struct* inst) {
    /* Get component Light from "parent" */
    Light *pLight = inst->parent;

    /* Get behavior light from the Light */
    Light_struct *light = &pLight->Light;


    /* Initialization job which can be done in a separated function or inlined. */
    _basic_Light_init(light);
}

/**********************************************************************
 * Main function Body of behavior "Light"
 **********************************************************************/
void Light(Cse_Light_Struct* inst) {
    /* Get component Light from "parent" */
    Light *pLight = inst->parent;

    /* Get behavior light from the Light */
    Light_struct *light = &pLight->Light;

    /* handle external event(s) */
    light->EVENT = LIGHT_EVENT_T_NO_EVENT;
    {// cppcheck shadowVariable
        /* @generated_from _2022x_1ad00ce_1659688287223_365621_4218 */
        SignalEvent_Tick_type signalEvent_Tick;
        Cse_Read_ipTimer_Tick(inst, &signalEvent_Tick);
        if(signalEvent_Tick.trigger == TRUE) {
            light->EVENT = LIGHT_EVENT_T_Tick;
        }
    }
    /* handle internal event (s) */

    /* update WALL_CLOCK */
    light->WALL_CLOCK = tal_GetTime();

    (void)_basic_Light(light);

    /* Copy data out */
    light->opLight_light = pLight->poutData;

    /* write output(s) */
    Cse_Write_opLight_light(inst, &light->opLight_light);

}

/**********************************************************************
 * Exit function invoked at execution ending
 **********************************************************************/
void Light_end(Cse_Light_Struct* inst) {
    /* Get component Light from "parent" */
    Light *pLight = inst->parent;

    /* Get behavior light from the Light */
    Light_struct *light = &pLight->Light;

    _basic_Light_end(light);
}

/* end of file */
