/* @date 2025-03-04T06:13:23.893430992Z */

/**********************************************************************
 * @file Light_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from _2022x_1ad00ce_1659679002893_124708_3365
 **********************************************************************/

#ifndef CSE_LIGHT_ITF_H
#define CSE_LIGHT_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Light_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* @generated_from _2022x_1_1ad00ce_1677833604509_32091_3522 */
	/* @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781 */	
	void (*Write_opLight_light)(Boolean* msg);
	/* Trigger functions */
	/* Read functions */
	/* @generated_from _2022x_1ad00ce_1659683538905_142987_3408 */
	/* @generated_from _2022x_1ad00ce_1659688287223_365621_4218 */  
	void (*Read_ipTimer_Tick)(SignalEvent_Tick_type* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Light *parent;
}Cse_Light_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from _2022x_1ad00ce_1659688246184_266641_4147 */ 
void Light_Light_init(Cse_Light_Struct* self);
void Light_Light(Cse_Light_Struct* instance);
void Light_Light_end(Cse_Light_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from _2022x_1ad00ce_1659688246184_266641_4147 */ 
#define Light(...) Light_Light(__VA_ARGS__)
/* @generated_from _2022x_1ad00ce_1659688246184_266641_4147 */ 
#define Light_init(...) Light_Light_init(__VA_ARGS__)
/* @generated_from _2022x_1ad00ce_1659688246184_266641_4147 */ 
#define Light_end(...) Light_Light_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */
/* @generated_from _2022x_1_1ad00ce_1677833604509_32091_3522 */
/* @generated_from _2022x_1_1ad00ce_1679479084488_911966_6781 */	
void Cse_Write_opLight_light(Cse_Light_Struct* instance, Boolean* msg);

/* Trigger functions declaration */

/* Read functions declaration */
/* @generated_from _2022x_1ad00ce_1659683538905_142987_3408 */
/* @generated_from _2022x_1ad00ce_1659688287223_365621_4218 */
void Cse_Read_ipTimer_Tick(Cse_Light_Struct* instance, SignalEvent_Tick_type* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Read_ipTimer_Tick(inst, data) inst->Read_ipTimer_Tick(data)
#define Cse_Write_opLight_light(inst, data) inst->Write_opLight_light(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_LIGHT_ITF_H */

/* end of file */
