/* @date 2025-03-04T06:13:23.901096554Z */

/**********************************************************************
 * @file Light.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659679002893_124708_3365
 **********************************************************************/

#ifndef LIGHT_H
#define LIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Light_itf.h"
#include "Light_internal_types.h"
#include "Light_Light.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from _2022x_1ad00ce_1659679002893_124708_3365 */	 
typedef struct Light{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Light*);

	/**
	 * @brief Public attribute for composition relation to Boolean:poutData
	 * @generated_from _2022x_1_1ad00ce_1678450596358_632926_4770
	 */
	Boolean poutData;
		
	/**
	 * Data for Behavior Light
	 * @generated_from _2022x_1ad00ce_1659688246184_266641_4147
	 */
	Light_struct Light;

	/**********************************************************************
	 * Communication Interface section
	 **********************************************************************/
	/**
	 * Communication interface
	 * @generated_from _2022x_1ad00ce_1659679002893_124708_3365
	 */
	Cse_Light_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Light;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_1ad00ce_1659679002893_124708_3365
 */
void Light_ctor(Light* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef LIGHT_H

/* end of file */