/* @date 2025-03-04T06:13:23.903767483Z */

/**********************************************************************
 * @file Light.c
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659679002893_124708_3365
 **********************************************************************/

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include <stddef.h> // NULL
#include "Light.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */


/* Function pointer to destructor function generated automatically */
static void Light_dtor(struct Light* self){
	/* Call hierarchical destructors */
	self->Light.dtor(&self->Light);

	/* Clean pointer to destructor */
	self->dtor = NULL;
}

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_1ad00ce_1659679002893_124708_3365
 */
void Light_ctor(Light* self){
	/* Init pointer to destructor */
	self->dtor = Light_dtor;

	/* Default values */

	/* Configure Communication Interface */
	self->cse_itf.parent = self;

	/* Call hierarchical constructors */
	Light_struct_ctor(&self->Light, self);
}
/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */