/* @date 2025-03-04T06:13:23.893990971Z */

/**********************************************************************
 * @file Light_type.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from _2022x_1ad00ce_1659679002893_124708_3365
 **********************************************************************/

#ifndef LIGHT_TYPE_H
#define LIGHT_TYPE_H

#include <stddef.h>
/* stdbool.h define standard bool (true/false) starting from C99 standard */ 
#include <stdbool.h>

/**********************************************************************
 * Data Type trigger_type definition
 **********************************************************************/
#ifndef trigger_type_DEFINITION
#define trigger_type_DEFINITION
typedef bool trigger_type;
#endif /* trigger_type */

/**********************************************************************
 * Data Type SignalEvent_Tick_type definition
 **********************************************************************/
#ifndef SignalEvent_Tick_type_DEFINITION
#define SignalEvent_Tick_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_Tick_type;
#endif /* SignalEvent_Tick_type */

/**********************************************************************
 * Data Type Boolean definition
 **********************************************************************/
#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool Boolean;
#endif /* Boolean */

#endif /* LIGHT_TYPE_H */

/* end of file */
