/* @date 2025-03-04T06:13:23.923661992Z */

/**********************************************************************
 * @file Model_Functions_Send_On.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659688754535_274895_4354
 **********************************************************************/

/* Application code for activity "Send On" */

#include "Model_Functions_Send_On.h"

#include "Button.h"
#include <string.h>
/**********************************************************************
 * handy helpers
 **********************************************************************/
#define button_button   instance->button_button
#define button          button_button
#define pinData         instance->classifier->pinData

/**********************************************************************
 * default event handlers
 **********************************************************************/
// cppcheck-suppress constParameterCallback
static MODEL_FUNCTIONS_SEND_ON_EVENT_T default_peekEvent(Model_Functions_Send_On_struct *instance) {
    return instance->EVENT;
}
static MODEL_FUNCTIONS_SEND_ON_EVENT_T default_nextEvent(Model_Functions_Send_On_struct *instance) {
    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    return MODEL_FUNCTIONS_SEND_ON_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent(Model_Functions_Send_On_struct *instance, MODEL_FUNCTIONS_SEND_ON_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == MODEL_FUNCTIONS_SEND_ON_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************
 * helpers
 **********************************************************************/
static inline Boolean isRunning(const Model_Functions_Send_On_struct* const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************
 * Function Model_Functions_Send_On_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from _2022x_1ad00ce_1659688754535_274895_4354
 **********************************************************************/
static void Model_Functions_Send_On_struct_dtor(struct Model_Functions_Send_On_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function Model_Functions_Send_On_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from _2022x_1ad00ce_1659688754535_274895_4354
 **********************************************************************/
void Model_Functions_Send_On_struct_ctor(struct Model_Functions_Send_On_struct * const self, struct Button* classifier) \
    {
    /* Init pointer to destructor */
    self->dtor = Model_Functions_Send_On_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * Function _basic_Model_Functions_Send_On_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659688754535_274895_4354
 **********************************************************************/
void _basic_Model_Functions_Send_On_init(Model_Functions_Send_On_struct *instance) {
    if(instance->peekEVENT == NULL) {instance->peekEVENT = default_peekEvent;}
    if(instance->nextEVENT == NULL) {instance->nextEVENT = default_nextEvent;}
    if(instance->sendEVENT == NULL) {instance->sendEVENT = default_sendEvent;}
    instance->EVENT = MODEL_FUNCTIONS_SEND_ON_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));

    instance->WALL_CLOCK        = (WALLCLOCK_T)0;

}

/**********************************************************************
 * Function _basic_Model_Functions_Send_On
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659688754535_274895_4354
 **********************************************************************/
Boolean _basic_Model_Functions_Send_On(Model_Functions_Send_On_struct *instance) {
    /* initialization */
    if(isRunning(instance) == FALSE) {
        instance->flow[0] = 1u; /* SET_FLOW->SendSignalAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node SendSignalAction */
    /* @generated_from _2022x_1ad00ce_1659688980647_633314_4472 */
    if(1u == (instance->flow[0] & 1u)) { /* TST_FLOW<-Init */
        Boolean success = instance->sendEVENT(instance, MODEL_FUNCTIONS_SEND_ON_EVENT_T_On);
        if(success != FALSE) {
            instance->flow[0] ^= 1u; /* CLR_FLOW<-Init */
        }
    }

    return (FALSE == isRunning(instance)) ? TRUE : FALSE;
}

/**********************************************************************
 * Function _basic_Model_Functions_Send_On_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659688754535_274895_4354
 **********************************************************************/
void _basic_Model_Functions_Send_On_end(Model_Functions_Send_On_struct *instance) {
    (void)instance; /* MISRA rule 2.7 (unused parameter) */
}

/* end of file */
