/* @date 2025-03-04T06:13:23.975440895Z */

/**********************************************************************
 * @file Tempo.c
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from _2022x_2_16600ad_1710516215858_329482_4706
 **********************************************************************/

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include <stddef.h> // NULL
#include "Tempo.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */


/* Function pointer to destructor function generated automatically */
static void Tempo_dtor(struct Tempo* self){
	/* Call hierarchical destructors */
	self->TempoManager.dtor(&self->TempoManager);

	/* Clean pointer to destructor */
	self->dtor = NULL;
}

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_2_16600ad_1710516215858_329482_4706
 */
void Tempo_ctor(Tempo* self){
	/* Init pointer to destructor */
	self->dtor = Tempo_dtor;

	/* Default values */

	/* Configure Communication Interface */
	self->cse_itf.parent = self;

	/* Call hierarchical constructors */
	TempoManager_struct_ctor(&self->TempoManager, self);
}
/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */