/* @date 2025-03-04T06:13:23.962401362Z */

/**********************************************************************
 * @file Tempo_TempoManager.h
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_2_16600ad_1710518012706_366349_5363
 **********************************************************************/

#ifndef TEMPO_TEMPOMANAGER_H
#define TEMPO_TEMPOMANAGER_H

#include "Tempo_itf.h" /* Datatypes defined at interfaces */
#include "Tempo_internal_types.h" /* Datatypes for internal data */


/* BEG_USER_CODE(types) do not remove */

#ifndef WALLCLOCK_T
#define WALLCLOCK_T WALLCLOCK_T
typedef double  WALLCLOCK_T;  /* time type (can be any scalar) */
#endif
#ifndef USERDATA_T
#define USERDATA_T  USERDATA_T
typedef void *  USERDATA_T;   /* replace this pointer by an anonymous struct if needed. */
#endif

/* END_USER_CODE(types) do not remove */

typedef enum {
    TEMPOMANAGER_STATE_T_INITIAL_0,
    TEMPOMANAGER_STATE_T_Init,
    TEMPOMANAGER_STATE_T_Tempo,
    TEMPOMANAGER_STATE_T_VOID
} TEMPOMANAGER_STATE_T;

typedef enum {
    TEMPOMANAGER_EVENT_T_Off,
    TEMPOMANAGER_EVENT_T_On,
    TEMPOMANAGER_EVENT_T_NO_EVENT
} TEMPOMANAGER_EVENT_T;

typedef struct TempoManager_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct TempoManager_struct*);

    /* user data */
    USERDATA_T  USERDATA;

    /* data */
    Integer     ipTempo_button;
    Boolean     opControl_switchOff;



    /* sub behaviors */

    /* pointer to classifier */
    struct Tempo* classifier;

    /* internal */
    TEMPOMANAGER_STATE_T    CURRENT_STATE_0;
    WALLCLOCK_T WALL_CLOCK;
    TEMPOMANAGER_EVENT_T    EVENT;
    Boolean     FIRST;
    Boolean     DONE_ACTIVITY;
} TempoManager_struct;

void TempoManager_struct_ctor(struct TempoManager_struct * const self, struct Tempo* classifier);
void _basic_TempoManager_init(TempoManager_struct *instance);
void _basic_TempoManager(TempoManager_struct *instance);
void _basic_TempoManager_end(TempoManager_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*TEMPO_TEMPOMANAGER_H*/
/* end of file */
