/* @date 2025-03-04T06:13:23.967121241Z */

/**********************************************************************
 * @file Tempo_type.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from _2022x_2_16600ad_1710516215858_329482_4706
 **********************************************************************/

#ifndef TEMPO_TYPE_H
#define TEMPO_TYPE_H

#include <stddef.h>
/* stdbool.h define standard bool (true/false) starting from C99 standard */ 
#include <stdbool.h>

/**********************************************************************
 * Data Type Integer definition
 **********************************************************************/
#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int Integer;
#endif /* Integer */

/**********************************************************************
 * Data Type Boolean definition
 **********************************************************************/
#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool Boolean;
#endif /* Boolean */

/**********************************************************************
 * Data Type trigger_type definition
 **********************************************************************/
#ifndef trigger_type_DEFINITION
#define trigger_type_DEFINITION
typedef bool trigger_type;
#endif /* trigger_type */

/**********************************************************************
 * Data Type SignalEvent_On_type definition
 **********************************************************************/
#ifndef SignalEvent_On_type_DEFINITION
#define SignalEvent_On_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_On_type;
#endif /* SignalEvent_On_type */

/**********************************************************************
 * Data Type SignalEvent_Off_type definition
 **********************************************************************/
#ifndef SignalEvent_Off_type_DEFINITION
#define SignalEvent_Off_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_Off_type;
#endif /* SignalEvent_Off_type */

#endif /* TEMPO_TYPE_H */

/* end of file */
