/*2024-03-18T10:41:23.982358100Z*/

/**********************************************************************
 * @file Tempo_TempoManager_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v100
 **********************************************************************/

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define ipTempo     instance->ipTempo_button
#define opControl   instance->opControl_switchOff
#define tempo       instance->classifier->tempo

#include "Tal.h"
#include "Tempo_TempoManager.h"

#define IMPL_WITH_CALLBACK

bool myTimerRunning = false;
timerId myTimerId = 0;

#ifdef IMPL_WITH_CALLBACK
void *cbk(void* arg){
	tal_printf("END_OF_TIMER_IN_CALLBACK\n");
	TempoManager_struct *instance = (TempoManager_struct*)arg;

	opControl = true;
	return NULL;
}

void *myFct(void* arg){
	myTimerId = tal_CreateTimer(cbk, arg);
	TempoManager_struct *instance = (TempoManager_struct*)arg;
	if(ipTempo > 0){
		tal_SetTimer(myTimerId, ipTempo, false);
		myTimerRunning = true;
		tal_WaitTimer(myTimerId);
		tal_printf("wait timer done\n");
	}
	return NULL;
}
#else

void *myFct(void* arg){
	myTimerId = tal_CreateTimer(NULL, NULL);
	tal_SetTimer(myTimerId, 4, false);
	tal_WaitTimer(myTimerId);

	tal_printf(TAL.tracer, "END_OF_TIMER\n");
}

#endif

/* end of file */
