/* @date 2025-03-04T06:13:23.858090989Z */

/**********************************************************************
 * @file Timer_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from _2022x_1ad00ce_1659678985350_593051_3321
 **********************************************************************/

#ifndef CSE_TIMER_ITF_H
#define CSE_TIMER_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Timer_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* Trigger functions */
	/* @generated_from _2022x_1ad00ce_1659683566715_850672_3426 */
	/* @generated_from _2022x_1ad00ce_1659688287223_365621_4218 */  
	void (*Trigger_opLight_Tick)(void);
	/* Read functions */
	/* @generated_from _2022x_1ad00ce_1659683568410_618746_3444 */
	/* @generated_from _2022x_1ad00ce_1659688230703_340985_4140 */  
	void (*Read_ipControl_On)(SignalEvent_On_type* msg);
	/* @generated_from _2022x_1ad00ce_1659683568410_618746_3444 */
	/* @generated_from _2022x_1ad00ce_1659688235695_364403_4143 */  
	void (*Read_ipControl_Off)(SignalEvent_Off_type* msg);
	/* @generated_from _2022x_2_16600ad_1710516938469_985483_4880 */
	/* @generated_from _2022x_2_16600ad_1710521616807_180606_4578 */  
	void (*Read_ipControl2_switchOff)(Boolean* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Timer *parent;
}Cse_Timer_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from _2022x_1ad00ce_1659687960195_296841_3882 */ 
void Timer_Timer_init(Cse_Timer_Struct* self);
void Timer_Timer(Cse_Timer_Struct* instance);
void Timer_Timer_end(Cse_Timer_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from _2022x_1ad00ce_1659687960195_296841_3882 */ 
#define Timer(...) Timer_Timer(__VA_ARGS__)
/* @generated_from _2022x_1ad00ce_1659687960195_296841_3882 */ 
#define Timer_init(...) Timer_Timer_init(__VA_ARGS__)
/* @generated_from _2022x_1ad00ce_1659687960195_296841_3882 */ 
#define Timer_end(...) Timer_Timer_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */

/* Trigger functions declaration */
/* @generated_from _2022x_1ad00ce_1659683566715_850672_3426 */
/* @generated_from _2022x_1ad00ce_1659688287223_365621_4218 */  
void Cse_Trigger_opLight_Tick(Cse_Timer_Struct* instance);

/* Read functions declaration */
/* @generated_from _2022x_1ad00ce_1659683568410_618746_3444 */
/* @generated_from _2022x_1ad00ce_1659688230703_340985_4140 */
void Cse_Read_ipControl_On(Cse_Timer_Struct* instance, SignalEvent_On_type* msg);
/* @generated_from _2022x_1ad00ce_1659683568410_618746_3444 */
/* @generated_from _2022x_1ad00ce_1659688235695_364403_4143 */
void Cse_Read_ipControl_Off(Cse_Timer_Struct* instance, SignalEvent_Off_type* msg);
/* @generated_from _2022x_2_16600ad_1710516938469_985483_4880 */
/* @generated_from _2022x_2_16600ad_1710521616807_180606_4578 */
void Cse_Read_ipControl2_switchOff(Cse_Timer_Struct* instance, Boolean* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Trigger_opLight_Tick(inst) inst->Trigger_opLight_Tick()
#define Cse_Read_ipControl_On(inst, data) inst->Read_ipControl_On(data)
#define Cse_Read_ipControl_Off(inst, data) inst->Read_ipControl_Off(data)
#define Cse_Read_ipControl2_switchOff(inst, data) inst->Read_ipControl2_switchOff(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_TIMER_ITF_H */

/* end of file */
