/* @date 2025-03-04T06:13:23.815902586Z */

/**********************************************************************
 * @file Timer_Timer.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659687960195_296841_3882
 **********************************************************************/

/* Application code for statemachine "Timer" */

#include "Timer_Timer.h"
#include "Timer.h"

#define STATEMACHINE        Timer_struct

/**********************************************************************
 * Function Timer_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from _2022x_1ad00ce_1659687960195_296841_3882
 **********************************************************************/
static void Timer_struct_dtor(struct Timer_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function Timer_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from _2022x_1ad00ce_1659687960195_296841_3882
 **********************************************************************/
void Timer_struct_ctor(struct Timer_struct * const self, struct Timer* classifier) {
    /* Init pointer to destructor */
    self->dtor = Timer_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * separate code of user-modifiable functions to prevent accidental
 * changes to code above.
 **********************************************************************/
#include "Timer_Timer_usr.c"

/**********************************************************************
 * Function _basic_Timer_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659687960195_296841_3882
 **********************************************************************/
void _basic_Timer_init(Timer_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T)0;
    instance->CURRENT_STATE_0 = TIMER_STATE_T_VOID;

    instance->Ticking_Entry_Timer_Send_Tick.classifier = instance->classifier;
    _basic_Timer_Send_Tick_init(&(instance->Ticking_Entry_Timer_Send_Tick));

    StateMachine_init(instance);
}

/**********************************************************************
 * Function _basic_Timer
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659687960195_296841_3882
 **********************************************************************/
void _basic_Timer(Timer_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> off */
        /* @generated_from _2022x_1ad00ce_1659687960278_958645_3912 */
        instance->CURRENT_STATE_0 = TIMER_STATE_T_off;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State off */
        /* @generated_from _2022x_1ad00ce_1659687960278_832242_3911 */
        case TIMER_STATE_T_off: {
            if( instance->EVENT == TIMER_EVENT_T_On ) {
                /* Transition off -> Ticking */
                /* @generated_from _2022x_1ad00ce_1659687979397_223331_3933 */
                Ticking_Entry(instance); /* Entry Send Tick */
                instance->CURRENT_STATE_0 = TIMER_STATE_T_Ticking;
                instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
                instance->EVENT = TIMER_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of TIMER_STATE_T_off */
        }
        /* State Ticking */
        /* @generated_from _2022x_1ad00ce_1659687979394_415125_3932 */
        case TIMER_STATE_T_Ticking: {
            if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_0) >= (WALLCLOCK_T)1 ) {
                /* Transition Ticking -> Ticking */
                /* @generated_from _2022x_1ad00ce_1659688556921_32403_4312 */
                Ticking_Entry(instance); /* Entry Send Tick */
                instance->CURRENT_STATE_0 = TIMER_STATE_T_Ticking;
                instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
                instance->EVENT = TIMER_EVENT_T_NO_EVENT;
            } else if( instance->EVENT == TIMER_EVENT_T_Off ) {
                /* Transition Ticking -> off */
                /* @generated_from _2022x_1ad00ce_1659687987489_253426_3950 */
                instance->CURRENT_STATE_0 = TIMER_STATE_T_off;
                instance->EVENT = TIMER_EVENT_T_NO_EVENT;
            } else if( switchOff == true ) {
                /* Transition Ticking -> off */
                /* @generated_from _2022x_2_16600ad_1710521816028_84531_4642 */
                instance->CURRENT_STATE_0 = TIMER_STATE_T_off;
                instance->EVENT = TIMER_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of TIMER_STATE_T_Ticking */
        }
        default: break;
    } /* end of switch */
}

/**********************************************************************
 * Function _basic_Timer_end
 * Implements statemachine exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from _2022x_1ad00ce_1659687960195_296841_3882
 **********************************************************************/
void _basic_Timer_end(Timer_struct *instance) {
    StateMachine_end(instance);
}

/* end of file */
