/* @date 2025-03-04T06:13:23.875668738Z */

/**********************************************************************
 * @file Timer.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678985350_593051_3321
 **********************************************************************/

#ifndef TIMER_H
#define TIMER_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Timer_itf.h"
#include "Timer_internal_types.h"
#include "Timer_Timer.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from _2022x_1ad00ce_1659678985350_593051_3321 */	 
typedef struct Timer{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Timer*);

	/**
	 * @brief Public attribute for composition relation to Boolean:switchOff
	 * @generated_from _2022x_2_16600ad_1710521839298_640697_4658
	 */
	Boolean switchOff;
		
	/**
	 * Data for Behavior Timer
	 * @generated_from _2022x_1ad00ce_1659687960195_296841_3882
	 */
	Timer_struct Timer;

	/**********************************************************************
	 * Communication Interface section
	 **********************************************************************/
	/**
	 * Communication interface
	 * @generated_from _2022x_1ad00ce_1659678985350_593051_3321
	 */
	Cse_Timer_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Timer;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_1ad00ce_1659678985350_593051_3321
 */
void Timer_ctor(Timer* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef TIMER_H

/* end of file */