/* @date 2025-03-04T06:13:23.822749390Z */

/**********************************************************************
 * @file Timer_Timer_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659687960195_296841_3882
 **********************************************************************/

#ifdef STATEMACHINE

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define ipControl2_switchOff    instance->ipControl2_switchOff
#define ipControl2              ipControl2_switchOff
#define switchOff               instance->classifier->switchOff

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Function Ticking_Entry
 * Implements "Entry" of State: Ticking
 * Entry calls Activity: Send Tick
 *
 * @generated_from _2022x_1ad00ce_1659687979394_415125_3932
 * @generated_from _2022x_1ad00ce_1659689071378_428346_4514
 **********************************************************************/
static void Ticking_Entry(Timer_struct *instance) {
    /* BEG_USER_CODE(Entry_2022x_1ad00ce_1659687979394_415125_3932) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    instance->DONE_ACTIVITY = _basic_Timer_Send_Tick(&(instance->Ticking_Entry_Timer_Send_Tick));

    /* END_USER_CODE(Entry_2022x_1ad00ce_1659687979394_415125_3932) do not remove */
}

static void StateMachine_init(Timer_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(init_state_machine) do not remove */
}

static void StateMachine_end(Timer_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */
    _basic_Timer_Send_Tick_end(&(instance->Ticking_Entry_Timer_Send_Tick));

    /* END_USER_CODE(end_state_machine) do not remove */
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

#endif /* STATEMACHINE */
/* end of file */
