/* @date 2025-03-04T06:13:23.879488070Z */

/**********************************************************************
 * @file Timer.c
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from _2022x_1ad00ce_1659678985350_593051_3321
 **********************************************************************/

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include <stddef.h> // NULL
#include "Timer.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */


/* Function pointer to destructor function generated automatically */
static void Timer_dtor(struct Timer* self){
	/* Call hierarchical destructors */
	self->Timer.dtor(&self->Timer);

	/* Clean pointer to destructor */
	self->dtor = NULL;
}

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from _2022x_1ad00ce_1659678985350_593051_3321
 */
void Timer_ctor(Timer* self){
	/* Init pointer to destructor */
	self->dtor = Timer_dtor;

	/* Default values */

	/* Configure Communication Interface */
	self->cse_itf.parent = self;

	/* Call hierarchical constructors */
	Timer_struct_ctor(&self->Timer, self);
}
/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */