/* @date 2025-03-27T11:04:29.659618406Z */

/**********************************************************************
 * @file Button_type.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from 6a9507e5-fe18-4fdc-b0ff-a7818ecd76a2
 **********************************************************************/

#ifndef BUTTON_TYPE_H
#define BUTTON_TYPE_H

#include <stddef.h>
/* stdbool.h define standard bool (true/false) starting from C99 standard */ 
#include <stdbool.h>

/**********************************************************************
 * Data Type trigger_type definition
 **********************************************************************/
#ifndef trigger_type_DEFINITION
#define trigger_type_DEFINITION
typedef bool trigger_type;
#endif /* trigger_type */

/**********************************************************************
 * Data Type SignalEvent_On_type definition
 **********************************************************************/
#ifndef SignalEvent_On_type_DEFINITION
#define SignalEvent_On_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_On_type;
#endif /* SignalEvent_On_type */

/**********************************************************************
 * Data Type SignalEvent_Off_type definition
 **********************************************************************/
#ifndef SignalEvent_Off_type_DEFINITION
#define SignalEvent_Off_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_Off_type;
#endif /* SignalEvent_Off_type */

/**********************************************************************
 * Data Type Boolean definition
 **********************************************************************/
#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool Boolean;
#endif /* Boolean */

#endif /* BUTTON_TYPE_H */

/* end of file */
