/* @date 2025-03-27T11:04:29.645270532Z */

/**********************************************************************
 * @file Button_Button_Send_Off.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 713d0110-19f6-4220-8bca-b45dbcdb0c60
 **********************************************************************/

/* Application code for activity "Send Off" */

#include "Button_Button_Send_Off.h"

#include "Button.h"
#include <string.h>
/**********************************************************************
 * handy helpers
 **********************************************************************/
#define button_button           instance->button_button
#define button                  button_button
#define pinData                 instance->classifier->pinData

/**********************************************************************
 * default event handlers
 **********************************************************************/
// cppcheck-suppress constParameterCallback
static BUTTON_SEND_OFF_EVENT_T default_peekEvent(Button_Send_Off_struct *instance) {
    return instance->EVENT;
}
static BUTTON_SEND_OFF_EVENT_T default_nextEvent(Button_Send_Off_struct *instance) {
    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    return BUTTON_SEND_OFF_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent(Button_Send_Off_struct *instance, BUTTON_SEND_OFF_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == BUTTON_SEND_OFF_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************
 * helpers
 **********************************************************************/
static inline Boolean isRunning(const Button_Send_Off_struct* const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************
 * Function Button_Send_Off_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from 713d0110-19f6-4220-8bca-b45dbcdb0c60
 **********************************************************************/
static void Button_Send_Off_struct_dtor(struct Button_Send_Off_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function Button_Send_Off_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 713d0110-19f6-4220-8bca-b45dbcdb0c60
 **********************************************************************/
void Button_Send_Off_struct_ctor(struct Button_Send_Off_struct * const self, struct Button* classifier) {
    /* Init pointer to destructor */
    self->dtor = Button_Send_Off_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * Function _basic_Button_Send_Off_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 713d0110-19f6-4220-8bca-b45dbcdb0c60
 **********************************************************************/
void _basic_Button_Send_Off_init(Button_Send_Off_struct *instance) {
    if(instance->peekEVENT == NULL) {instance->peekEVENT = default_peekEvent;}
    if(instance->nextEVENT == NULL) {instance->nextEVENT = default_nextEvent;}
    if(instance->sendEVENT == NULL) {instance->sendEVENT = default_sendEvent;}
    instance->EVENT = BUTTON_SEND_OFF_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));

    instance->WALL_CLOCK        = (WALLCLOCK_T)0;


    // TODO how to assign events functions
    // instance->node_2_Model_Functions_Send_Off.peekEVENT = instance->peekEVENT;
    // instance->node_2_Model_Functions_Send_Off.nextEVENT = instance->nextEVENT;
    // instance->node_2_Model_Functions_Send_Off.sendEVENT = instance->sendEVENT;
    instance->node_2_Model_Functions_Send_Off.classifier = instance->classifier;
    _basic_Model_Functions_Send_Off_init(&(instance->node_2_Model_Functions_Send_Off));
}

/**********************************************************************
 * Function _basic_Button_Send_Off
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 713d0110-19f6-4220-8bca-b45dbcdb0c60
 **********************************************************************/
Boolean _basic_Button_Send_Off(Button_Send_Off_struct *instance) {
    /* initialization */
    if(isRunning(instance) == FALSE) {
        instance->flow[0] = 1u; /* SET_FLOW->CallBehaviorAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node CallBehaviorAction */
    /* @generated_from e88f8b22-fc8a-44f1-85a9-6063979644cb */
    if(1u == (instance->flow[0] & 1u)) { /* TST_FLOW<-InitialNode */
        Boolean success;
        success = _basic_Model_Functions_Send_Off(&(instance->node_2_Model_Functions_Send_Off));
        if(success != FALSE) {
            instance->flow[0] ^= 1u; /* CLR_FLOW<-InitialNode */
            instance->flow[0] |= 2u; /* SET_FLOW->ActivityFinalNode */
        }
    }
    /* node ActivityFinalNode */
    /* @generated_from 53cf2d1d-cb20-4a8e-a523-63f7f9d32cf0 */
    if(2u == (instance->flow[0] & 2u)) { /* TST_FLOW<-CallBehaviorAction */
        (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));
    }

    return (FALSE == isRunning(instance)) ? TRUE : FALSE;
}

/**********************************************************************
 * Function _basic_Button_Send_Off_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from 713d0110-19f6-4220-8bca-b45dbcdb0c60
 **********************************************************************/
void _basic_Button_Send_Off_end(Button_Send_Off_struct *instance) {
    _basic_Model_Functions_Send_Off_end(&(instance->node_2_Model_Functions_Send_Off));
}

/* end of file */
