/* @date 2025-03-27T11:04:29.658773211Z */

/**********************************************************************
 * @file Button_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from 6a9507e5-fe18-4fdc-b0ff-a7818ecd76a2
 **********************************************************************/

#ifndef CSE_BUTTON_ITF_H
#define CSE_BUTTON_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Button_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* Trigger functions */
	/* @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08 */
	/* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */  
	void (*Trigger_control_On)(void);
	/* @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08 */
	/* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */  
	void (*Trigger_control_Off)(void);
	/* Read functions */
	/* @generated_from 6d305e60-ceb8-4426-8b00-1e85f8fa3445 */
	/* @generated_from ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21 */  
	void (*Read_button_button)(Boolean* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Button *parent;
}Cse_Button_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from 5441d506-e192-4fde-9759-894d27006756 */ 
void Button_Button_init(Cse_Button_Struct* self);
void Button_Button(Cse_Button_Struct* instance);
void Button_Button_end(Cse_Button_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from 5441d506-e192-4fde-9759-894d27006756 */ 
#define Button(...) Button_Button(__VA_ARGS__)
/* @generated_from 5441d506-e192-4fde-9759-894d27006756 */ 
#define Button_init(...) Button_Button_init(__VA_ARGS__)
/* @generated_from 5441d506-e192-4fde-9759-894d27006756 */ 
#define Button_end(...) Button_Button_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */

/* Trigger functions declaration */
/* @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08 */
/* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */  
void Cse_Trigger_control_On(Cse_Button_Struct* instance);
/* @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08 */
/* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */  
void Cse_Trigger_control_Off(Cse_Button_Struct* instance);

/* Read functions declaration */
/* @generated_from 6d305e60-ceb8-4426-8b00-1e85f8fa3445 */
/* @generated_from ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21 */
void Cse_Read_button_button(Cse_Button_Struct* instance, Boolean* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Trigger_control_On(inst) inst->Trigger_control_On()
#define Cse_Trigger_control_Off(inst) inst->Trigger_control_Off()
#define Cse_Read_button_button(inst, data) inst->Read_button_button(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_BUTTON_ITF_H */

/* end of file */
