/* @date 2025-03-27T11:04:29.658406297Z */

/**********************************************************************
 * @file Button_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from 6a9507e5-fe18-4fdc-b0ff-a7818ecd76a2
 **********************************************************************/

#include "Button.h"
#include "Button_itf.h"
#include "Button_Button.h"
#include "Tal.h" // tal_getTime

/**********************************************************************
 * Init function invoked for component initialization purpose.
 **********************************************************************/
void Button_init(Cse_Button_Struct* inst) {
    /* Get component Button from "parent" */
    Button *pButton = inst->parent;

    /* Get behavior button from the Button */
    Button_struct *button = &pButton->Button;


    /* Initialization job which can be done in a separated function or inlined. */
    _basic_Button_init(button);
}

/**********************************************************************
 * Main function Body of behavior "Button"
 **********************************************************************/
void Button(Cse_Button_Struct* inst) {
    /* Get component Button from "parent" */
    Button *pButton = inst->parent;

    /* Get behavior button from the Button */
    Button_struct *button = &pButton->Button;

    /* read input(s) */
    Cse_Read_button_button(inst, &button->button_button);

    /* update WALL_CLOCK */
    button->WALL_CLOCK = tal_GetTime();
    button->on_Effect_Button_Send_Off.WALL_CLOCK = tal_GetTime();
    button->on_Effect_Button_Send_Off.node_2_Model_Functions_Send_Off.WALL_CLOCK = tal_GetTime();
    button->on_Entry_Button_Send_On.WALL_CLOCK = tal_GetTime();
    button->on_Entry_Button_Send_On.node_2_Model_Functions_Send_On.WALL_CLOCK = tal_GetTime();

    /* Copy data in */
    pButton->pinData = button->button_button;

    (void)_basic_Button(button);

    /* trigger event(s) */
    if (button->on_Entry_Button_Send_On.node_2_Model_Functions_Send_On.EVENT == MODEL_FUNCTIONS_SEND_ON_EVENT_T_On) {
        button->on_Entry_Button_Send_On.node_2_Model_Functions_Send_On.EVENT = MODEL_FUNCTIONS_SEND_ON_EVENT_T_NO_EVENT;
        Cse_Trigger_control_On(inst);
    }
    if (button->on_Effect_Button_Send_Off.node_2_Model_Functions_Send_Off.EVENT == MODEL_FUNCTIONS_SEND_OFF_EVENT_T_Off) \
        {
        button->on_Effect_Button_Send_Off.node_2_Model_Functions_Send_Off.EVENT = MODEL_FUNCTIONS_SEND_OFF_EVENT_T_NO_EVENT;
        Cse_Trigger_control_Off(inst);
    }
}

/**********************************************************************
 * Exit function invoked at execution ending
 **********************************************************************/
void Button_end(Cse_Button_Struct* inst) {
    /* Get component Button from "parent" */
    Button *pButton = inst->parent;

    /* Get behavior button from the Button */
    Button_struct *button = &pButton->Button;

    _basic_Button_end(button);
}

/* end of file */
