/* @date 2025-03-27T11:04:29.667094695Z */

/**********************************************************************
 * @file Button.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from 6a9507e5-fe18-4fdc-b0ff-a7818ecd76a2
 **********************************************************************/

#ifndef BUTTON_H
#define BUTTON_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Button_itf.h"
#include "Button_internal_types.h"
#include "Button_Button.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from 6a9507e5-fe18-4fdc-b0ff-a7818ecd76a2 */	 
typedef struct Button{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Button*);

	/**
	 * @brief Public attribute for composition relation to Boolean:pinData
	 * @generated_from 059788ae-6589-4061-ad01-8edf2e212afd
	 */
	Boolean pinData;
		
	/**
	 * Data for Behavior Button
	 * @generated_from 5441d506-e192-4fde-9759-894d27006756
	 */
	Button_struct Button;

	/**********************************************************************
	 * Communication Interface section
	 **********************************************************************/
	/**
	 * Communication interface
	 * @generated_from 6a9507e5-fe18-4fdc-b0ff-a7818ecd76a2
	 */
	Cse_Button_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Button;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 6a9507e5-fe18-4fdc-b0ff-a7818ecd76a2
 */
void Button_ctor(Button* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef BUTTON_H

/* end of file */