/* @date 2025-03-27T11:04:29.637149603Z */

/**********************************************************************
 * @file Button_Button_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 5441d506-e192-4fde-9759-894d27006756
 **********************************************************************/

#ifdef STATEMACHINE

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define button_button   instance->button_button
#define button          button_button
#define pinData         instance->classifier->pinData

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Function on_Effect
 * Implements Effect of Transition between States: on -> off
 * Effect calls Activity: Send Off
 *
 * @generated_from a42b5975-be62-4844-a57c-b41b5af3f4d7
 * @generated_from 713d0110-19f6-4220-8bca-b45dbcdb0c60
 **********************************************************************/
static void on_Effect(Button_struct *instance) {
    /* BEG_USER_CODE(Effecta42b5975-be62-4844-a57c-b41b5af3f4d7) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    instance->DONE_ACTIVITY = _basic_Button_Send_Off(&(instance->on_Effect_Button_Send_Off));

    /* END_USER_CODE(Effecta42b5975-be62-4844-a57c-b41b5af3f4d7) do not remove */
}

/**********************************************************************
 * Function on_Entry
 * Implements "Entry" of State: on
 * Entry calls Activity: Send On
 *
 * @generated_from a494b83c-7c33-4230-be7c-28d8319ce1ec
 * @generated_from 6414a6e2-b1c5-49c6-af71-af964e1571ea
 **********************************************************************/
static void on_Entry(Button_struct *instance) {
    /* BEG_USER_CODE(Entrya494b83c-7c33-4230-be7c-28d8319ce1ec) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    instance->DONE_ACTIVITY = _basic_Button_Send_On(&(instance->on_Entry_Button_Send_On));

    /* END_USER_CODE(Entrya494b83c-7c33-4230-be7c-28d8319ce1ec) do not remove */
}

static void StateMachine_init(Button_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(init_state_machine) do not remove */
}

static void StateMachine_end(Button_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */
    _basic_Button_Send_Off_end(&(instance->on_Effect_Button_Send_Off));
    _basic_Button_Send_On_end(&(instance->on_Entry_Button_Send_On));

    /* END_USER_CODE(end_state_machine) do not remove */
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

#endif /* STATEMACHINE */
/* end of file */
