/* @date 2025-03-27T11:04:29.678784257Z */

/**********************************************************************
 * @file Counter_type.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from ff38d222-721b-4155-939a-53cc5314f361
 **********************************************************************/

#ifndef COUNTER_TYPE_H
#define COUNTER_TYPE_H

#include <stddef.h>
/* stdbool.h define standard bool (true/false) starting from C99 standard */ 
#include <stdbool.h>

/**********************************************************************
 * Data Type Boolean definition
 **********************************************************************/
#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool Boolean;
#endif /* Boolean */

/**********************************************************************
 * Data Type Integer definition
 **********************************************************************/
#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int Integer;
#endif /* Integer */

#endif /* COUNTER_TYPE_H */

/* end of file */
