/* @date 2025-03-27T11:04:29.675822463Z */

/**********************************************************************
 * @file Counter_OB_cnt.c
 *
 * Automatically generated by Software Producer Engineer
 * UML Opaque Behavior C/C++ Code Generator @version v1.0.0
 *
 * @generated_from 5ebedd3f-e615-4b53-9693-452939456a6b
 **********************************************************************/
#include "Counter.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**
 * Start of Opaque Behavior OB_cnt body section
 * @generated_from 5ebedd3f-e615-4b53-9693-452939456a6b
 */

/* BEG_USER_CODE(5ebedd3f-e615-4b53-9693-452939456a6b) do not remove */

#include <stdio.h>
	
	//Local
	static int counter;
	static Boolean cntEnb;

void OB_cnt_init(Cse_Counter_Struct* inst){
	(void)inst;
	//Parameter
	counter = 0;
	cntEnb = true;
}

void OB_cnt(Cse_Counter_Struct* inst){
	//printf(" Counting..\n");

	//Input
	Boolean countin = FALSE;

	//Output
	
	//Local
	
	/*******  Cse read *****/
	Cse_Read_ipLight_light(inst, &countin);
	
	/*******  Definition *****/

	if ((countin ==true) && (cntEnb ==true)) {
		counter++;
		(void)printf("Light ON Count is : %d \n", counter);
		cntEnb =false;
	}
	if (countin ==false) {
		cntEnb = true;
	}
		
	/*******  Cse write *****/
	Cse_Write_opCounts_data(inst, &counter);
}

void OB_cnt_term(Cse_Counter_Struct* inst){
	(void)inst;
}


/* END_USER_CODE(5ebedd3f-e615-4b53-9693-452939456a6b) do not remove */
/* End of Opaque Behavior OB_cnt body section */

/* end of file */