/* @date 2025-03-27T11:04:29.689365490Z */

/************************************************
 * @file Counter_internal_types.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from ff38d222-721b-4155-939a-53cc5314f361
 ***********************************************/

#ifndef COUNTER_INTERNAL_TYPES_H
#define COUNTER_INTERNAL_TYPES_H

#include <stdbool.h>


/**********************************************************************
 * Data Types used in statemachines and activities definition
 **********************************************************************/

#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool    Boolean;
#endif

#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int     Integer;
#endif

#ifndef Real_DEFINITION
#define Real_DEFINITION
typedef double   Real;
#endif

#ifndef String_DEFINITION
#define String_DEFINITION
typedef char *  String;
#endif

#ifndef TRUE
#define TRUE    true
#endif

#ifndef FALSE
#define FALSE   false
#endif

#endif //#ifndef COUNTER_INTERNAL_TYPES_H

/* end of file */