/* @date 2025-03-27T11:04:29.678256196Z */

/**********************************************************************
 * @file Counter_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from ff38d222-721b-4155-939a-53cc5314f361
 **********************************************************************/

#ifndef CSE_COUNTER_ITF_H
#define CSE_COUNTER_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Counter_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673 */
	/* @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673 */	
	void (*Write_opCounts_data)(Integer* msg);
	/* Trigger functions */
	/* Read functions */
	/* @generated_from c027c956-bc59-467c-a000-446044b609e3 */
	/* @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5 */  
	void (*Read_ipLight_light)(Boolean* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Counter *parent;
}Cse_Counter_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from 5ebedd3f-e615-4b53-9693-452939456a6b */ 
void Counter_OB_cnt_init(Cse_Counter_Struct* self);
void Counter_OB_cnt(Cse_Counter_Struct* instance);
void Counter_OB_cnt_end(Cse_Counter_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from 5ebedd3f-e615-4b53-9693-452939456a6b */ 
#define OB_cnt(...) Counter_OB_cnt(__VA_ARGS__)
/* @generated_from 5ebedd3f-e615-4b53-9693-452939456a6b */ 
#define OB_cnt_init(...) Counter_OB_cnt_init(__VA_ARGS__)
/* @generated_from 5ebedd3f-e615-4b53-9693-452939456a6b */ 
#define OB_cnt_end(...) Counter_OB_cnt_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */
/* @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673 */
/* @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673 */	
void Cse_Write_opCounts_data(Cse_Counter_Struct* instance, Integer* msg);

/* Trigger functions declaration */

/* Read functions declaration */
/* @generated_from c027c956-bc59-467c-a000-446044b609e3 */
/* @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5 */
void Cse_Read_ipLight_light(Cse_Counter_Struct* instance, Boolean* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Read_ipLight_light(inst, data) inst->Read_ipLight_light(data)
#define Cse_Write_opCounts_data(inst, data) inst->Write_opCounts_data(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_COUNTER_ITF_H */

/* end of file */
