/* @date 2025-03-27T11:04:29.683341939Z */

/**********************************************************************
 * @file Counter.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from ff38d222-721b-4155-939a-53cc5314f361
 **********************************************************************/

#ifndef COUNTER_H
#define COUNTER_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Counter_itf.h"
#include "Counter_internal_types.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from ff38d222-721b-4155-939a-53cc5314f361 */	 
typedef struct Counter{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Counter*);

	/**********************************************************************
	 * Communication Interface section
	 **********************************************************************/
	/**
	 * Communication interface
	 * @generated_from ff38d222-721b-4155-939a-53cc5314f361
	 */
	Cse_Counter_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Counter;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from ff38d222-721b-4155-939a-53cc5314f361
 */
void Counter_ctor(Counter* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef COUNTER_H

/* end of file */