/* @date 2025-03-27T11:04:29.677906909Z */

/**********************************************************************
 * @file Counter_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from ff38d222-721b-4155-939a-53cc5314f361
 **********************************************************************/

#include "Counter.h"
#include "Counter_itf.h"
#include "Tal.h" // tal_getTime

/* end of file */
