/* @date 2025-03-27T11:04:29.350259067Z */

/**********************************************************************
 * @file Cse_Flashlight_hook_usr.c
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 *
 * @generated_from 28cbcdad-312a-495d-9ce1-2d3c79f29110
 **********************************************************************/

/*
 * define symbol USER_HOOKS to enable this file content on compiler 
 * command or uncomment following line
 */
/* #define USER_HOOKS */
#ifdef USER_HOOKS

#include "Cse_cfg.h"

#ifdef __cplusplus
// Code is compiled as C code even if the file is a cpp file
extern "C" {
#endif /* __cplusplus */

/* BEG_USER_CODE(HEADER) do not remove */
/* Add your includes here */
/* END_USER_CODE(HEADER) do not remove */

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl_On_Start
 * Start Hook to be overwritten to read On value on ipControl port
 * @generated_from 644c256e-801e-46df-be80-219fec881e01
 * @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8
*/
void Cse_ReadHook_Flashlight_timer_ipControl_On_Start(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(644c256e-801e-46df-be80-219fec881e01_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(644c256e-801e-46df-be80-219fec881e01_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl_On_Return
 * Return Hook to be overwritten to read On value on ipControl port
 * @generated_from 644c256e-801e-46df-be80-219fec881e01
 * @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8
*/
void Cse_ReadHook_Flashlight_timer_ipControl_On_Return(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(644c256e-801e-46df-be80-219fec881e01_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(644c256e-801e-46df-be80-219fec881e01_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl_Off_Start
 * Start Hook to be overwritten to read Off value on ipControl port
 * @generated_from 644c256e-801e-46df-be80-219fec881e01
 * @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555
*/
void Cse_ReadHook_Flashlight_timer_ipControl_Off_Start(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(644c256e-801e-46df-be80-219fec881e01_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(644c256e-801e-46df-be80-219fec881e01_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl_Off_Return
 * Return Hook to be overwritten to read Off value on ipControl port
 * @generated_from 644c256e-801e-46df-be80-219fec881e01
 * @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555
*/
void Cse_ReadHook_Flashlight_timer_ipControl_Off_Return(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(644c256e-801e-46df-be80-219fec881e01_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(644c256e-801e-46df-be80-219fec881e01_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_light_ipTimer_Tick_Start
 * Start Hook to be overwritten to read Tick value on ipTimer port
 * @generated_from e74c94e1-684b-4aec-a446-57b7eff8b9e6
 * @generated_from 223688c0-a48b-4d23-8f87-d869296ad962
*/
void Cse_ReadHook_Flashlight_light_ipTimer_Tick_Start(SignalEvent_Tick_type* pData){
	/* BEG_USER_CODE(e74c94e1-684b-4aec-a446-57b7eff8b9e6_223688c0-a48b-4d23-8f87-d869296ad962) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e74c94e1-684b-4aec-a446-57b7eff8b9e6_223688c0-a48b-4d23-8f87-d869296ad962) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_light_ipTimer_Tick_Return
 * Return Hook to be overwritten to read Tick value on ipTimer port
 * @generated_from e74c94e1-684b-4aec-a446-57b7eff8b9e6
 * @generated_from 223688c0-a48b-4d23-8f87-d869296ad962
*/
void Cse_ReadHook_Flashlight_light_ipTimer_Tick_Return(SignalEvent_Tick_type* pData){
	/* BEG_USER_CODE(e74c94e1-684b-4aec-a446-57b7eff8b9e6_223688c0-a48b-4d23-8f87-d869296ad962) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e74c94e1-684b-4aec-a446-57b7eff8b9e6_223688c0-a48b-4d23-8f87-d869296ad962) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_control_On_Start
 * Start Hook to be overwritten to read On value on control port
 * @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6
 * @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8
*/
void Cse_ReadHook_Flashlight_tempoManager_control_On_Start(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_control_On_Return
 * Return Hook to be overwritten to read On value on control port
 * @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6
 * @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8
*/
void Cse_ReadHook_Flashlight_tempoManager_control_On_Return(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_control_Off_Start
 * Start Hook to be overwritten to read Off value on control port
 * @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6
 * @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555
*/
void Cse_ReadHook_Flashlight_tempoManager_control_Off_Start(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_control_Off_Return
 * Return Hook to be overwritten to read Off value on control port
 * @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6
 * @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555
*/
void Cse_ReadHook_Flashlight_tempoManager_control_Off_Return(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_onCount_ipLight_light_Start
 * Start Hook to be overwritten to read light value on ipLight port
 * @generated_from c027c956-bc59-467c-a000-446044b609e3
 * @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5
*/
void Cse_ReadHook_Flashlight_onCount_ipLight_light_Start(Boolean* pData){
	/* BEG_USER_CODE(c027c956-bc59-467c-a000-446044b609e3_638296ee-eff2-47cf-a528-78cb187ad4e5) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c027c956-bc59-467c-a000-446044b609e3_638296ee-eff2-47cf-a528-78cb187ad4e5) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_onCount_ipLight_light_Return
 * Return Hook to be overwritten to read light value on ipLight port
 * @generated_from c027c956-bc59-467c-a000-446044b609e3
 * @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5
*/
void Cse_ReadHook_Flashlight_onCount_ipLight_light_Return(Boolean* pData){
	/* BEG_USER_CODE(c027c956-bc59-467c-a000-446044b609e3_638296ee-eff2-47cf-a528-78cb187ad4e5) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c027c956-bc59-467c-a000-446044b609e3_638296ee-eff2-47cf-a528-78cb187ad4e5) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Start
 * Start Hook to be overwritten to read switchOff value on ipControl2 port
 * @generated_from 42060ef5-7bab-484c-989e-8eec5da359e0
 * @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a
*/
void Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Start(Boolean* pData){
	/* BEG_USER_CODE(42060ef5-7bab-484c-989e-8eec5da359e0_ce8eef98-3abd-48d2-acb6-4458d9a2a56a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(42060ef5-7bab-484c-989e-8eec5da359e0_ce8eef98-3abd-48d2-acb6-4458d9a2a56a) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Return
 * Return Hook to be overwritten to read switchOff value on ipControl2 port
 * @generated_from 42060ef5-7bab-484c-989e-8eec5da359e0
 * @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a
*/
void Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Return(Boolean* pData){
	/* BEG_USER_CODE(42060ef5-7bab-484c-989e-8eec5da359e0_ce8eef98-3abd-48d2-acb6-4458d9a2a56a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(42060ef5-7bab-484c-989e-8eec5da359e0_ce8eef98-3abd-48d2-acb6-4458d9a2a56a) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_button_button_button_Start
 * Start Hook to be overwritten to read button value on button port
 * @generated_from 6d305e60-ceb8-4426-8b00-1e85f8fa3445
 * @generated_from ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21
*/
void Cse_ReadHook_Flashlight_button_button_button_Start(Boolean* pData){
	/* BEG_USER_CODE(6d305e60-ceb8-4426-8b00-1e85f8fa3445_ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(6d305e60-ceb8-4426-8b00-1e85f8fa3445_ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_button_button_button_Return
 * Return Hook to be overwritten to read button value on button port
 * @generated_from 6d305e60-ceb8-4426-8b00-1e85f8fa3445
 * @generated_from ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21
*/
void Cse_ReadHook_Flashlight_button_button_button_Return(Boolean* pData){
	/* BEG_USER_CODE(6d305e60-ceb8-4426-8b00-1e85f8fa3445_ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(6d305e60-ceb8-4426-8b00-1e85f8fa3445_ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Start
 * Start Hook to be overwritten to read button value on ipTempo port
 * @generated_from 107d9c5c-35fc-4298-9679-81ed2cf3efa0
 * @generated_from 45a985c7-ac8d-4418-9e46-2b7cf0867b32
*/
void Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Start(Integer* pData){
	/* BEG_USER_CODE(107d9c5c-35fc-4298-9679-81ed2cf3efa0_45a985c7-ac8d-4418-9e46-2b7cf0867b32) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(107d9c5c-35fc-4298-9679-81ed2cf3efa0_45a985c7-ac8d-4418-9e46-2b7cf0867b32) do not remove */
}

/**
 * Function Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Return
 * Return Hook to be overwritten to read button value on ipTempo port
 * @generated_from 107d9c5c-35fc-4298-9679-81ed2cf3efa0
 * @generated_from 45a985c7-ac8d-4418-9e46-2b7cf0867b32
*/
void Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Return(Integer* pData){
	/* BEG_USER_CODE(107d9c5c-35fc-4298-9679-81ed2cf3efa0_45a985c7-ac8d-4418-9e46-2b7cf0867b32) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(107d9c5c-35fc-4298-9679-81ed2cf3efa0_45a985c7-ac8d-4418-9e46-2b7cf0867b32) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_light_opLight_light_Start
 * Start hook to be overwritten to send light value on opLight port
 * @generated_from 48b8db33-57a9-4f78-a9c3-ed492905f3ae
 * @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5
 */
void Cse_WriteHook_Flashlight_light_opLight_light_Start(Boolean* pData){
	/* BEG_USER_CODE(48b8db33-57a9-4f78-a9c3-ed492905f3ae_638296ee-eff2-47cf-a528-78cb187ad4e5) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(48b8db33-57a9-4f78-a9c3-ed492905f3ae_638296ee-eff2-47cf-a528-78cb187ad4e5) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_light_opLight_light_Return
 * Return hook to be overwritten to send light value on opLight port
 * @generated_from 48b8db33-57a9-4f78-a9c3-ed492905f3ae
 * @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5
 */
void Cse_WriteHook_Flashlight_light_opLight_light_Return(Boolean* pData){
	/* BEG_USER_CODE(48b8db33-57a9-4f78-a9c3-ed492905f3ae_638296ee-eff2-47cf-a528-78cb187ad4e5) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(48b8db33-57a9-4f78-a9c3-ed492905f3ae_638296ee-eff2-47cf-a528-78cb187ad4e5) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_onCount_opCounts_data_Start
 * Start hook to be overwritten to send data value on opCounts port
 * @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673
 * @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673
 */
void Cse_WriteHook_Flashlight_onCount_opCounts_data_Start(Integer* pData){
	/* BEG_USER_CODE(f7b0b053-71a4-4f90-a8fc-bf0bae341673_f7b0b053-71a4-4f90-a8fc-bf0bae341673) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(f7b0b053-71a4-4f90-a8fc-bf0bae341673_f7b0b053-71a4-4f90-a8fc-bf0bae341673) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_onCount_opCounts_data_Return
 * Return hook to be overwritten to send data value on opCounts port
 * @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673
 * @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673
 */
void Cse_WriteHook_Flashlight_onCount_opCounts_data_Return(Integer* pData){
	/* BEG_USER_CODE(f7b0b053-71a4-4f90-a8fc-bf0bae341673_f7b0b053-71a4-4f90-a8fc-bf0bae341673) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(f7b0b053-71a4-4f90-a8fc-bf0bae341673_f7b0b053-71a4-4f90-a8fc-bf0bae341673) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Start
 * Start hook to be overwritten to send switchOff value on opControl port
 * @generated_from 0c123f41-f825-4736-a34f-e120a337f4cd
 * @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a
 */
void Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Start(Boolean* pData){
	/* BEG_USER_CODE(0c123f41-f825-4736-a34f-e120a337f4cd_ce8eef98-3abd-48d2-acb6-4458d9a2a56a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(0c123f41-f825-4736-a34f-e120a337f4cd_ce8eef98-3abd-48d2-acb6-4458d9a2a56a) do not remove */
}

/**
 * Function Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Return
 * Return hook to be overwritten to send switchOff value on opControl port
 * @generated_from 0c123f41-f825-4736-a34f-e120a337f4cd
 * @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a
 */
void Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Return(Boolean* pData){
	/* BEG_USER_CODE(0c123f41-f825-4736-a34f-e120a337f4cd_ce8eef98-3abd-48d2-acb6-4458d9a2a56a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(0c123f41-f825-4736-a34f-e120a337f4cd_ce8eef98-3abd-48d2-acb6-4458d9a2a56a) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_timer_opLight_Tick_Start
 * Start hook to be overwritten to Trigger Tick on opLight port
 * @generated_from 38b48e8e-9edb-4f25-8030-d2e76166b1ca
 * @generated_from 223688c0-a48b-4d23-8f87-d869296ad962
 */
void Cse_TriggerHook_Flashlight_timer_opLight_Tick_Start(SignalEvent_Tick_type* pData){
	/* BEG_USER_CODE(38b48e8e-9edb-4f25-8030-d2e76166b1ca_223688c0-a48b-4d23-8f87-d869296ad962) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38b48e8e-9edb-4f25-8030-d2e76166b1ca_223688c0-a48b-4d23-8f87-d869296ad962) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_timer_opLight_Tick_Return
 * Return hook to be overwritten to Trigger Tick on opLight port
 * @generated_from 38b48e8e-9edb-4f25-8030-d2e76166b1ca
 * @generated_from 223688c0-a48b-4d23-8f87-d869296ad962
 */
void Cse_TriggerHook_Flashlight_timer_opLight_Tick_Return(SignalEvent_Tick_type* pData){
	/* BEG_USER_CODE(38b48e8e-9edb-4f25-8030-d2e76166b1ca_223688c0-a48b-4d23-8f87-d869296ad962) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38b48e8e-9edb-4f25-8030-d2e76166b1ca_223688c0-a48b-4d23-8f87-d869296ad962) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_button_control_On_Start
 * Start hook to be overwritten to Trigger On on control port
 * @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08
 * @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8
 */
void Cse_TriggerHook_Flashlight_button_control_On_Start(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(c2410e8a-16aa-4fd7-946d-af43b985ba08_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c2410e8a-16aa-4fd7-946d-af43b985ba08_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_button_control_On_Return
 * Return hook to be overwritten to Trigger On on control port
 * @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08
 * @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8
 */
void Cse_TriggerHook_Flashlight_button_control_On_Return(SignalEvent_On_type* pData){
	/* BEG_USER_CODE(c2410e8a-16aa-4fd7-946d-af43b985ba08_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c2410e8a-16aa-4fd7-946d-af43b985ba08_94cdab86-41e8-4eb5-89b1-271590a97ab8) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_button_control_Off_Start
 * Start hook to be overwritten to Trigger Off on control port
 * @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08
 * @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555
 */
void Cse_TriggerHook_Flashlight_button_control_Off_Start(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(c2410e8a-16aa-4fd7-946d-af43b985ba08_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c2410e8a-16aa-4fd7-946d-af43b985ba08_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
}

/**
 * Function Cse_TriggerHook_Flashlight_button_control_Off_Return
 * Return hook to be overwritten to Trigger Off on control port
 * @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08
 * @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555
 */
void Cse_TriggerHook_Flashlight_button_control_Off_Return(SignalEvent_Off_type* pData){
	/* BEG_USER_CODE(c2410e8a-16aa-4fd7-946d-af43b985ba08_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c2410e8a-16aa-4fd7-946d-af43b985ba08_ec8bda96-4321-4ebc-a6bf-11d724651555) do not remove */
}


#ifdef __cplusplus
}
#endif /* __cplusplus */

/* BEG_USER_CODE(FOOTER) do not remove */
/* Add your includes here */
/* END_USER_CODE(FOOTER) do not remove */

#endif /* USER_HOOKS */
/* end of file */
