/* @date 2025-03-27T11:04:29.350660095Z */

/**********************************************************************
 * @file Cse_Flashlight_hook_cfg.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 *
 * @generated_from 28cbcdad-312a-495d-9ce1-2d3c79f29110
 **********************************************************************/

#ifndef CSE_FLASHLIGHT_HOOK_CFG_H
#define CSE_FLASHLIGHT_HOOK_CFG_H

/**********************************************************************
 * Macros declaration definition
 **********************************************************************/
/* 
 * Define symbol ENABLE_HOOKS to enable the mechanism of hooks 
 * Enabled by default
 */
#define ENABLE_HOOKS
#ifdef ENABLE_HOOKS

#define Cse_ReadHook_Flashlight_timer_ipControl_On
#define Cse_ReadHook_Flashlight_timer_ipControl_Off
#define Cse_ReadHook_Flashlight_light_ipTimer_Tick
#define Cse_ReadHook_Flashlight_tempoManager_control_On
#define Cse_ReadHook_Flashlight_tempoManager_control_Off
#define Cse_ReadHook_Flashlight_onCount_ipLight_light
#define Cse_ReadHook_Flashlight_timer_ipControl2_switchOff
#define Cse_ReadHook_Flashlight_button_button_button
#define Cse_ReadHook_Flashlight_tempoManager_ipTempo_button
#define Cse_WriteHook_Flashlight_light_opLight_light
#define Cse_WriteHook_Flashlight_onCount_opCounts_data
#define Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff
#define Cse_TriggerHook_Flashlight_timer_opLight_Tick
#define Cse_TriggerHook_Flashlight_button_control_On
#define Cse_TriggerHook_Flashlight_button_control_Off

#endif /* ENABLE_HOOKS */

#endif /* CSE_<?COMPONENT_NAME_DEFINE?>_HOOK_CFG_H */

/* end of file */
