/* @date 2025-03-27T11:04:29.349286693Z */

/**********************************************************************
 * @file Cse_Flashlight.c
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 *
 * @generated_from 28cbcdad-312a-495d-9ce1-2d3c79f29110
 **********************************************************************/

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Tal.h" // tal_allocate
#include "Cse_cfg.h"
#include "Cse_Flashlight_hook.h"
#define CSE_C /* Macro to include only some specific parts of include files */
#include "Flashlight.h"

#include <string.h> // memset

#include "Timer_itf.h"
#include "Light_itf.h"
#include "Button_itf.h"
#include "Counter_itf.h"
#include "Tempo_itf.h"

#ifdef CSE_DEBUG
#include <stdio.h>
#define debug_cse(...) printf(__VA_ARGS__); fflush(stdout)
#else
#define debug_cse(...)
#endif

/**
 * Unique instance of the main entity
 */
Flashlight* pFlashlight;

/**
 * Required additional objects to instanciate
 */

task_descriptor task_descriptors[NUMBER_OF_TASKS];

static function_ptr task0_functions[4];
static Cse_instance_ptr task0_rteInstances[4];

static function_ptr task1_functions[1];
static Cse_instance_ptr task1_rteInstances[1];


/**********************************************************************
 * Function to Trigger Tick on opLight port
 * @generated_from 38b48e8e-9edb-4f25-8030-d2e76166b1ca
 * @generated_from 223688c0-a48b-4d23-8f87-d869296ad962
 **********************************************************************/
static void Cse_Trigger_Flashlight_timer_opLight_Tick(void){

	Cse_TriggerHook_Flashlight_timer_opLight_Tick_Start(&pFlashlight->to_light_ipTimer_Tick);
	debug_cse("DEBUG: Cse_Trigger_Flashlight_timer_opLight_Tick\n");
	pFlashlight->to_light_ipTimer_Tick.trigger = 1;
	Cse_TriggerHook_Flashlight_timer_opLight_Tick_Return(&pFlashlight->to_light_ipTimer_Tick);
}

/**********************************************************************
 * Function to Trigger On on control port
 * @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08
 * @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8
 **********************************************************************/
static void Cse_Trigger_Flashlight_button_control_On(void){

	Cse_TriggerHook_Flashlight_button_control_On_Start(&pFlashlight->to_timer_ipControl_On);
	debug_cse("DEBUG: Cse_Trigger_Flashlight_button_control_On\n");
	pFlashlight->to_timer_ipControl_On.trigger = 1;
	pFlashlight->to_tempoManager_control_On.trigger = 1;
	Cse_TriggerHook_Flashlight_button_control_On_Return(&pFlashlight->to_timer_ipControl_On);
}

/**********************************************************************
 * Function to Trigger Off on control port
 * @generated_from c2410e8a-16aa-4fd7-946d-af43b985ba08
 * @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555
 **********************************************************************/
static void Cse_Trigger_Flashlight_button_control_Off(void){

	Cse_TriggerHook_Flashlight_button_control_Off_Start(&pFlashlight->to_timer_ipControl_Off);
	debug_cse("DEBUG: Cse_Trigger_Flashlight_button_control_Off\n");
	pFlashlight->to_timer_ipControl_Off.trigger = 1;
	pFlashlight->to_tempoManager_control_Off.trigger = 1;
	Cse_TriggerHook_Flashlight_button_control_Off_Return(&pFlashlight->to_timer_ipControl_Off);
}


/**********************************************************************
 * Function to send light value on opLight port
 * @generated_from 48b8db33-57a9-4f78-a9c3-ed492905f3ae
 * @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5
 **********************************************************************/
static void Cse_Write_Flashlight_light_opLight_light(Boolean* data){
	// Copy byte by byte
	unsigned int byteIdx;

	Cse_WriteHook_Flashlight_light_opLight_light_Start(&pFlashlight->from_light_opLight_light);
	debug_cse("DEBUG: Cse_Write_Flashlight_light_opLight_light\n");

	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) &pFlashlight->from_light_opLight_light)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Flashlight_light_opLight_light_Return(&pFlashlight->from_light_opLight_light);
	
}

/**********************************************************************
 * Function to send data value on opCounts port
 * @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673
 * @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673
 **********************************************************************/
static void Cse_Write_Flashlight_onCount_opCounts_data(Integer* data){
	// Copy byte by byte
	unsigned int byteIdx;

	Cse_WriteHook_Flashlight_onCount_opCounts_data_Start(&pFlashlight->from_onCount_opCounts_data);
	debug_cse("DEBUG: Cse_Write_Flashlight_onCount_opCounts_data\n");

	for(byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pFlashlight->from_onCount_opCounts_data)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Flashlight_onCount_opCounts_data_Return(&pFlashlight->from_onCount_opCounts_data);
	
}

/**********************************************************************
 * Function to send switchOff value on opControl port
 * @generated_from 0c123f41-f825-4736-a34f-e120a337f4cd
 * @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a
 **********************************************************************/
static void Cse_Write_Flashlight_tempoManager_opControl_switchOff(Boolean* data){
	// Copy byte by byte
	unsigned int byteIdx;

	Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Start(&pFlashlight->from_tempoManager_opControl_switchOff);
	debug_cse("DEBUG: Cse_Write_Flashlight_tempoManager_opControl_switchOff\n");

	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) &pFlashlight->from_tempoManager_opControl_switchOff)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Flashlight_tempoManager_opControl_switchOff_Return(&pFlashlight->from_tempoManager_opControl_switchOff);
	
}


/**********************************************************************
 * Function to read On value on ipControl port
 * @generated_from 644c256e-801e-46df-be80-219fec881e01
 * @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8
 **********************************************************************/
static void Cse_Read_Flashlight_timer_ipControl_On(SignalEvent_On_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_timer_ipControl_On_Start(&pFlashlight->to_timer_ipControl_On);
	debug_cse("DEBUG: RTE_Read_Flashlight_timer_ipControl_On\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_On_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_timer_ipControl_On)[byteIdx];
	}
	pFlashlight->to_timer_ipControl_On.trigger = 0;
	Cse_ReadHook_Flashlight_timer_ipControl_On_Return(&pFlashlight->to_timer_ipControl_On);
}

/**********************************************************************
 * Function to read Off value on ipControl port
 * @generated_from 644c256e-801e-46df-be80-219fec881e01
 * @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555
 **********************************************************************/
static void Cse_Read_Flashlight_timer_ipControl_Off(SignalEvent_Off_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_timer_ipControl_Off_Start(&pFlashlight->to_timer_ipControl_Off);
	debug_cse("DEBUG: RTE_Read_Flashlight_timer_ipControl_Off\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Off_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_timer_ipControl_Off)[byteIdx];
	}
	pFlashlight->to_timer_ipControl_Off.trigger = 0;
	Cse_ReadHook_Flashlight_timer_ipControl_Off_Return(&pFlashlight->to_timer_ipControl_Off);
}

/**********************************************************************
 * Function to read Tick value on ipTimer port
 * @generated_from e74c94e1-684b-4aec-a446-57b7eff8b9e6
 * @generated_from 223688c0-a48b-4d23-8f87-d869296ad962
 **********************************************************************/
static void Cse_Read_Flashlight_light_ipTimer_Tick(SignalEvent_Tick_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_light_ipTimer_Tick_Start(&pFlashlight->to_light_ipTimer_Tick);
	debug_cse("DEBUG: RTE_Read_Flashlight_light_ipTimer_Tick\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Tick_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_light_ipTimer_Tick)[byteIdx];
	}
	pFlashlight->to_light_ipTimer_Tick.trigger = 0;
	Cse_ReadHook_Flashlight_light_ipTimer_Tick_Return(&pFlashlight->to_light_ipTimer_Tick);
}

/**********************************************************************
 * Function to read On value on control port
 * @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6
 * @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8
 **********************************************************************/
static void Cse_Read_Flashlight_tempoManager_control_On(SignalEvent_On_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_tempoManager_control_On_Start(&pFlashlight->to_tempoManager_control_On);
	debug_cse("DEBUG: RTE_Read_Flashlight_tempoManager_control_On\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_On_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_tempoManager_control_On)[byteIdx];
	}
	pFlashlight->to_tempoManager_control_On.trigger = 0;
	Cse_ReadHook_Flashlight_tempoManager_control_On_Return(&pFlashlight->to_tempoManager_control_On);
}

/**********************************************************************
 * Function to read Off value on control port
 * @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6
 * @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555
 **********************************************************************/
static void Cse_Read_Flashlight_tempoManager_control_Off(SignalEvent_Off_type* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_tempoManager_control_Off_Start(&pFlashlight->to_tempoManager_control_Off);
	debug_cse("DEBUG: RTE_Read_Flashlight_tempoManager_control_Off\n");
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Off_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->to_tempoManager_control_Off)[byteIdx];
	}
	pFlashlight->to_tempoManager_control_Off.trigger = 0;
	Cse_ReadHook_Flashlight_tempoManager_control_Off_Return(&pFlashlight->to_tempoManager_control_Off);
}

/**********************************************************************
 * Function to read light value on ipLight port
 * @generated_from c027c956-bc59-467c-a000-446044b609e3
 * @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5
 **********************************************************************/
static void Cse_Read_Flashlight_onCount_ipLight_light(Boolean* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_onCount_ipLight_light_Start(&pFlashlight->from_light_opLight_light);
	debug_cse("DEBUG: RTE_Read_Flashlight_onCount_ipLight_light\n");
	Cse_ReadHook_Flashlight_onCount_ipLight_light_Return(&pFlashlight->from_light_opLight_light);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->from_light_opLight_light)[byteIdx];
	}
}

/**********************************************************************
 * Function to read switchOff value on ipControl2 port
 * @generated_from 42060ef5-7bab-484c-989e-8eec5da359e0
 * @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a
 **********************************************************************/
static void Cse_Read_Flashlight_timer_ipControl2_switchOff(Boolean* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Start(&pFlashlight->from_tempoManager_opControl_switchOff);
	debug_cse("DEBUG: RTE_Read_Flashlight_timer_ipControl2_switchOff\n");
	Cse_ReadHook_Flashlight_timer_ipControl2_switchOff_Return(&pFlashlight->from_tempoManager_opControl_switchOff);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->from_tempoManager_opControl_switchOff)[byteIdx];
	}
}

/**********************************************************************
 * Function to read button value on button port
 * @generated_from 6d305e60-ceb8-4426-8b00-1e85f8fa3445
 * @generated_from ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21
 **********************************************************************/
static void Cse_Read_Flashlight_button_button_button(Boolean* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_button_button_button_Start(&pFlashlight->from_UNCONNECTED_button_button);
	debug_cse("DEBUG: RTE_Read_Flashlight_button_button_button\n");
	Cse_ReadHook_Flashlight_button_button_button_Return(&pFlashlight->from_UNCONNECTED_button_button);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->from_UNCONNECTED_button_button)[byteIdx];
	}
}

/**********************************************************************
 * Function to read button value on ipTempo port
 * @generated_from 107d9c5c-35fc-4298-9679-81ed2cf3efa0
 * @generated_from 45a985c7-ac8d-4418-9e46-2b7cf0867b32
 **********************************************************************/
static void Cse_Read_Flashlight_tempoManager_ipTempo_button(Integer* data){
	unsigned int byteIdx;
	
	Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Start(&pFlashlight->from_UNCONNECTED_ipTempo_button);
	debug_cse("DEBUG: RTE_Read_Flashlight_tempoManager_ipTempo_button\n");
	Cse_ReadHook_Flashlight_tempoManager_ipTempo_button_Return(&pFlashlight->from_UNCONNECTED_ipTempo_button);
	for(byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pFlashlight->from_UNCONNECTED_ipTempo_button)[byteIdx];
	}
}



/**********************************************************************
 * Map the communication APIs to component instances
 * First function to call before Cse_task_descriptors_init & Cse_components_init
 **********************************************************************/
void Cse_component_instances_init(void){
	pFlashlight = tal_allocate(sizeof(Flashlight));

	/* Erase memory section for Behaviors proper implementation */
	memset(pFlashlight, 0, sizeof(Flashlight));

	Flashlight_ctor(pFlashlight);
	
	/* BEG: Timer Communication Interface Configuration */
	/* Write functions */
	/* Trigger functions */
	pFlashlight->timer.cse_itf.Trigger_opLight_Tick = &Cse_Trigger_Flashlight_timer_opLight_Tick;
	/* Read functions */
	pFlashlight->timer.cse_itf.Read_ipControl_On = &Cse_Read_Flashlight_timer_ipControl_On;
	pFlashlight->timer.cse_itf.Read_ipControl_Off = &Cse_Read_Flashlight_timer_ipControl_Off;
	pFlashlight->timer.cse_itf.Read_ipControl2_switchOff = &Cse_Read_Flashlight_timer_ipControl2_switchOff;
	/* Server call functions */
	/* END: Timer Cmmunication Interface Configuration */

	/* BEG: Light Communication Interface Configuration */
	/* Write functions */
	pFlashlight->light.cse_itf.Write_opLight_light = &Cse_Write_Flashlight_light_opLight_light;
	/* Trigger functions */
	/* Read functions */
	pFlashlight->light.cse_itf.Read_ipTimer_Tick = &Cse_Read_Flashlight_light_ipTimer_Tick;
	/* Server call functions */
	/* END: Light Cmmunication Interface Configuration */

	/* BEG: Button Communication Interface Configuration */
	/* Write functions */
	/* Trigger functions */
	pFlashlight->button.cse_itf.Trigger_control_On = &Cse_Trigger_Flashlight_button_control_On;
	pFlashlight->button.cse_itf.Trigger_control_Off = &Cse_Trigger_Flashlight_button_control_Off;
	/* Read functions */
	pFlashlight->button.cse_itf.Read_button_button = &Cse_Read_Flashlight_button_button_button;
	/* Server call functions */
	/* END: Button Cmmunication Interface Configuration */

	/* BEG: Counter Communication Interface Configuration */
	/* Write functions */
	pFlashlight->onCount.cse_itf.Write_opCounts_data = &Cse_Write_Flashlight_onCount_opCounts_data;
	/* Trigger functions */
	/* Read functions */
	pFlashlight->onCount.cse_itf.Read_ipLight_light = &Cse_Read_Flashlight_onCount_ipLight_light;
	/* Server call functions */
	/* END: Counter Cmmunication Interface Configuration */

	/* BEG: Tempo Communication Interface Configuration */
	/* Write functions */
	pFlashlight->tempoManager.cse_itf.Write_opControl_switchOff = &Cse_Write_Flashlight_tempoManager_opControl_switchOff;
	/* Trigger functions */
	/* Read functions */
	pFlashlight->tempoManager.cse_itf.Read_ipTempo_button = &Cse_Read_Flashlight_tempoManager_ipTempo_button;
	pFlashlight->tempoManager.cse_itf.Read_control_On = &Cse_Read_Flashlight_tempoManager_control_On;
	pFlashlight->tempoManager.cse_itf.Read_control_Off = &Cse_Read_Flashlight_tempoManager_control_Off;
	/* Server call functions */
	/* END: Tempo Cmmunication Interface Configuration */

}

/**********************************************************************
 * Function configuring each task.
 * Function to call just after Cse_component_instances_init
 **********************************************************************/
void Cse_task_descriptors_init(void){
  /* Runnable to task mapping */
  task0_functions[0] = (function_ptr)Timer_Timer;
  task0_rteInstances[0] = &pFlashlight->timer.cse_itf;
  /* Runnable to task mapping */
  task0_functions[1] = (function_ptr)Light_Light;
  task0_rteInstances[1] = &pFlashlight->light.cse_itf;
  /* Runnable to task mapping */
  task0_functions[2] = (function_ptr)Button_Button;
  task0_rteInstances[2] = &pFlashlight->button.cse_itf;
  /* Runnable to task mapping */
  task0_functions[3] = (function_ptr)Counter_OB_cnt;
  task0_rteInstances[3] = &pFlashlight->onCount.cse_itf;
  /* Runnable to task mapping */
  task1_functions[0] = (function_ptr)Tempo_TempoManager;
  task1_rteInstances[0] = &pFlashlight->tempoManager.cse_itf;

  /* Periodic task task0 configuration */
  task_descriptors[0].type = PERIODIC;
  task_descriptors[0].period = 50;
  task_descriptors[0].functions = task0_functions;
  task_descriptors[0].cse_instances = task0_rteInstances;
  task_descriptors[0].nfunctions = 4;

  /* Periodic task task1 configuration */
  task_descriptors[1].type = PERIODIC;
  task_descriptors[1].period = 100;
  task_descriptors[1].functions = task1_functions;
  task_descriptors[1].cse_instances = task1_rteInstances;
  task_descriptors[1].nfunctions = 1;


}

/**********************************************************************
 * Function calling all the init functions as configured in the model.
 * To be called after Cse_task_descriptors_init & Cse_component_instances_init
 **********************************************************************/
void Cse_components_init(void) {
	Timer_Timer_init(&pFlashlight->timer.cse_itf);
	Light_Light_init(&pFlashlight->light.cse_itf);
	Button_Button_init(&pFlashlight->button.cse_itf);
	Counter_OB_cnt_init(&pFlashlight->onCount.cse_itf);
	Tempo_TempoManager_init(&pFlashlight->tempoManager.cse_itf);
}

/* end of file */
