/* @date 2025-03-27T11:04:29.348597310Z */

/**********************************************************************
 * @file Cse_cfg.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 1.0.0
 *
 * @generated_from 28cbcdad-312a-495d-9ce1-2d3c79f29110
 **********************************************************************/


#ifndef CSE_CFG_H
#define CSE_CFG_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "task_descriptor.h" /* task_descriptor declaration */

#include "Timer_type.h"
#include "Light_type.h"
#include "Button_type.h"
#include "Counter_type.h"
#include "Tempo_type.h"

/**********************************************************************
 * Macros declaration
 **********************************************************************/
/*
 * Number of predefined tasks
 */
#define NUMBER_OF_TASKS 2

/*
 * Tasks ids definition
 */
#define TASK_0 0
#define TASK_1 1

/*
 * Behaviors in tasks position index definition
 */
#define TASK_0_timer_Timer 0
#define TASK_0_light_Light 1
#define TASK_0_button_Button 2
#define TASK_0_onCount_OB_cnt 3
#define TASK_1_tempoManager_TempoManager 0

/**********************************************************************
 * Functions declaration
 **********************************************************************/
/*
 * Map the communication APIs to component instances
 * First function to call before Cse_task_descriptors_init & Cse_components_init
 */
void Cse_component_instances_init(void);

/*
 * Function configuring each task.
 * Function to call just after Cse_component_instances_init
 */
void Cse_task_descriptors_init(void);

/*
 * Function calling all the init functions as configured in the model.
 * To be called after Cse_task_descriptors_init & Cse_component_instances_init
 */
void Cse_components_init(void);

/*
 * Extern declaration of task_descriptors variable for its access from the TAL.
 */
extern task_descriptor task_descriptors[NUMBER_OF_TASKS];

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* CSE_CFG_H */

/* end of file */
