/* @date 2025-03-27T11:04:29.490918692Z */

/************************************************
 * @file Flashlight_internal_types.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from 28cbcdad-312a-495d-9ce1-2d3c79f29110
 ***********************************************/

#ifndef FLASHLIGHT_INTERNAL_TYPES_H
#define FLASHLIGHT_INTERNAL_TYPES_H

#include <stdbool.h>


/**********************************************************************
 * Data Types used in statemachines and activities definition
 **********************************************************************/

#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool    Boolean;
#endif

#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int     Integer;
#endif

#ifndef Real_DEFINITION
#define Real_DEFINITION
typedef double   Real;
#endif

#ifndef String_DEFINITION
#define String_DEFINITION
typedef char *  String;
#endif

#ifndef TRUE
#define TRUE    true
#endif

#ifndef FALSE
#define FALSE   false
#endif

#endif //#ifndef FLASHLIGHT_INTERNAL_TYPES_H

/* end of file */