/* @date 2025-03-27T11:04:29.455661253Z */

/**********************************************************************
 * @file Flashlight.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from 28cbcdad-312a-495d-9ce1-2d3c79f29110
 **********************************************************************/

#ifndef FLASHLIGHT_H
#define FLASHLIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Flashlight_internal_types.h"
#include "Light.h"
#include "Button.h"
#include "Timer.h"
#include "Tempo.h"
#include "Counter.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from 28cbcdad-312a-495d-9ce1-2d3c79f29110 */	 
typedef struct Flashlight{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Flashlight*);

	/**
	 * @brief Public attribute for composition relation to Timer:timer
	 * @generated_from f9537694-2e80-4aca-bac5-a6cb3b75f5ac
	 */
	struct Timer timer;
		
	/**
	 * @brief Public attribute for composition relation to Light:light
	 * @generated_from 6e9a1d1d-4193-43ed-aacf-a71ed6655f5d
	 */
	struct Light light;
		
	/**
	 * @brief Public attribute for composition relation to Button:button
	 * @generated_from 23bf4ffb-6928-4427-8c0c-388f7437f152
	 */
	struct Button button;
		
	/**
	 * @brief Public attribute for composition relation to Counter:onCount
	 * @generated_from ed853e7f-b784-46e3-bb0f-4d27649ac5d0
	 */
	struct Counter onCount;
		
	/**
	 * @brief Public attribute for composition relation to Tempo:tempoManager
	 * @generated_from c9c61785-831d-403c-b4f6-106210278a24
	 */
	struct Tempo tempoManager;
		
	/**********************************************************************
	 * Communication & Scheduling Environment - Shared variables declaration
	 **********************************************************************/
	/* @generated_from 644c256e-801e-46df-be80-219fec881e01 */
	/* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */
	/* @generated_from 2a5cfbed-4c72-454a-842c-93489f4eb2ca */
	SignalEvent_On_type to_timer_ipControl_On;
	 
	/* @generated_from 644c256e-801e-46df-be80-219fec881e01 */
	/* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */
	/* @generated_from 2a5cfbed-4c72-454a-842c-93489f4eb2ca */
	SignalEvent_Off_type to_timer_ipControl_Off;
	 
	/* @generated_from 48b8db33-57a9-4f78-a9c3-ed492905f3ae */
	/* @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5 */
	/* @generated_from e8c145dc-c7ba-4c89-8efa-21deb348c4a7 */
	/* @generated_from c0a88fa1-c2ac-4151-aceb-8c871945d512 */
	Boolean from_light_opLight_light;
	 
	/* @generated_from e74c94e1-684b-4aec-a446-57b7eff8b9e6 */
	/* @generated_from 223688c0-a48b-4d23-8f87-d869296ad962 */
	/* @generated_from 48abb342-f8fe-42c2-b014-5356c5479919 */
	SignalEvent_Tick_type to_light_ipTimer_Tick;
	 
	/* @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673 */
	/* @generated_from f7b0b053-71a4-4f90-a8fc-bf0bae341673 */
	/* @generated_from 2147d210-a9df-419e-a27b-355ad3112c12 */
	Integer from_onCount_opCounts_data;
	 
	/* @generated_from 0c123f41-f825-4736-a34f-e120a337f4cd */
	/* @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a */
	/* @generated_from 557d6e00-0b06-4ab8-92fb-fc67e6c07e20 */
	Boolean from_tempoManager_opControl_switchOff;
	 
	/* @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6 */
	/* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */
	/* @generated_from 62ae5e2c-6d87-44cf-b60b-7ad2043552a8 */
	SignalEvent_On_type to_tempoManager_control_On;
	 
	/* @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6 */
	/* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */
	/* @generated_from 62ae5e2c-6d87-44cf-b60b-7ad2043552a8 */
	SignalEvent_Off_type to_tempoManager_control_Off;
	 
	/* @generated_from 6d305e60-ceb8-4426-8b00-1e85f8fa3445 */
	/* @generated_from ce6e6cb5-2f9a-45e2-ab24-460b69aa7b21 */
	/* @generated_from 62ae5e2c-6d87-44cf-b60b-7ad2043552a8 */
	Boolean from_UNCONNECTED_button_button;
	 
	/* @generated_from 107d9c5c-35fc-4298-9679-81ed2cf3efa0 */
	/* @generated_from 45a985c7-ac8d-4418-9e46-2b7cf0867b32 */
	/* @generated_from 62ae5e2c-6d87-44cf-b60b-7ad2043552a8 */
	Integer from_UNCONNECTED_ipTempo_button;
	 
	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Flashlight;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 28cbcdad-312a-495d-9ce1-2d3c79f29110
 */
void Flashlight_ctor(Flashlight* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef FLASHLIGHT_H

/* end of file */