/* @date 2025-03-27T11:04:29.610394144Z */

/**********************************************************************
 * @file Light_Light.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1
 **********************************************************************/

/* Application code for statemachine "Light" */

#include "Light_Light.h"
#include "Light.h"

#define STATEMACHINE        Light_struct

/**********************************************************************
 * Function Light_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1
 **********************************************************************/
static void Light_struct_dtor(struct Light_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function Light_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1
 **********************************************************************/
void Light_struct_ctor(struct Light_struct * const self, struct Light* classifier) {
    /* Init pointer to destructor */
    self->dtor = Light_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * separate code of user-modifiable functions to prevent accidental
 * changes to code above.
 **********************************************************************/
#include "Light_Light_usr.c"

/**********************************************************************
 * Function _basic_Light_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1
 **********************************************************************/
void _basic_Light_init(Light_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T)0;
    instance->CURRENT_STATE_0 = LIGHT_STATE_T_VOID;

    StateMachine_init(instance);
}

/**********************************************************************
 * Function _basic_Light
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1
 **********************************************************************/
void _basic_Light(Light_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> Off */
        /* @generated_from a90e0cca-fb51-4170-844f-56105150982e */
        instance->CURRENT_STATE_0 = LIGHT_STATE_T_Off;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State Off */
        /* @generated_from 5858f93e-f96f-4e9b-85ff-5f011827768e */
        case LIGHT_STATE_T_Off: {
            instance->DONE_ACTIVITY = TRUE;
            Off_Do(instance); /* Do of LIGHT_STATE_T_Off */
            if( instance->EVENT == LIGHT_EVENT_T_Tick ) {
                /* Transition Off -> On */
                /* @generated_from fcf4dd37-a238-4df7-96d6-5fbe4ba4dfdc */
                instance->CURRENT_STATE_0 = LIGHT_STATE_T_On;
                instance->EVENT = LIGHT_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of LIGHT_STATE_T_Off */
        }
        /* State On */
        /* @generated_from 3a253292-aefb-4c22-a869-e088e324156d */
        case LIGHT_STATE_T_On: {
            instance->DONE_ACTIVITY = TRUE;
            On_Do(instance); /* Do of LIGHT_STATE_T_On */
            if( instance->EVENT == LIGHT_EVENT_T_Tick ) {
                /* Transition On -> Off */
                /* @generated_from 45c10847-ac26-4139-a9cc-e97aec3b8f58 */
                instance->CURRENT_STATE_0 = LIGHT_STATE_T_Off;
                instance->EVENT = LIGHT_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of LIGHT_STATE_T_On */
        }
        default: break;
    } /* end of switch */
}

/**********************************************************************
 * Function _basic_Light_end
 * Implements statemachine exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1
 **********************************************************************/
void _basic_Light_end(Light_struct *instance) {
    StateMachine_end(instance);
}

/* end of file */
