/* @date 2025-03-27T11:04:29.615843428Z */

/**********************************************************************
 * @file Light_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from 38175907-adc5-4f9f-9dc7-61cb1af8eafe
 **********************************************************************/

#ifndef CSE_LIGHT_ITF_H
#define CSE_LIGHT_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Light_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* @generated_from 48b8db33-57a9-4f78-a9c3-ed492905f3ae */
	/* @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5 */	
	void (*Write_opLight_light)(Boolean* msg);
	/* Trigger functions */
	/* Read functions */
	/* @generated_from e74c94e1-684b-4aec-a446-57b7eff8b9e6 */
	/* @generated_from 223688c0-a48b-4d23-8f87-d869296ad962 */  
	void (*Read_ipTimer_Tick)(SignalEvent_Tick_type* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Light *parent;
}Cse_Light_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1 */ 
void Light_Light_init(Cse_Light_Struct* self);
void Light_Light(Cse_Light_Struct* instance);
void Light_Light_end(Cse_Light_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1 */ 
#define Light(...) Light_Light(__VA_ARGS__)
/* @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1 */ 
#define Light_init(...) Light_Light_init(__VA_ARGS__)
/* @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1 */ 
#define Light_end(...) Light_Light_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */
/* @generated_from 48b8db33-57a9-4f78-a9c3-ed492905f3ae */
/* @generated_from 638296ee-eff2-47cf-a528-78cb187ad4e5 */	
void Cse_Write_opLight_light(Cse_Light_Struct* instance, Boolean* msg);

/* Trigger functions declaration */

/* Read functions declaration */
/* @generated_from e74c94e1-684b-4aec-a446-57b7eff8b9e6 */
/* @generated_from 223688c0-a48b-4d23-8f87-d869296ad962 */
void Cse_Read_ipTimer_Tick(Cse_Light_Struct* instance, SignalEvent_Tick_type* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Read_ipTimer_Tick(inst, data) inst->Read_ipTimer_Tick(data)
#define Cse_Write_opLight_light(inst, data) inst->Write_opLight_light(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_LIGHT_ITF_H */

/* end of file */
