/* @date 2025-03-27T11:04:29.613753858Z */

/**********************************************************************
 * @file Light_Light_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1
 **********************************************************************/

#ifdef STATEMACHINE

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define opLight_light   instance->opLight_light
#define opLight         opLight_light
#define poutData        instance->classifier->poutData

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Function Off_Do
 * Implements "Do" of State: Off
 * Do calls OpaqueBehavior: null
 *
 * @generated_from 5858f93e-f96f-4e9b-85ff-5f011827768e
 * @generated_from eb5c7e3f-39d4-4e53-9153-12ffb4163e21
 **********************************************************************/
static void Off_Do(Light_struct *instance) {
    /* BEG_USER_CODE(Do5858f93e-f96f-4e9b-85ff-5f011827768e) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    poutData=false;

    /* END_USER_CODE(Do5858f93e-f96f-4e9b-85ff-5f011827768e) do not remove */
}

/**********************************************************************
 * Function On_Do
 * Implements "Do" of State: On
 * Do calls OpaqueBehavior: null
 *
 * @generated_from 3a253292-aefb-4c22-a869-e088e324156d
 * @generated_from 0fda275c-8ff3-4f4a-a0d5-f91c0f211bff
 **********************************************************************/
static void On_Do(Light_struct *instance) {
    /* BEG_USER_CODE(Do3a253292-aefb-4c22-a869-e088e324156d) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    poutData=true;

    /* END_USER_CODE(Do3a253292-aefb-4c22-a869-e088e324156d) do not remove */
}

static void StateMachine_init(Light_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(init_state_machine) do not remove */
}

static void StateMachine_end(Light_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(end_state_machine) do not remove */
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

#endif /* STATEMACHINE */
/* end of file */
