/* @date 2025-03-27T11:04:29.624919676Z */

/**********************************************************************
 * @file Light.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from 38175907-adc5-4f9f-9dc7-61cb1af8eafe
 **********************************************************************/

#ifndef LIGHT_H
#define LIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Light_itf.h"
#include "Light_internal_types.h"
#include "Light_Light.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from 38175907-adc5-4f9f-9dc7-61cb1af8eafe */	 
typedef struct Light{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Light*);

	/**
	 * @brief Public attribute for composition relation to Boolean:poutData
	 * @generated_from ed0175ef-57ac-4aad-aedc-21113628d91f
	 */
	Boolean poutData;
		
	/**
	 * Data for Behavior Light
	 * @generated_from a779e9a7-a3f6-41ff-a973-2e642eef9fe1
	 */
	Light_struct Light;

	/**********************************************************************
	 * Communication Interface section
	 **********************************************************************/
	/**
	 * Communication interface
	 * @generated_from 38175907-adc5-4f9f-9dc7-61cb1af8eafe
	 */
	Cse_Light_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Light;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 38175907-adc5-4f9f-9dc7-61cb1af8eafe
 */
void Light_ctor(Light* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef LIGHT_H

/* end of file */