/* @date 2025-03-27T11:04:29.630090338Z */

/************************************************
 * @file Light_internal_types.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from 38175907-adc5-4f9f-9dc7-61cb1af8eafe
 ***********************************************/

#ifndef LIGHT_INTERNAL_TYPES_H
#define LIGHT_INTERNAL_TYPES_H

#include <stdbool.h>

/**********************************************************************
 * Data Type Boolean definition
 * @generated_from Type_UUID_SYSML_Primitives_Boolean
 **********************************************************************/
#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool Boolean;
#endif /* Boolean */


/**********************************************************************
 * Data Types used in statemachines and activities definition
 **********************************************************************/

#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool    Boolean;
#endif

#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int     Integer;
#endif

#ifndef Real_DEFINITION
#define Real_DEFINITION
typedef double   Real;
#endif

#ifndef String_DEFINITION
#define String_DEFINITION
typedef char *  String;
#endif

#ifndef TRUE
#define TRUE    true
#endif

#ifndef FALSE
#define FALSE   false
#endif

#endif //#ifndef LIGHT_INTERNAL_TYPES_H

/* end of file */