/* @date 2025-03-27T11:04:29.648389436Z */

/**********************************************************************
 * @file Model_Functions_Send_On.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from c5e6b354-4071-4512-b5c7-3e6022e4a257
 **********************************************************************/

#ifndef MODEL_FUNCTIONS_SEND_ON_H
#define MODEL_FUNCTIONS_SEND_ON_H

#include "Button_type.h" /* Datatypes for internal data */
#include "Button_internal_types.h" /* Datatypes for internal data */

#include <stdint.h>
typedef enum {
    MODEL_FUNCTIONS_SEND_ON_EVENT_T_NO_EVENT,
    MODEL_FUNCTIONS_SEND_ON_EVENT_T_On
} MODEL_FUNCTIONS_SEND_ON_EVENT_T;

#ifndef ESP_TYPES
#define ESP_TYPES
/* BEG_USER_CODE(local-types) do not remove */

typedef double  WALLCLOCK_T;  /* time type (can be any scalar) */
typedef void *  USERDATA_T;   /* replace this pointer by an anonymous struct if needed. */

/* END_USER_CODE(local-types) do not remove */
#endif

typedef struct Model_Functions_Send_On_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Model_Functions_Send_On_struct*);

    /* user data */
    USERDATA_T  USERDATA;

    /* data */
    Boolean     button_button;


    /* events */
    MODEL_FUNCTIONS_SEND_ON_EVENT_T EVENT;
    MODEL_FUNCTIONS_SEND_ON_EVENT_T (*peekEVENT)(struct Model_Functions_Send_On_struct *instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    MODEL_FUNCTIONS_SEND_ON_EVENT_T (*nextEVENT)(struct Model_Functions_Send_On_struct *instance); /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean     (*sendEVENT)(struct Model_Functions_Send_On_struct *instance, MODEL_FUNCTIONS_SEND_ON_EVENT_T event); /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct Button* classifier;

    /* internal */
    uint32_t    flow[1];
    WALLCLOCK_T WALL_CLOCK;
} Model_Functions_Send_On_struct;

void Model_Functions_Send_On_struct_ctor(struct Model_Functions_Send_On_struct * const self, struct Button* classifier);
void _basic_Model_Functions_Send_On_init(Model_Functions_Send_On_struct *instance);
Boolean _basic_Model_Functions_Send_On(Model_Functions_Send_On_struct *instance);
void _basic_Model_Functions_Send_On_end(Model_Functions_Send_On_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*MODEL_FUNCTIONS_SEND_ON_H*/
/* end of file */
