/* @date 2025-03-27T11:04:29.714999184Z */

/************************************************
 * @file Tempo_internal_types.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from 7cef0e29-9d40-498c-80be-05b489490d10
 ***********************************************/

#ifndef TEMPO_INTERNAL_TYPES_H
#define TEMPO_INTERNAL_TYPES_H

#include <stdbool.h>

/**********************************************************************
 * Data Type Real definition
 * @generated_from Type_UUID_SYSML_Primitives_Real
 **********************************************************************/
#ifndef Real_DEFINITION
#define Real_DEFINITION
typedef double Real;
#endif /* Real */


/**********************************************************************
 * Data Types used in statemachines and activities definition
 **********************************************************************/

#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool    Boolean;
#endif

#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int     Integer;
#endif

#ifndef Real_DEFINITION
#define Real_DEFINITION
typedef double   Real;
#endif

#ifndef String_DEFINITION
#define String_DEFINITION
typedef char *  String;
#endif

#ifndef TRUE
#define TRUE    true
#endif

#ifndef FALSE
#define FALSE   false
#endif

#endif //#ifndef TEMPO_INTERNAL_TYPES_H

/* end of file */