/* @date 2025-03-27T11:04:29.699216011Z */

/**********************************************************************
 * @file Tempo_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from 7cef0e29-9d40-498c-80be-05b489490d10
 **********************************************************************/

#ifndef CSE_TEMPO_ITF_H
#define CSE_TEMPO_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Tempo_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* @generated_from 0c123f41-f825-4736-a34f-e120a337f4cd */
	/* @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a */	
	void (*Write_opControl_switchOff)(Boolean* msg);
	/* Trigger functions */
	/* Read functions */
	/* @generated_from 107d9c5c-35fc-4298-9679-81ed2cf3efa0 */
	/* @generated_from 45a985c7-ac8d-4418-9e46-2b7cf0867b32 */  
	void (*Read_ipTempo_button)(Integer* msg);
	/* @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6 */
	/* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */  
	void (*Read_control_On)(SignalEvent_On_type* msg);
	/* @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6 */
	/* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */  
	void (*Read_control_Off)(SignalEvent_Off_type* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Tempo *parent;
}Cse_Tempo_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from e74afbae-3205-4e38-bdb0-f37be3968c29 */ 
void Tempo_TempoManager_init(Cse_Tempo_Struct* self);
void Tempo_TempoManager(Cse_Tempo_Struct* instance);
void Tempo_TempoManager_end(Cse_Tempo_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from e74afbae-3205-4e38-bdb0-f37be3968c29 */ 
#define TempoManager(...) Tempo_TempoManager(__VA_ARGS__)
/* @generated_from e74afbae-3205-4e38-bdb0-f37be3968c29 */ 
#define TempoManager_init(...) Tempo_TempoManager_init(__VA_ARGS__)
/* @generated_from e74afbae-3205-4e38-bdb0-f37be3968c29 */ 
#define TempoManager_end(...) Tempo_TempoManager_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */
/* @generated_from 0c123f41-f825-4736-a34f-e120a337f4cd */
/* @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a */	
void Cse_Write_opControl_switchOff(Cse_Tempo_Struct* instance, Boolean* msg);

/* Trigger functions declaration */

/* Read functions declaration */
/* @generated_from 107d9c5c-35fc-4298-9679-81ed2cf3efa0 */
/* @generated_from 45a985c7-ac8d-4418-9e46-2b7cf0867b32 */
void Cse_Read_ipTempo_button(Cse_Tempo_Struct* instance, Integer* msg);
/* @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6 */
/* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */
void Cse_Read_control_On(Cse_Tempo_Struct* instance, SignalEvent_On_type* msg);
/* @generated_from 4d67b6fb-1fe4-466e-9a22-bb0ca0272fa6 */
/* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */
void Cse_Read_control_Off(Cse_Tempo_Struct* instance, SignalEvent_Off_type* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Read_ipTempo_button(inst, data) inst->Read_ipTempo_button(data)
#define Cse_Write_opControl_switchOff(inst, data) inst->Write_opControl_switchOff(data)
#define Cse_Read_control_On(inst, data) inst->Read_control_On(data)
#define Cse_Read_control_Off(inst, data) inst->Read_control_Off(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_TEMPO_ITF_H */

/* end of file */
