/* @date 2025-03-27T11:04:29.709744402Z */

/**********************************************************************
 * @file Tempo.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from 7cef0e29-9d40-498c-80be-05b489490d10
 **********************************************************************/

#ifndef TEMPO_H
#define TEMPO_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include <Tal.h>
#include "Tempo_itf.h"
#include "Tempo_internal_types.h"
#include "Tempo_TempoManager.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from 7cef0e29-9d40-498c-80be-05b489490d10 */	 
typedef struct Tempo{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Tempo*);

	/**
	 * @brief Public attribute for composition relation to Real:tempo
	 * @generated_from 3b3d45db-1989-48d0-a9da-4caa20cfcc05
	 */
	Real tempo;
		
	/**
	 * Data for Behavior TempoManager
	 * @generated_from e74afbae-3205-4e38-bdb0-f37be3968c29
	 */
	TempoManager_struct TempoManager;

	/**********************************************************************
	 * Communication Interface section
	 **********************************************************************/
	/**
	 * Communication interface
	 * @generated_from 7cef0e29-9d40-498c-80be-05b489490d10
	 */
	Cse_Tempo_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Tempo;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 7cef0e29-9d40-498c-80be-05b489490d10
 */
void Tempo_ctor(Tempo* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef TEMPO_H

/* end of file */