/* @date 2025-03-27T11:04:29.698823198Z */

/**********************************************************************
 * @file Tempo_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from 7cef0e29-9d40-498c-80be-05b489490d10
 **********************************************************************/

#include "Tempo.h"
#include "Tempo_itf.h"
#include "Tempo_TempoManager.h"
#include "Tal.h" // tal_getTime

/**********************************************************************
 * Init function invoked for component initialization purpose.
 **********************************************************************/
void TempoManager_init(Cse_Tempo_Struct* inst) {
    /* Get component Tempo from "parent" */
    Tempo *pTempo = inst->parent;

    /* Get behavior tempoManager from the Tempo */
    TempoManager_struct *tempoManager = &pTempo->TempoManager;


    /* Initialization job which can be done in a separated function or inlined. */
    _basic_TempoManager_init(tempoManager);
}

/**********************************************************************
 * Main function Body of behavior "TempoManager"
 **********************************************************************/
void TempoManager(Cse_Tempo_Struct* inst) {
    /* Get component Tempo from "parent" */
    Tempo *pTempo = inst->parent;

    /* Get behavior tempoManager from the Tempo */
    TempoManager_struct *tempoManager = &pTempo->TempoManager;

    /* read input(s) */
    Cse_Read_ipTempo_button(inst, &tempoManager->ipTempo_button);

    /* handle external event(s) */
    tempoManager->EVENT = TEMPOMANAGER_EVENT_T_NO_EVENT;
    {// cppcheck shadowVariable
        /* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */
        SignalEvent_On_type signalEvent_On;
        Cse_Read_control_On(inst, &signalEvent_On);
        if(signalEvent_On.trigger == TRUE) {
            tempoManager->EVENT = TEMPOMANAGER_EVENT_T_On;
        }
    }
    if(tempoManager->EVENT == TEMPOMANAGER_EVENT_T_NO_EVENT) {
        /* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */
        SignalEvent_Off_type signalEvent_Off;
        Cse_Read_control_Off(inst, &signalEvent_Off);
        if(signalEvent_Off.trigger == TRUE) {
            tempoManager->EVENT = TEMPOMANAGER_EVENT_T_Off;
        }
    }
    /* handle internal event (s) */

    /* update WALL_CLOCK */
    tempoManager->WALL_CLOCK = tal_GetTime();

    /* Copy data in */
    pTempo->tempo = tempoManager->ipTempo_button;

    (void)_basic_TempoManager(tempoManager);

    /* write output(s) */
    Cse_Write_opControl_switchOff(inst, &tempoManager->opControl_switchOff);

}

/**********************************************************************
 * Exit function invoked at execution ending
 **********************************************************************/
void TempoManager_end(Cse_Tempo_Struct* inst) {
    /* Get component Tempo from "parent" */
    Tempo *pTempo = inst->parent;

    /* Get behavior tempoManager from the Tempo */
    TempoManager_struct *tempoManager = &pTempo->TempoManager;

    _basic_TempoManager_end(tempoManager);
}

/* end of file */
