/* @date 2025-03-27T11:04:29.696834803Z */

/**********************************************************************
 * @file Tempo_TempoManager_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from e74afbae-3205-4e38-bdb0-f37be3968c29
 **********************************************************************/

#ifdef STATEMACHINE

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define ipTempo_button      instance->ipTempo_button
#define ipTempo             ipTempo_button
#define opControl_switchOff instance->opControl_switchOff
#define opControl           opControl_switchOff
#define tempo               instance->classifier->tempo

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Function Init_Entry
 * Implements "Entry" of State: Init
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from d2e7fe36-7601-4d6d-ba8a-d6287820c036
 * @generated_from 8e38a400-ffaf-4965-b4e8-d1437c5e6ba8
 **********************************************************************/
static void Init_Entry(TempoManager_struct *instance) {
    /* BEG_USER_CODE(Entryd2e7fe36-7601-4d6d-ba8a-d6287820c036) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    extern bool myTimerRunning;
    extern timerId myTimerId;

    opControl = false;
    if(myTimerRunning == true){
        myTimerRunning = false;
        tal_CancelTimer(myTimerId);
    }

    /* END_USER_CODE(Entryd2e7fe36-7601-4d6d-ba8a-d6287820c036) do not remove */
}

/**********************************************************************
 * Function Tempo_Entry
 * Implements "Entry" of State: Tempo
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 3928578c-3cf3-418b-90b8-d7a9a6a3cf03
 * @generated_from b542607f-b696-4137-8f7c-bebf2e14cd16
 **********************************************************************/
static void Tempo_Entry(TempoManager_struct *instance) {
    /* BEG_USER_CODE(Entry3928578c-3cf3-418b-90b8-d7a9a6a3cf03) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    extern void *myFct(void* arg);

    opControl = false;
    if(ipTempo > 0){
        tal_CreateThread(myFct, instance);
    }

    /* END_USER_CODE(Entry3928578c-3cf3-418b-90b8-d7a9a6a3cf03) do not remove */
}

static void StateMachine_init(TempoManager_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(init_state_machine) do not remove */
}

static void StateMachine_end(TempoManager_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(end_state_machine) do not remove */
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

#endif /* STATEMACHINE */
/* end of file */
