/* @date 2025-03-27T11:04:29.522401310Z */

/**********************************************************************
 * @file Timer_Timer.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857
 **********************************************************************/

/* Application code for statemachine "Timer" */

#include "Timer_Timer.h"
#include "Timer.h"

#define STATEMACHINE        Timer_struct

/**********************************************************************
 * Function Timer_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857
 **********************************************************************/
static void Timer_struct_dtor(struct Timer_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************
 * Function Timer_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857
 **********************************************************************/
void Timer_struct_ctor(struct Timer_struct * const self, struct Timer* classifier) {
    /* Init pointer to destructor */
    self->dtor = Timer_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;
}
/**********************************************************************
 * separate code of user-modifiable functions to prevent accidental
 * changes to code above.
 **********************************************************************/
#include "Timer_Timer_usr.c"

/**********************************************************************
 * Function _basic_Timer_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857
 **********************************************************************/
void _basic_Timer_init(Timer_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T)0;
    instance->CURRENT_STATE_0 = TIMER_STATE_T_VOID;

    instance->Ticking_Entry_Timer_Send_Tick.classifier = instance->classifier;
    _basic_Timer_Send_Tick_init(&(instance->Ticking_Entry_Timer_Send_Tick));

    StateMachine_init(instance);
}

/**********************************************************************
 * Function _basic_Timer
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857
 **********************************************************************/
void _basic_Timer(Timer_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> off */
        /* @generated_from 0f3d0f8a-4f66-45d8-870d-aecd3e9cac0e */
        instance->CURRENT_STATE_0 = TIMER_STATE_T_off;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State off */
        /* @generated_from beb6e86c-095a-4c86-97a0-361dd45c218e */
        case TIMER_STATE_T_off: {
            if( instance->EVENT == TIMER_EVENT_T_On ) {
                /* Transition off -> Ticking */
                /* @generated_from 910dfbd8-8d15-49a2-a659-134b94604fdc */
                Ticking_Entry(instance); /* Entry Send Tick */
                instance->CURRENT_STATE_0 = TIMER_STATE_T_Ticking;
                instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
                instance->EVENT = TIMER_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of TIMER_STATE_T_off */
        }
        /* State Ticking */
        /* @generated_from df90ff0d-c524-4053-807b-f0e665e31fe9 */
        case TIMER_STATE_T_Ticking: {
            if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_0) >= (WALLCLOCK_T)1 ) {
                /* Transition Ticking -> Ticking */
                /* @generated_from ea0f5512-3882-4a01-8ac3-94cadf581515 */
                Ticking_Entry(instance); /* Entry Send Tick */
                instance->CURRENT_STATE_0 = TIMER_STATE_T_Ticking;
                instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
                instance->EVENT = TIMER_EVENT_T_NO_EVENT;
            } else if( switchOff == true ) {
                /* Transition Ticking -> off */
                /* @generated_from 26060223-b8bc-4efd-ab6b-5adf78a8c1be */
                instance->CURRENT_STATE_0 = TIMER_STATE_T_off;
                instance->EVENT = TIMER_EVENT_T_NO_EVENT;
            } else if( instance->EVENT == TIMER_EVENT_T_Off ) {
                /* Transition Ticking -> off */
                /* @generated_from 66244153-2193-4d33-9a91-405855596937 */
                instance->CURRENT_STATE_0 = TIMER_STATE_T_off;
                instance->EVENT = TIMER_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of TIMER_STATE_T_Ticking */
        }
        default: break;
    } /* end of switch */
}

/**********************************************************************
 * Function _basic_Timer_end
 * Implements statemachine exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857
 **********************************************************************/
void _basic_Timer_end(Timer_struct *instance) {
    StateMachine_end(instance);
}

/* end of file */
