/* @date 2025-03-27T11:04:29.569777576Z */

/**********************************************************************
 * @file Timer_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from 354afcb3-f3bf-4932-b27e-3534b29a5c91
 **********************************************************************/

#include "Timer.h"
#include "Timer_itf.h"
#include "Timer_Timer.h"
#include "Tal.h" // tal_getTime

/**********************************************************************
 * Init function invoked for component initialization purpose.
 **********************************************************************/
void Timer_init(Cse_Timer_Struct* inst) {
    /* Get component Timer from "parent" */
    Timer *pTimer = inst->parent;

    /* Get behavior timer from the Timer */
    Timer_struct *timer = &pTimer->Timer;


    /* Initialization job which can be done in a separated function or inlined. */
    _basic_Timer_init(timer);
}

/**********************************************************************
 * Main function Body of behavior "Timer"
 **********************************************************************/
void Timer(Cse_Timer_Struct* inst) {
    /* Get component Timer from "parent" */
    Timer *pTimer = inst->parent;

    /* Get behavior timer from the Timer */
    Timer_struct *timer = &pTimer->Timer;

    /* read input(s) */
    Cse_Read_ipControl2_switchOff(inst, &timer->ipControl2_switchOff);

    /* handle external event(s) */
    timer->EVENT = TIMER_EVENT_T_NO_EVENT;
    {// cppcheck shadowVariable
        /* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */
        SignalEvent_On_type signalEvent_On;
        Cse_Read_ipControl_On(inst, &signalEvent_On);
        if(signalEvent_On.trigger == TRUE) {
            timer->EVENT = TIMER_EVENT_T_On;
        }
    }
    if(timer->EVENT == TIMER_EVENT_T_NO_EVENT) {
        /* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */
        SignalEvent_Off_type signalEvent_Off;
        Cse_Read_ipControl_Off(inst, &signalEvent_Off);
        if(signalEvent_Off.trigger == TRUE) {
            timer->EVENT = TIMER_EVENT_T_Off;
        }
    }
    /* handle internal event (s) */

    /* update WALL_CLOCK */
    timer->WALL_CLOCK = tal_GetTime();
    timer->Ticking_Entry_Timer_Send_Tick.WALL_CLOCK = tal_GetTime();
    timer->Ticking_Entry_Timer_Send_Tick.node_2_Model_Functions_Send_Tick.WALL_CLOCK = tal_GetTime();

    /* Copy data in */
    pTimer->switchOff = timer->ipControl2_switchOff;

    (void)_basic_Timer(timer);

    /* trigger event(s) */
    if (timer->Ticking_Entry_Timer_Send_Tick.node_2_Model_Functions_Send_Tick.EVENT == MODEL_FUNCTIONS_SEND_TICK_EVENT_T_Tick) \
        {
        timer->Ticking_Entry_Timer_Send_Tick.node_2_Model_Functions_Send_Tick.EVENT = MODEL_FUNCTIONS_SEND_TICK_EVENT_T_NO_EVENT;
        Cse_Trigger_opLight_Tick(inst);
    }
}

/**********************************************************************
 * Exit function invoked at execution ending
 **********************************************************************/
void Timer_end(Cse_Timer_Struct* inst) {
    /* Get component Timer from "parent" */
    Timer *pTimer = inst->parent;

    /* Get behavior timer from the Timer */
    Timer_struct *timer = &pTimer->Timer;

    _basic_Timer_end(timer);
}

/* end of file */
