/* @date 2025-03-27T11:04:29.531853707Z */

/**********************************************************************
 * @file Timer_Timer_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857
 **********************************************************************/

#ifdef STATEMACHINE

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define ipControl2_switchOff    instance->ipControl2_switchOff
#define ipControl2              ipControl2_switchOff
#define switchOff               instance->classifier->switchOff

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Function Ticking_Entry
 * Implements "Entry" of State: Ticking
 * Entry calls Activity: Send Tick
 *
 * @generated_from df90ff0d-c524-4053-807b-f0e665e31fe9
 * @generated_from c5f625c5-0482-4745-99dd-232e7bad7464
 **********************************************************************/
static void Ticking_Entry(Timer_struct *instance) {
    /* BEG_USER_CODE(Entrydf90ff0d-c524-4053-807b-f0e665e31fe9) do not remove */

    (void)instance; /* MISRA rule 2.7 (unused parameter) */
    instance->DONE_ACTIVITY = _basic_Timer_Send_Tick(&(instance->Ticking_Entry_Timer_Send_Tick));

    /* END_USER_CODE(Entrydf90ff0d-c524-4053-807b-f0e665e31fe9) do not remove */
}

static void StateMachine_init(Timer_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance; /* MISRA rule 2.7 (unused parameter) */

    /* END_USER_CODE(init_state_machine) do not remove */
}

static void StateMachine_end(Timer_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */
    _basic_Timer_Send_Tick_end(&(instance->Ticking_Entry_Timer_Send_Tick));

    /* END_USER_CODE(end_state_machine) do not remove */
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

#endif /* STATEMACHINE */
/* end of file */
