/* @date 2025-03-27T11:04:29.595039194Z */

/**********************************************************************
 * @file Timer.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version 1.0.0
 *
 * @generated_from 354afcb3-f3bf-4932-b27e-3534b29a5c91
 **********************************************************************/

#ifndef TIMER_H
#define TIMER_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Timer_itf.h"
#include "Timer_internal_types.h"
#include "Timer_Timer.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************
 * Type definition
 **********************************************************************/
/** @generated_from 354afcb3-f3bf-4932-b27e-3534b29a5c91 */	 
typedef struct Timer{
	/**
	 * Function pointer to destructor function generated automatically
	 */
	void (*dtor)(struct Timer*);

	/**
	 * @brief Public attribute for composition relation to Boolean:switchOff
	 * @generated_from 96a48424-5f6f-44c7-90f3-9f3cbc31be20
	 */
	Boolean switchOff;
		
	/**
	 * Data for Behavior Timer
	 * @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857
	 */
	Timer_struct Timer;

	/**********************************************************************
	 * Communication Interface section
	 **********************************************************************/
	/**
	 * Communication interface
	 * @generated_from 354afcb3-f3bf-4932-b27e-3534b29a5c91
	 */
	Cse_Timer_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Timer;
/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 354afcb3-f3bf-4932-b27e-3534b29a5c91
 */
void Timer_ctor(Timer* self);
 

#ifdef __cplusplus
}
#endif

#endif //#ifndef TIMER_H

/* end of file */