/* @date 2025-03-27T11:04:29.604382701Z */

/************************************************
 * @file Timer_internal_types.h
 *
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 *
 * @generated_from 354afcb3-f3bf-4932-b27e-3534b29a5c91
 ***********************************************/

#ifndef TIMER_INTERNAL_TYPES_H
#define TIMER_INTERNAL_TYPES_H

#include <stdbool.h>

/**********************************************************************
 * Data Type Boolean definition
 * @generated_from Type_UUID_SYSML_Primitives_Boolean
 **********************************************************************/
#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool Boolean;
#endif /* Boolean */


/**********************************************************************
 * Data Types used in statemachines and activities definition
 **********************************************************************/

#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool    Boolean;
#endif

#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int     Integer;
#endif

#ifndef Real_DEFINITION
#define Real_DEFINITION
typedef double   Real;
#endif

#ifndef String_DEFINITION
#define String_DEFINITION
typedef char *  String;
#endif

#ifndef TRUE
#define TRUE    true
#endif

#ifndef FALSE
#define FALSE   false
#endif

#endif //#ifndef TIMER_INTERNAL_TYPES_H

/* end of file */