/* @date 2025-03-27T11:04:29.539688162Z */

/**********************************************************************
 * @file Timer_Timer_Send_Tick.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from c5f625c5-0482-4745-99dd-232e7bad7464
 **********************************************************************/

#ifndef TIMER_TIMER_SEND_TICK_H
#define TIMER_TIMER_SEND_TICK_H

#include "Timer_type.h" /* Datatypes for internal data */
#include "Timer_internal_types.h" /* Datatypes for internal data */

#include "Model_Functions_Send_Tick.h"

#include <stdint.h>
typedef enum {
    TIMER_SEND_TICK_EVENT_T_NO_EVENT
} TIMER_SEND_TICK_EVENT_T;

#ifndef ESP_TYPES
#define ESP_TYPES
/* BEG_USER_CODE(local-types) do not remove */

typedef double  WALLCLOCK_T;  /* time type (can be any scalar) */
typedef void *  USERDATA_T;   /* replace this pointer by an anonymous struct if needed. */

/* END_USER_CODE(local-types) do not remove */
#endif

typedef struct Timer_Send_Tick_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Timer_Send_Tick_struct*);

    /* user data */
    USERDATA_T                          USERDATA;

    /* data */
    Boolean                             ipControl2_switchOff;

    /* called behaviors */
    Model_Functions_Send_Tick_struct    node_2_Model_Functions_Send_Tick;

    /* events */
    TIMER_SEND_TICK_EVENT_T             EVENT;
    TIMER_SEND_TICK_EVENT_T             (*peekEVENT)(struct Timer_Send_Tick_struct *instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    TIMER_SEND_TICK_EVENT_T             (*nextEVENT)(struct Timer_Send_Tick_struct *instance); /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean                             (*sendEVENT)(struct Timer_Send_Tick_struct *instance, TIMER_SEND_TICK_EVENT_T event); \
        /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct Timer* classifier;

    /* internal */
    uint32_t                            flow[1];
    WALLCLOCK_T                         WALL_CLOCK;
} Timer_Send_Tick_struct;

void Timer_Send_Tick_struct_ctor(struct Timer_Send_Tick_struct * const self, struct Timer* classifier);
void _basic_Timer_Send_Tick_init(Timer_Send_Tick_struct *instance);
Boolean _basic_Timer_Send_Tick(Timer_Send_Tick_struct *instance);
void _basic_Timer_Send_Tick_end(Timer_Send_Tick_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*TIMER_TIMER_SEND_TICK_H*/
/* end of file */
