/* @date 2025-03-27T11:04:29.571395874Z */

/**********************************************************************
 * @file Timer_itf.h
 *
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version 
 *
 * @generated_from 354afcb3-f3bf-4932-b27e-3534b29a5c91
 **********************************************************************/

#ifndef CSE_TIMER_ITF_H
#define CSE_TIMER_ITF_H

/**********************************************************************
 * Includes declaration
 **********************************************************************/
#include "Timer_type.h"


/* CSE Component Structure declaration ----------*/
typedef struct{
	/* Write functions */
	/* Trigger functions */
	/* @generated_from 38b48e8e-9edb-4f25-8030-d2e76166b1ca */
	/* @generated_from 223688c0-a48b-4d23-8f87-d869296ad962 */  
	void (*Trigger_opLight_Tick)(void);
	/* Read functions */
	/* @generated_from 644c256e-801e-46df-be80-219fec881e01 */
	/* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */  
	void (*Read_ipControl_On)(SignalEvent_On_type* msg);
	/* @generated_from 644c256e-801e-46df-be80-219fec881e01 */
	/* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */  
	void (*Read_ipControl_Off)(SignalEvent_Off_type* msg);
	/* @generated_from 42060ef5-7bab-484c-989e-8eec5da359e0 */
	/* @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a */  
	void (*Read_ipControl2_switchOff)(Boolean* msg);
	/* Server call functions */
	/* pointer to parent */
	struct Timer *parent;
}Cse_Timer_Struct;

/* Behavior functions declaration--------------- */
/* @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857 */ 
void Timer_Timer_init(Cse_Timer_Struct* self);
void Timer_Timer(Cse_Timer_Struct* instance);
void Timer_Timer_end(Cse_Timer_Struct* self);

#ifndef CSE_C

/* Behavior API Mapping -------------------------*/
/* @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857 */ 
#define Timer(...) Timer_Timer(__VA_ARGS__)
/* @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857 */ 
#define Timer_init(...) Timer_Timer_init(__VA_ARGS__)
/* @generated_from bb5961b5-3662-41e6-9da3-acfc6a9d8857 */ 
#define Timer_end(...) Timer_Timer_end(__VA_ARGS__)

#ifdef CSE_CONTRACT
/* CSE Contract for documentation purpose -------*/
/* Write functions declaration */

/* Trigger functions declaration */
/* @generated_from 38b48e8e-9edb-4f25-8030-d2e76166b1ca */
/* @generated_from 223688c0-a48b-4d23-8f87-d869296ad962 */  
void Cse_Trigger_opLight_Tick(Cse_Timer_Struct* instance);

/* Read functions declaration */
/* @generated_from 644c256e-801e-46df-be80-219fec881e01 */
/* @generated_from 94cdab86-41e8-4eb5-89b1-271590a97ab8 */
void Cse_Read_ipControl_On(Cse_Timer_Struct* instance, SignalEvent_On_type* msg);
/* @generated_from 644c256e-801e-46df-be80-219fec881e01 */
/* @generated_from ec8bda96-4321-4ebc-a6bf-11d724651555 */
void Cse_Read_ipControl_Off(Cse_Timer_Struct* instance, SignalEvent_Off_type* msg);
/* @generated_from 42060ef5-7bab-484c-989e-8eec5da359e0 */
/* @generated_from ce8eef98-3abd-48d2-acb6-4458d9a2a56a */
void Cse_Read_ipControl2_switchOff(Cse_Timer_Struct* instance, Boolean* msg);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */
/* CSE API Mapping used at compilation phase ----*/
#define Cse_Trigger_opLight_Tick(inst) inst->Trigger_opLight_Tick()
#define Cse_Read_ipControl_On(inst, data) inst->Read_ipControl_On(data)
#define Cse_Read_ipControl_Off(inst, data) inst->Read_ipControl_Off(data)
#define Cse_Read_ipControl2_switchOff(inst, data) inst->Read_ipControl2_switchOff(data)

#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C*/

#endif /* CSE_TIMER_ITF_H */

/* end of file */
